### ISSUE TITLE
@proto.utwente.nl doesn't seem to work properly

### ISSUE THREAD

**Issue by hanotonah** [saproto/saproto#1007]
Mails get delivered only hours or days later if they are directed at a @proto.utwente.nl (known problem for board@, the function specific mails but also committee mails), or don't get delivered at all. D:
Senders sometimes get the error: 451 Temporary local problem - please try later and a message that the mail was not delivered.

Has been discussed in more detail on Slack!

**Comment by jonathanjuursema** [comment]
As far as we can see the e-mails are not rejected by our mail server. We see them arriving later than they have been sent, and around the sending time there are no indications of a message being bounced. 

We are waiting for a notification around the time the message is actually sent but not received, and forwarded bounce mails.

**Comment by thijsdortmann** [comment]
@saproto/board Is this still a problem? It seems like it was only a temporary disruption, so if that's the case, I'd like to close the Github issue :)

**Comment by jonathanjuursema** [comment]
Closed, this no longer seems to be a problem and the original issue did not look like a problem on our side. :)
