### ISSUE TITLE
Proto DokuWiki: first years seem to be unable to login

### ISSUE THREAD

**Issue by hanotonah** [saproto/saproto#1008]
The board has received multiple complaints, mostly from first years, that they are unable to login to the dokuwiki, even after trying the 'standard' steps (updating your password, syncing it, etc.). However, for the older people, these steps seem to work.

1 first year mentioned he got an error when trying to reach the members page: ''Permission Denied Sorry, you don't have enough rights to continue''. However, I dont know if he was logged in or not :p

**Comment by jonathanjuursema** [comment]
@saproto/board has this happened again?

**Comment by hanotonah** [comment]
I heard it several times again in the whatsappgroup of the firstyears, so it seems like it is still a problem sadly.

**Comment by jonathanjuursema** [comment]
Okay, but as discussed two weeks ago we really need more information as we can't find anything wrong on our end. If this happens again could you ask them:

- Is the problem with logging in? If so, what error do you get? Can you logout en login on the Proto website with the same password? Did they try the password sync?
- Or is the problem with accessing a specific page AFTER logging in? Did they check if they were actually logged in? If they are really logged in, can they do a call [this page](https://wiki.proto.utwente.nl/start?do=check) and let us know what they get?
- Who are they?

Could you send us the answers to these questions containing personal information via Slack?

**Comment by jonathanjuursema** [comment]
If you can ask in the Whatsapp Groups if the people experiencing these issues can try the above things and give us feedback before tomorrow, perhaps we can fix it.

**Comment by hesje** [comment]
I’m having the same issue.
I cannot login with the same username and password as I use for the proto website, even after a password sync.

**Comment by jonathanjuursema** [comment]
I'm afraid this issue is dependent on #958 or another solution of the sorts. Tried a number of things, but if the problems are still there I'm not sure if this can be fixed another way.

**Comment by jonathanjuursema** [comment]
By the way, I'm still waiting on the feedback requested [here](https://github.com/saproto/saproto/issues/1008#issuecomment-547016174).

Please Slack me a list of all people who have this issue, have them perform the debugging steps linked above and include the repsonses in that list.

**Comment by thijsdortmann** [comment]
All new members had blocked accounts on LDAP for a thusfar unknown. Manually unblocking them in AD solved the problem (for now).
