### ISSUE TITLE
Very important: Soundboard requests

### ISSUE THREAD

**Issue by hanotonah** [saproto/saproto#1011]
Hey hey beheer!

During a very productive evening in Protopolis, we encountered a youtube video of which some parts would be awesome in the soundboard! See attached zip.
[Snuivah.zip](https://github.com/saproto/saproto/files/3739750/Snuivah.zip)

Could you add them to the soundboard? :D

Good luck with all the more important stuff!! 
xoxo

**Comment by hanotonah** [comment]
Another 2 things!
[gadver.zip](https://github.com/saproto/saproto/files/3739838/gadver.zip)

**Comment by jonathanjuursema** [comment]
Done bij @thijsdortmann
