### ISSUE TITLE
OmNomCom Sound adjustment when error is given

### ISSUE THREAD

**Issue by sainety** [saproto/saproto#1012]
Heyo,

Right now, if the omnomcom has the 'you're too hasty!!' error, the same sound is played as when you do succesfully scan your card, which is confusing and probably also the reason people often don't notice it happening. Can this be fixed?

<2 Sanne

**Comment by jonathanjuursema** [comment]
According the the application flow this shouldn't happen, and I can't test it right now unfortunately. :(

Could you demo me this Tuesday?

**Comment by jonathanjuursema** [comment]
If this is the same as #1015 then this would be difficult to fix since (as in time consuming considering the gains). Isn't it enough that you don't hear the OmNomCom sound?

**Comment by sainety** [comment]
You do actually hear the OmNomCom sound, which is the problem. It sounds like your order has been processed successfully when it actually hasn't been.

**Comment by jonathanjuursema** [comment]
With "OmNomCom Sound" I mean the cookiemonster, not the beep. Are we talking about the same sound?

**Comment by sainety** [comment]
As far as I've noticed, the cookiemonster sound plays when the 'too hasty' error happens as well as when an order succeeds

**Comment by jonathanjuursema** [comment]
Okay, we'll have to recreate that tomorrow then.

**Comment by sainety** [comment]
We haven't notice this being an issue anymore
