### ISSUE TITLE
Website on mobile phone does weird stuff when editing pages

### ISSUE THREAD

**Issue by hanotonah** [saproto/saproto#1022]
Hello hello dear beheer,

When trying to edit a page on my phone, weird stuff happens to the text. When trying to type a space after a word, instead whatever you typed before will be duplicated, making it near impossible to edit a page using my phone. 

Is this a known issue? Is it possible to fix it?

Thank you for your time!!

<3

**Comment by jonathanjuursema** [comment]
I think this might have to do with the editor on the site (it's not just a text field, it also does some fancy stuff so you see text you want in bold in bold for example) and your phones keyboard's autocomplete or another feature of the keyboard. I'm not sure of the editor we use on the site is really meant to be used on mobile. Can you see if you still have the problem if disable autocomplete on your mobile phone and/or switch to the default keyboard?

**Comment by hanotonah** [comment]
Without autocomplete it indeed works like normal! Thank you!

**Comment by jonathanjuursema** [comment]
Nice. :)
