### ISSUE TITLE
Pop-up tab in Website when food is going to be ordered

### ISSUE THREAD

**Issue by StijnSlebos** [saproto/saproto#1023]
Whenever Proto decides to order food from elsewhere, now a link to a docs form is sent through whatsapp groups. Why not, whenever the board decides to open this form, a new tab appears in the proto-site, where you are directly linked to this form or a similar functionality. (maybe link it directly to the omnomcom?) Now also people outside the whatsapp groups \ socially offline can also order. & I can just go to the Proto site and order, instead of scrolling up in one of the many whatsapp groups!

**Comment by ttsmit** [comment]
Include a counter showing how long you have till the ordering closes.
