### ISSUE TITLE
Poster request-form fields expansion

### ISSUE THREAD

**Issue by PhilippeTu** [saproto/saproto#1025]
Dear Committee,

We notice that some of the poster requests don't include all the information we need and the overview is not all too clear sometimes.

Could we have different fields for the requester to fill in as follows?
What would you like to request?
What is it for?
What date?
What time?
What location?
What price?
What info or other design requests should be on the design?
(the contact info part can stay the same)

Thank you!! :)
- GraphiCie

**Comment by thijsdortmann** [comment]
Fix :)
