### ISSUE TITLE
Birthday email

### ISSUE THREAD

**Issue by renske32** [saproto/saproto#1028]
Hello,

Ik had al eerder op slack een dingetje gezet over de birthday email en ik moest een issue aanmaken en ben dat vergeten te doen... Dus bij deze.

Kan ipv regards renske mulder er regards board 9.0 komen?
En we hebben een birthday foto!!! Kan die toegevoegd worden?

**Comment by renske32** [comment]
Ik krijg de birthday foto niet toegevoegd, maar die staat wel op slack..

**Comment by jonathanjuursema** [comment]
Could you include a link to the Slack message?
