### ISSUE TITLE
API limit protube

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#1029]
Almost every day we reach the Youtube API limit which sucks, since then we have to listen to Last Christmas - WHAM! again on Skyradio. Can we fix this?

**Comment by jonathanjuursema** [comment]
Quota increase limit request has been sent to YouTube!

**Comment by Jessseee** [comment]
We think the chance of our API qouta increasing is very small so for now #1083 is an option to make people more aware of the quota. For now we will close this issue.
