### ISSUE TITLE
Company Management System on website

### ISSUE THREAD

**Issue by Vlieking** [saproto/saproto#1032]
Hello HYTTIOAOAC,

As some of you might know, having a decent CRM as an Officer of External Affairs has always been a bit of a problem for past (and current) Externals. I think it would be of great value to have a decent CRM that does not change every year so that future externals have a good system to look up past partnerships and keep track of current ones.  

I understand that this wil likely be long term project that won't be finished that quickly, which is fine. If you guys are willing to take this upon you (which I would greatly appreciate) I would be willing to join your meetings every now and then (when you deem necessary) to go into more detail about what exactly needs to be implemented to make a good CRM, and I will try my best to get future Externals to continue using it as well.

**Comment by jonathanjuursema** [comment]
Perhaps it's wise if you can come to a meeting to discuss this. :)

**Comment by Vlieking** [comment]
I agree! I'll join you the third of december :)

**Comment by Jessseee** [comment]
@saproto/board Is this still a feature you want to be implemented?

**Comment by Jessseee** [comment]
@saproto/board Has chosen an external CMS, so this will not be implemented in the website.
