### ISSUE TITLE
New sounds for in the sounds board!

### ISSUE THREAD

**Issue by renske32** [saproto/saproto#1033]
Hallo,

Hannah en ik willen graag dit geluid in het soundboard onder de naam 'Nut'! Thanks in advance!! :D
[nut_ZKo5FA9.zip](https://github.com/saproto/saproto/files/3859232/nut_ZKo5FA9.zip) (Ik kon geen mp3 toevoegen en ik ben incapabel dus hierbij een zippie :) )

**Comment by thijsdortmann** [comment]
Done!
