### ISSUE TITLE
New member sound 

### ISSUE THREAD

**Issue by Vlieking** [saproto/saproto#1035]
Hi, you know how when someone makes an issue (like this one) a sound plays (like this one) (okay you should have been in the room but it was great im sure) 

Anyway, when a new person becomes a proto member, we should also have a sound play! Something fun, maybe the celebration time theme. Would this be possible? If yes, I'll provide some fun sound :)

Kind regards

**Comment by thijsdortmann** [comment]
That's definitely possible :) Please provide the sound - then I'll add it next beheeravond.

**Comment by Vlieking** [comment]
[one of us.zip](https://github.com/saproto/saproto/files/3887632/one.of.us.zip)
