### ISSUE TITLE
Itech inclusion main page

### ISSUE THREAD

**Issue by Vlieking** [saproto/saproto#1036]
Hello Beheer, 

When opening our website without being a member or having an account, you are greeted with some flavour text explaining creative technology. These days, we also have Interaction Technology as one of our studies. Could Itech be included in these flavour texts? 

Kind regards,

**Comment by jonathanjuursema** [comment]
Of course, if you can let us know what the texts should be. :)

**Comment by sainety** [comment]
Hannah is going to work on writing a bit of text for this, we'll get back to this once that is finished

**Comment by hanotonah** [comment]
https://docs.google.com/document/d/1EB8SE5C1-xHk55zm6k9i0FAWwfcLbN9j_h7N50GsXi4/edit?usp=sharing

The changed texts :)
