### ISSUE TITLE
Societies on Website

### ISSUE THREAD

**Issue by sainety** [saproto/saproto#1044]
Here is the issue for working societies into the proto website

Er op komen te staan als societies (niet als commissies) waarbij:
- De leden niet gezien worden als 'actief lid' door lid te zijn van de society
- Er staat bij events die worden gekoppeld aan societies (de 'organized by' unit) dat hij georganiseerd is door een society 
- Niet meetellen voor commissie related achievements want het is geen commissie :p
- Allergielijst moeten ze wel kunnen zien bij events 

There will be a forum on the 10th of december in which our proposel for societies can be reviewed by members. After this, there is a possibility for small changes to still happen in this setup, so postponing starting with this until after the 10th of december is advisable. 

<3 Ninetje

**Comment by jonathanjuursema** [comment]
Adding `feedback` while awaiting the mentioned forum. Please remove this label as soon as we can start. :)
