### ISSUE TITLE
Helper mail nog being sent. 

### ISSUE THREAD

**Issue by Vlieking** [saproto/saproto#1048]
Hello, 

This monday, an event was made (FriAD) which needed ERO's. However, there appeared to not have been any helper mail sent to the emergencie. (at least 3 people who have their helper mails turned on did not get it). So yeah... halp?

**Comment by jonathanjuursema** [comment]
As far as I can see noone has helper reminders set for the EmergenCie. Could you send me a message on Slack with who believe their reminders should be enabled for the EmergenCie?

**Comment by jonathanjuursema** [comment]
Okay so this is not the helper *reminder* emails, but instead the initial e-mails that committee members get when their committee has been picked as a helping committee.

**Comment by thijsdortmann** [comment]
This is most likely caused by #1072. This has been fixed, but the fix has not yet been approved/released.

**Comment by thijsdortmann** [comment]
Should be fixed now that #1072 is merged. Please reopen the issue if the problem occurs again :)
