### ISSUE TITLE
Printing page error [Priority!]

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#105]
When printing something, one can choose a number less than 1 for copies (0, -1, -2, etc.)
This results in free prints, or even profit, in order history.

IF you make the HTML5 number field with attribute `min="1"`, it should fix it.

**Comment by thijsdortmann** [comment]
And maybe also add a server-side check for orderline amounts.

**Comment by jonathanjuursema** [comment]
Yep. The HTML5 attribute and a server-side check should do the trick. We should also make sure the printer server supports this.
