### ISSUE TITLE
Nonmembers also appear in lists

### ISSUE THREAD

**Issue by MaartjeHuveneers** [saproto/saproto#1051]
When we look up members (for example when signing people up for events), all users appear in the list (so also the people who are no longer members), but we never use them. Could the list be at least ordered so that members appear on top and non-members after that? Now when you look up a common name, you have to scroll through all users

So nothing too urgent, but would be nice :)

**Comment by Jessseee** [comment]
Sorry that we could not implement this during your board year 😉.  But, this feature has now been added and it is way more efficient indeed.
