### ISSUE TITLE
Achievement proposal: Participation Trophee

### ISSUE THREAD

**Issue by sainety** [saproto/saproto#1052]
Hey have you tried, 

We have a proposal for a new achievement: the participation trophee! This is an achievement that is given when a member has attended a certain % or Proto activities in a month. This would then be a % of all proto activities that actually has a sign up. 
We like the idea of having achievements for 25%, 75% and 100%, if it isn't too much work to make the achievement for different percentages. What do you guys think about this? 

<3 board 9.0

**Comment by xadya** [comment]
Should then be a % per year or per module I think. Otherwise it's only feasible for the first generations of proto members
