### ISSUE TITLE
Weekly Update on frontpage 

### ISSUE THREAD

**Issue by renske32** [saproto/saproto#1054]
Tijdens de wissel ALV kregen we nog de opmerking dat de weekly update er gek uitziet op de homepage. De weekly update is namelijk best lang doordat hij smal is en steekt helemaal uit aan de onderkant van de website en dit ziet er raar uit... Kan dit veranderd worden. Misschien kan je een soort optie maken met 'meer weergeven' oid..!

**Comment by Jessseee** [comment]
I will close this issue for now but this might still be looked at in a future redesign of the home page.
