### ISSUE TITLE
Enhanced legibility of video title on ProTube

### ISSUE THREAD

**Issue by JRitmeester** [saproto/saproto#1056]
Hi all,

I was just sitting in Proto when I wanted to spot what artist was playing over the speakers and on-screen. However, the video had a white backdrop so I couldnt read it from where I was sitting. Also, Im HELLA lazy so I didnt want to get up. 
(I realise this is such a non-problem)
Would it be possible to have a small stroke around the letters, or something similar?

Edit: Of course I dont know how thick the stroke would have to be. Might have to be so big that it ruins the text altogether. But of course, it's just a suggestion.

**Comment by jonathanjuursema** [comment]
In the meantime, check the recently played list: https://www.proto.utwente.nl/protube/dashboard :)

**Comment by Jessseee** [comment]
We will combine all ProTube issues into a new repository where we will start to rebuilding the ProTube.
