### ISSUE TITLE
Calander synching participation type added

### ISSUE THREAD

**Issue by PhilippeTu** [saproto/saproto#1059]
When synching the Proto Calendar to your Google Calendar for example it's possible to only see synched events.
Would it be possible to define in the event description in your calendar what type(s) of participation you have with a certain event? (Participant, Helper, Organiser)

**Comment by jonathanjuursema** [comment]
This should already be there in the title?

![image](https://user-images.githubusercontent.com/1134192/71097921-1eed0800-21b1-11ea-815a-8864e742d513.png)

**Comment by PhilippeTu** [comment]
Oh yes it is, so sorry...

**Comment by jonathanjuursema** [comment]
Please re-open the issue if you miss something. :)
