### ISSUE TITLE
Protube Hits & Achievement pages

### ISSUE THREAD

**Issue by Vlieking** [saproto/saproto#1064]
Hi, merry christmas and such, 

The "achievement" and "Protube Hits" pages are, as of now, visible to all visitors of our website under the "association" section. Considering the contents of these pages, could they be moved to "for members" and made hidden for non-members?  (I wanted to do this, but these pages are not in the page admin toolie)

Cheers,

**Comment by jonathanjuursema** [comment]
Hey! 🎄

You can edit the position of these pages in the menu [here](https://www.proto.utwente.nl/menu). :)

Happy days! 🎉
