### ISSUE TITLE
IsAlfredThere.nl improvements - suggestions from Alfred!

### ISSUE THREAD

**Issue by jonathanjuursema** [saproto/saproto#1067]
So, had a talk with Alfred today and he had some suggestions for his IsAlfredThere.nl page. Let me put them down here. :)

- [ ] The default "I'll be back" time is 9AM tomorrow. Afred suggested it to be some time today, because he more often sets away for the same day then the next day. I propose to make the default time the next full hour on the same day.
- [ ] On the page, disable the "backspace" key as a browser navigation key. He often presses backspace when the input field is accidentally not fully selected (the datetime fields of bootstrap are not always that good).
- [ ] Add a fourth option where Alfred can choose his own text to show, such as "I'm on holiday, contact such and such."

**Comment by JonaMata** [comment]
It seems that to change the time, the time to change has to be selected twice. We should look into making this easier.
