### ISSUE TITLE
Updated poster-request form

### ISSUE THREAD

**Issue by PhilippeTu** [saproto/saproto#1068]
Dear Cool-Computer-Chickies,

We from the GraphiCie-overleg would like to change a few things from the Poster Request form as we’ve seen that it’s not always too clear what is expected of people.
As a seperate comment I included a screenshot of the current poster request form.
From top to bottom:

Your request
What is the date? -> What is the activity’s date?
What is the time? -> What is the activity’s time?
What is the location? -> What is the activity’s location?
What is going to cost? -> What is the activity’s participation fee?
New question -> What crucial element that must be on the poster? (e.g. company logo in one-line answer text box)
What should be on the design? -> Any ideas of yours you would like to see in the poster’s design?

Contact info
Who to contact? -> Who to contact (include your email address)

New block
Don’t forget, we need at least two weeks to design a poster!
Send my request! (button)

**Comment by PhilippeTu** [comment]
![current poster request form](https://user-images.githubusercontent.com/16576216/71903605-be743980-3164-11ea-8f5f-723aa01f3adb.png)

**Comment by thijsdortmann** [comment]
Done :)
