### ISSUE TITLE
"Protographer will receive food compensation" checkbox.

### ISSUE THREAD

**Issue by sainety** [saproto/saproto#1069]
Hey HYT, 

The guidelines in the 9.0 policy plan state that the Protography has no guarantee to receive food compensation during activities, where emergencie and guild of drafters would. However, it is strongly encouraged for committees to provide this compensation from their budget and in special cases they can receive the compensation. During the GMM discussing this topic, people made known that they'd appreciate an indicator on activities whether or not this food compensation would be there or not. 

Would it be possible for you to create a checkbox that when checked will make sure it is indicated on the activity or the helper request that the protographer will have a food compensation? Ideally it would only be visible for protographers. I can't promise that coming boards will keep this policy the same as we have it now, so keep that in mind when thinking about if this project is worth the time that needs to be put into it :)

<3 Sanne

**Comment by sainety** [comment]
This is not currently relevant anymore, because photographers will be receiving compensation following Proto's general helper food policy as of now

**Comment by jonathanjuursema** [comment]
Closed by request of @sainety.
