### ISSUE TITLE
Photo bugs

### ISSUE THREAD

**Issue by JonaMata** [saproto/saproto#1070]
This is the place to report any bugs encountered with the new photo service.

- [x] Failed upload message not very elaborate
- [x] Every failed upload gives a separate message box
- [x] Bulk photo upload causes errors
- [x] Protube slideshow crops proto logo and credits

**Comment by sainety** [comment]
It seems like there is a limit to the amount of photos that can be uploaded into one album: I don't know the exact amount, but I believe it's 218? Which seems random. This was found out with uploading the photos in increments, it did not seem to have an issue uploading 48 photos at once.

**Comment by sainety** [comment]
@JonaMata I tried uploading the cantus pictures into a seperate album, but it doesn't want to upload any photo's anymore right now, not even one at the time

**Comment by sainety** [comment]
Links to photo albums in the 'media from this event' section on events seems to be broken, cause i get a 404 error when i try to navigate to them

**Comment by JonaMata** [comment]
Photo navigation using arrows and buttons doesn't work in newer albums.

**Comment by emielsteegh** [comment]
title-less albums can be added.

Album titles cannot be edited by normal users. (what if typo)

Removing the thumbnail pic breaks things
https://user-images.githubusercontent.com/37158629/74846956-a67e0100-5331-11ea-848c-fa637392a3db.png

Other (non-admin) users can delete another users' photos out of an album

Publishing an album without thumbnail selected gives it a grey thumbnail, maybe highlight that no thumbnail has been selected yet, or make it pick the first picture if none was selected.

Currently an empty album is chilling in your database c:

**Comment by sainety** [comment]
Can confirm, can't get into the photo admin right now because of an error like the one Emiel posted above (thumb() on null) :)

**Comment by sainety** [comment]
I've heared from multiple people that the loading for the page with all gala photo's is very very slow. I've also gotten the following report:
 
![image](https://user-images.githubusercontent.com/35506182/77546022-8fd84600-6eab-11ea-8f4d-a5ed35f8ee84.png)

It seems to be that there's some issues with the site not really being able to handle loading all the pictures, especially when multiple people want to access it at the same time
