### ISSUE TITLE
Proto specific Wi-Fi

### ISSUE THREAD

**Issue by Vlieking** [saproto/saproto#1077]
Hello Beheer, 

I was trying to setup the Proto Homey, but it sadly could not connect to our wifi. When contacting our tech support Emile Nijssen, he said the following: 

"Homey kan inderdaad niet overweg met WPA2 Enterprise, net zoals bijv. een Chromecast. Je kunt het beste dan een eigen S.A. Proto Wi-Fi Netwerk maken. Misschien kun je dit zelfs gratis doen op basis van een server met internet delen op Windows."

Do you know how feasible this would be? Thanks in advance :)

**Comment by xadya** [comment]
AFAIK was LISA working on creating a network that would support these type of devices. I asked SNT what the progress on that is. I will hear back from them on Monday. I suggest waiting for that update before doing anything drastically :)

**Comment by xadya** [comment]
Got a reply faster. Apparently the network will not be released in the Zilverling at the start. So if we want this we have to do something ourselves. Sharing internet via Windows will often result in a quarentained account, so I think simply buying a router would be best. Best to discuss this during the meeting i suppose

**Comment by thijsdortmann** [comment]
We might still have a router in the 'beheerkrat', but I'm not sure. If it's still there, we could use that to create our own Proto WiFi :)

**Comment by Jessseee** [comment]
There is currently no router available, so this issue will be halted until we find a good reason to install the Homey with a Proto specific WiFi network.
