### ISSUE TITLE
Categorising events

### ISSUE THREAD

**Issue by hanotonah** [saproto/saproto#1082]
Hello hello,

During the good idea drink, someone came with the idea to label all activities on the website into categories (next to the educational tag that is already there) so people can more easily see if it's interesting to them. Next to that, a way to search on the website for specific categories of activities would be a great addition to that. I would see this as a default option to see "all", but with perhaps button to choose between e.g. career, fun, sport, etc. activities available. 

Have you guys ever thought about this?  Would it maybe be something to implement?

Thank you for your hard work!! :D

**Comment by jonathanjuursema** [comment]
Just a nosy fyi from the other side of the world: I recall a previous issue with the same idea that we ended up not doing because we couldn't settle on what would and wouldn't be categories. If there was going to be a good list of categories this could be done though.

**Comment by Jessseee** [comment]
@hanotonah if board still likes this idea could you consider making a list of possible categories?

**Comment by hanotonah** [comment]
The board would still like this to be implemented! We suggest the following categories:

- Career
- Educational
- Drinks
- Trips
- Recreational

If you have any questions or suggestions regarding the categories, let me know!

**Comment by Jessseee** [comment]
We will look into implementing this.
