### ISSUE TITLE
Achievement description

### ISSUE THREAD

**Issue by renske32** [saproto/saproto#1092]
Often people forget why they got an achievement or the board forgets why they gave an achievement. Maybe there is a possibility to add a small description or something where people can fill in why people got the achievement or what the occasion was :)

**Comment by Wilkuu-2** [comment]
Isn't this issue a bit stale? It seems that the descriptions are already implemented into achievements.

**Comment by Jessseee** [comment]
> Isn't this issue a bit stale? It seems that the descriptions are already implemented into achievements.

No, the point is to implement a comment on why the achievement was given by the board. The titel of the issue is a bit confusing.
