### ISSUE TITLE
Quote corner sorting

### ISSUE THREAD

**Issue by AppleFromHell** [saproto/saproto#1101]
The ability to sort the quotes in the quote corner on the amount of likes, and be able to find out who put the most quotes in there, and so on. For an example, see the Astatine website.

**Comment by xadya** [comment]
There was once decided not to do this because of that you then always get the same quotes over and over again. I'm personally not necessarily against the idea, but this is the background (@hyt) :)

**Comment by Jessseee** [comment]
We could implement this as a preference toggle. But this will probably take a while to be implemented as this is very low priority.

**Comment by Jessseee** [comment]
We have actually decided not to implement this, due to privacy reasons and possibility of public shaming.
