### ISSUE TITLE
Arrows and arrow keys in photo viewer not working

### ISSUE THREAD

**Issue by PetervanderBurgt** [saproto/saproto#1104]
Dear HYT,

I think the title is quite self explanatory, but sadly the arrows at the top of the photo and the arrow keys on my keyboard are not working for cycling between the photo's.
Not sure if this was a known issue or not.

Kindest Regards!

**Comment by Jessseee** [comment]
This is already mentioned in the #1070 Photo bugs issue and being fixed in the features/photos branch.
