### ISSUE TITLE
Sumup integration

### ISSUE THREAD

**Issue by Sebastiaanjai** [saproto/saproto#1105]
Tipcie was wondering if it would be possible to automatically transfer payment details to the sumup when pressing the 'complete with card' button. this would make completing orders with card significantly easier.

**Comment by jonathanjuursema** [comment]
As far as I know when we discussed this before Sumup was chosen we indicated we did not see an easy to use API to do this. This would require a dedicated android app if that even works, and as far as I remeber we told the tipcie this at that time. Unless Sumup added a new API I think the status is the same.

**Comment by Jessseee** [comment]
Due to SumUp not having a propper API this feature will probably not be implemented.
