### ISSUE TITLE
Companies on the main page

### ISSUE THREAD

**Issue by Vlieking** [saproto/saproto#1110]
Hi beheer, 

There is a good chance that another company will join the header of our main page soon-ish. Wooh! This would however mean that 6 companies would now occupy this company space, making it all very small (they are already basically unreadible on mobile). I was wondering if you could make it so that our main page could actually handle more companies on there while keeping them visible, perhaps make them scroll by or something.

Kind regards, 

Mick

**Comment by Jessseee** [comment]
We could definitely implement a scrolling gallery for the company logos.

**Comment by xadya** [comment]
I would propose creating an if statement around this. This was implemented earlier, but then the number of sponsors lowered to about 4 and scrolling was a bit weird. So an if #sponsors > X then do scrolling, otherwise do static.

**Comment by Jessseee** [comment]
We will try and make a properly responsive gallery, don't worry.

**Comment by Jessseee** [comment]
How does this look? When on full screen a max of 5 logos will be shown and it will not scroll if there are less than 5 logos. It can also be manually scrolled.

![image](http://g.recordit.co/HMzFjIFiwJ.gif)
