### ISSUE TITLE
Societies request form on the wiki

### ISSUE THREAD

**Issue by hanotonah** [saproto/saproto#1119]
Hey lovelies,

Since the whole societies business can hopefully start soon, the board thought it would be nice to add a request form on the Dokuwiki to simplify the process.  We thought of the following questions for this form:

1. What will the name of the society be? 
[short answer text box]
2. How many members will the society preferably consist of?
[short answer text box]
3. What will the society be organising? If a proposal for a date of an activity is already known, please state this as well.
[long answer text box]
4. In what way will the society contribute to Proto and its members?
[long answer text box]
5. Does the event need help from Proto's helper committees? (i.e. drafters, EROs, etc.)
[short answer text box]
6. If yes, what kind of helpers would the society need help from and how many helpers would it need?
[maybe a drop down menu for helper committees (if possible of course)? otherwise just a short answer text box]
7. Have you read the following document thoroughly: "Societies information"?
[short answer text box]

The board could add some information to the page explaining other parts of the singup process.
What are your thoughts on this? Do you think it would be nice to add?

Thank you for reading <3

**Comment by jonathanjuursema** [comment]
I see you're already looking to [this](https://wiki.proto.utwente.nl/requests/graphicie) page on the wiki. You can try to make the form yourself based on that example, after which we can lock it for editing by members. Please let us know if you have trouble getting the form to work!

**Comment by hanotonah** [comment]
Ah I see now! I thought forms could only be made by you guys for some reason. I'll look into it, thanks :)

**Comment by hanotonah** [comment]
I made a form that seems to work! Could you make sure only the board can edit the form?

**Comment by jonathanjuursema** [comment]
Everything under /requests is already protected. Only board can edit. :)
