### ISSUE TITLE
Link to a non-existing page

### ISSUE THREAD

**Issue by SilverGoldfish2** [saproto/saproto#1122]
The link 'websites', found on the proto website underneath 'for members', does not link to an existing page anymore.

**Comment by jonathanjuursema** [comment]
For me it seems to do work. The bottom item under "for members" links to [this page](https://wiki.proto.utwente.nl/general/websites) which for me shows the content I would expect. Can you check if it links to the same URL for you?

**Comment by SilverGoldfish2** [comment]
It previously linked to this site: https://wiki.proto.utwente.nl/members/other/websites
But it seems to work fine for me now, so problem solved, I guess

**Comment by jonathanjuursema** [comment]
Cool! Perhaps a caching issue or a very quick board member. :)
