### ISSUE TITLE
Some changes on the Proto site

### ISSUE THREAD

**Issue by MaartjeHuveneers** [saproto/saproto#1126]
Hi dear HYT,

I'm currently looking at some small changes on the site and also wanted to remove a couple of pages I don't think are very useful. By removing those, I hope to make it a little more clear to newer members where they can find things.

However, I can imagine you've worked very hard to make those pages, or have another issue with it, so I just wanted to ask you whether you have a problem with me making the following changes on the site:
- Association > Assocation Documents: Remove (Can be found through the Wiki link as well)
- Members > Sublime Text License: Remove (Can be found through the Wiki link as well)
- Members > ProTube hits: Remove (Can be found through "ProTube Dashboard" as well) 
- Members > ProTube dashboard: Move this page to your personal menu (at the top right)

If you don't have any issues with this, I will make those changes :)
If you do, just let me know, so we can discuss it again!

**Comment by Jessseee** [comment]
We don't see any issue with these changes, we will move the protube dashboard to the personal menu.

**Comment by MaartjeHuveneers** [comment]
Thanks!
