### ISSUE TITLE
News letter  archive

### ISSUE THREAD

**Issue by Frankieknarf** [saproto/saproto#1138]
I wanted to read an old newsletter from the site, but this wasn't possible because only the latest newsletter is visible. I couldn't find an archive of these on the site. Could this be made possible with a 'see olders news' button?

Thanks!

**Comment by Jessseee** [comment]
With "newsletter" you are referring to the weekly update?

**Comment by jonathanjuursema** [comment]
If you mean the weekly update, unfortunately we don't save these. The functionality that is now used for the weekly update was never meant for the way it is now used, so unfortunately there is no archive for that. :(

**Comment by Frankieknarf** [comment]
yeah, I meant weekly update. I thought it would be nice to add it because it slowly adds historical data to the association. the longer we have these kind of newletters saved, the more we can use them during lustra and stuff like that. It should be low priority however :P

**Comment by xadya** [comment]
Ugly way around this is of course to create an account with a mail connected to it and to save these mails in an inbox

**Comment by jonathanjuursema** [comment]
Also @Frankieknarf see your e-mail. :)

**Comment by Frankieknarf** [comment]
Haha, Thanks for the momentary solution!
