### ISSUE TITLE
Editing committees: Lustrum and KiCC not editable

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#114]
BoththeLustrum Committee and the Kick-in Committee behave in an unusual way: neither of them displays more than the committee description, also making it impossible to edit them.

**Comment by jonathanjuursema** [comment]
This is not a software bug. Took me ten minutes to figure out though. The descriptions of these committees had - for some reason - an HTML escape block (`<!-- ESCAPED CONTENT //-->`) in them that was not closed, hence escaping all website HTML that came after the description. While committee description ideally use markdown, use of HTML in these description is allowed (and intended). So please double check what you put there. :)

I changed the two committee entries on the live site.

Note to developers that run a local database copy, you can always enter the editing console for a committee by navigating to the committee and appending `/edit` to the URL.
