### ISSUE TITLE
Point system Lustrum

### ISSUE THREAD

**Issue by Vlieking** [saproto/saproto#1141]
Hi HYTTIOAOC

For the lustum next year we would like to have a point system for participants. Would it be possible to keep track of points on the website, have a ranking of sorts which the Lustum committee can edit?

Kind regards

**Comment by jonathanjuursema** [comment]
I think that (given the current capacity and the "one-off" ness of the request) it is better to use an existing solution for this, rather than making something custom.

Would something like [this](https://github.com/CTFd/CTFd) suit the needs for the challenges you are planning? It has team-forming, challenges you can grant points for manually and if users obtain a secret code, and more.

**Comment by Vlieking** [comment]
Hello, Sorry for the late reply

I think this CTF thingy has way more functionality than we desire. If that could be stripped away this is fine. We just want to be able to keep track of points publicly on the website, and have the lustrum committee have the rights to edit these

**Comment by jonathanjuursema** [comment]
Hey @Vlieking, sorry for the late reply. I've changed this into a feature proposal, but I'm unassigning it from me since I won't be having the time to complete this issue. It's still on the backlog so if another committee member has time they'll try to get to it!

**Comment by Vlieking** [comment]
Helow, are there any updates on this? :)

**Comment by Jessseee** [comment]
Unfortunately, none of the committee members has taken on this feature-proposal yet. But perhaps one of the new committee members (@MaxLiebe or @thomaskvklink) wants to try implementing this feature?

**Comment by thomasvklink** [comment]
@Vlieking I will have a go at it.

**Comment by Jessseee** [comment]
@Vlieking is there a specific deadline for when you would like to start using this system?

**Comment by Vlieking** [comment]
Asap :p. But it would be nice if it were to be finished at least before the start of the lustrum. Depending on how card it is to implement, after the first activity (which is the 14th of december) would also be nice

**Comment by Vlieking** [comment]
Hellooooo, any updates on this one? :)

**Comment by thomasvklink** [comment]
@Vlieking Yes! We have been actively working on it and are wrapping things up regarding the creation of leaderboards. Next step for us is adding entries and displaying them.

**Comment by Vlieking** [comment]
Hai, has it been wrapped up yet?

**Comment by Vlieking** [comment]
Heyo, any updates?

**Comment by thomasvklink** [comment]
@Vlieking We are wrapping up the final few functions and tweaks. Our current goal is to finish it by the end of this week.

**Comment by thomasvklink** [comment]
@Vlieking Our deadline has been set for tomorrow. We will post an update once it's implemented.

**Comment by Vlieking** [comment]
Cool!

**Comment by Vlieking** [comment]
Sooo, the official lustrum is now 5 days ago, is this still a possibility to be implemented soon? We would really appreciate it!

**Comment by Jessseee** [comment]
Wow, it's merged. Your board responsible is now able to add and edit leaderboards.
