### ISSUE TITLE
Make an option to reset 2FA without access to 2FA app.

### ISSUE THREAD

**Issue by Vlieking** [saproto/saproto#1142]
Ja ik moest een issue aanmaken dus there we go woopediscoopedi

Als 2FA nog aan staat bij je account maar je kan niet meer bij je 2FA app is dat naar want dan kan je niet meer inloggen, das jammer, huiliehuilie :(:(

Vriendelijke groetjes

**Comment by jonathanjuursema** [comment]
Took the liberty to make the title a little bit clearer. :P
