### ISSUE TITLE
Rotary logo in proto banner

### ISSUE THREAD

**Issue by Vlieking** [saproto/saproto#1144]
Hi, as you might have seen in the pull requests, Emile would like to have the Athom logo rotate in the banner cuz that looks cool. Sebas said Emile already made this happen in the pull request (lmao). Could this be done? You would make our partnered company very happy.

Kind regards,

**Comment by Jessseee** [comment]
This is a very nice idea. I will fix up his pull request, but I don't see any other problem with implementing this.
