### ISSUE TITLE
Improve password reset usability

### ISSUE THREAD

**Issue by jonathanjuursema** [saproto/saproto#116]
The password reset currently works, but there is not really a feedback mechanism. The user gets no confirmations of their actions, which may lead them to attempt multiple resets.

Note for developers: currently everything extends build-in functions, so it may be useful just to develop our own independent system.

**Comment by cmitz** [comment]
The pre-filled value in the password field is `correct horse battery staple`. This shouldn't be as a HTML `value` but a `placeholder`
