### ISSUE TITLE
Randomize company order on Company page. 

### ISSUE THREAD

**Issue by Vlieking** [saproto/saproto#1169]
Hi guys, 

Right now, the companies on the career page are in a set order, making certain companies always appear first, giving those companies an "advantage" over others. Since all these companies pay (theoretically) the same to be on this page, could this order perhaps be randomized? 

Kind regards,

**Comment by Vlieking** [comment]
Hi, this isn't *really* my problem anymore since I'm an oldfart now, but I was wondering why this was suddenly closed, as it doesn't seem to be implemented yet?

**Comment by Vlieking** [comment]
Ah, I see that you merged it with the order of the logo bar, which is not what I meant lol. 

> "Right now, the companies on the **career page** are in a set order"

kusjes

**Comment by Jessseee** [comment]
My bad, I misread the issue. I will make the requested changes later.
