### ISSUE TITLE
weekly newsletter timelimit

### ISSUE THREAD

**Issue by Sebastiaanjai** [saproto/saproto#1198]
the weekly newsletter can currently only be posted once a week, this is quite annoying.
can this be 12 hours less? or perhaps be removed completely?

**Comment by jonathanjuursema** [comment]
It's the *weekly* newsletter, do you want to send it more often than once a week?

**Comment by Sebastiaanjai** [comment]
the intention is not to send it more than once a week, however it would be nice to be able to send it on monday morning if the last newsletter was sent in the afternoon or evening (so slightly less than 7 days)

**Comment by jonathanjuursema** [comment]
I've checked the code and as far as I can tell this is already implemented. You can only send the newsletter if in the current calander week (mon-sun) you have not already sent it. So theoretically you should be able to send one on sunday (provided you did not send one earlier that week)  and then again one on monday.

When I check the site I see one has been sent yesterday (monday) so the button is (correctly) greyed out today, tuesday in the same week.

Have you walked into this issue (sent previous week on monday evening, cannot send next week on monday morning) before?

**Comment by jonathanjuursema** [comment]
See the code over here as well: https://github.com/saproto/saproto/blob/master/app/Models/Newsletter.php#L86-L92

**Comment by Sebastiaanjai** [comment]
ah if this is the case then there should be no issue, perhaps the button to send the weekly newsletter was displayed incorrectly for some reason.   if this issue happens again next week ill create a new issue (minor bug fix)

**Comment by jonathanjuursema** [comment]
Awesome! Perhaps no activities were included in the newsletter yet, that also would trigger the button to be blocked!

**Comment by jonathanjuursema** [comment]
Please feel free to re-open this issue if the problem occurs again. :)
