### ISSUE TITLE
Committee emails not working properly

### ISSUE THREAD

**Issue by hanotonah** [saproto/saproto#1211]
Hey hey,

The board@ email still goes to Board 9.0, and some committee members do not get email when they are part of a committee, or still get email when they already have left, even though it is correct on the website. 
Could you take a look at it?
Thanks!!!

Hugs,
Hannah

**Comment by Sebastiaanjai** [comment]
Issue also found in other committees (TIPCie)

**Comment by Jessseee** [comment]
Is this still issue still occurring?

**Comment by hanotonah** [comment]
I haven't seen any Board mail, so that's good. However, I'm pretty sure I should've received some emails directed to Educacie (I sent them from my personal mail with educacie in cc), which I did not, even though I am part of the committee on the website.

**Comment by Jessseee** [comment]
Did you get the last email sent to the EducaCie today?

**Comment by hanotonah** [comment]
Yes I did!

**Comment by Jessseee** [comment]
This does not seem to be a problem anymore.
