### ISSUE TITLE
Clicking user with pending membership redirects to "your profile" 

### ISSUE THREAD

**Issue by maximdeleeuw** [saproto/saproto#1216]
Out of curiosity, I tried clicking on a member listed as having his birthday. When I did, I wasn't able to see the other person's profile as my own was shown instead. Searching for the member, and clicking on the name, also results in the same bug. 

Not sure if others have mentioned this too, did not see the same bug listed already.

Kind regards,
Maxim

**Comment by Jessseee** [comment]
I cannot replicate this bug. Could you ask some other members to see if they can replicate is?

**Comment by maximdeleeuw** [comment]
I checked again, and it appears it only happens with a user called Wouter
Bleker.

Kind regards / Met vriendelijke groet,
Maxim de Leeuw | Student Creative Technology

M +316 50 56 06 42
E maximdeleeuw@gmail.com
W LinkedIn

**Comment by Jessseee** [comment]
Ah I see, the issue is with any user that has a pending membership.
