### ISSUE TITLE
OmNomCom category visibility

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#122]
I would like to be able to edit the visibility of categories in all applications and the manual orderline tool.
What I image: editing a category will become more, not only changing the name, but also having checkboxes for visibility. One box for each application (omnomcom, pilscie, alfred) and one checkbox for the "manually add an orderline" tool.

If possible, would be sweet

**Comment by jonathanjuursema** [comment]
This can be done via a pull request in the [config file](https://github.com/saproto/saproto/blob/master/config/omnomcom.php). Given that changes like these haven't been requested in the past 5 years and if they'll occur they will be few and far between the time it'll cost us to databasify the OmNomCom stores and make a management application for them exceeds the effort to manually change them once in a while by far. (In addition we want to be involved in any other uses of the OmNomCom to prevent technical issues and oversights, so any changes to the stores should be approved by us anyway.)

For displaying what's shown in the 'manually add an orderline', this can be an extra checkbox on the category overview. But we're also looking in a 'search drop down' alternative to deply site-wide, so I'll close this for now.
