### ISSUE TITLE
Member cards not printing

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#123]
Omnomcom screen has error "cannot print file"

**Comment by jonathanjuursema** [comment]
The printer service on hestia is not running for some reason. I'm not sure when either of us will have time to fix this. But it WILL work before the registration next Tuesday. :)

**Comment by thijsdortmann** [comment]
If the Omnomcom screen (= Hestia) presents an error upon printing, the service is running, as it is the print service that it generating that error popup.

**Comment by thijsdortmann** [comment]
Also, didn't we have the same problem with printing documents to the document printer earlier?

**Comment by thijsdortmann** [comment]
I've restarted the print service and changed some firewall rules.

@renskruining Can you check if the issues are resolved? :)

**Comment by renskruining** [comment]
Sadly I cannot, as I'm not at Proto today. You want to ask Dennis.

With kind regards,
Rens Kruining

Treasurer of the Board of S.A. Proto
06-46518673 | treasurer@proto.utwente.nl

**Comment by thijsdortmann** [comment]
@DennisVinke Pretty please? :)

**Comment by jonathanjuursema** [comment]
@DennisVinke: I made a test print, should lay in the printer. If everything works, please close this issue. :)

**Comment by DennisVinke** [comment]
Printer did not print anything. Als no no error popped up on the Omnomcom.

**Comment by jonathanjuursema** [comment]
You only had to reboot the printer... For some reason the printer was stuck in maintenance mode. The issue with membercard printing had to do with the config file though. Both are fixed!
