### ISSUE TITLE
UT Address Book bug

### ISSUE THREAD

**Issue by MaartjeHuveneers** [saproto/saproto#1236]
I tried searching for a name in the UT address book, but I'm getting an error each time I try.

This is the error I get:

S.A. Proto | Error 500
array_filter() expects parameter 1 to be array, null given

This incident has already been reported: #96d8323ea07849edb9bc0b6d3dcb4f58

**Comment by Jessseee** [comment]
I am not able to replicate this. Does this happen with a particular search?

**Comment by MaartjeHuveneers** [comment]
It happens for me with every search I tried up to now:
100
s1906400
Maartje

If you want me to try some other inputs, I can

**Comment by Jessseee** [comment]
A yeah, you're right I was able to reproduce the issue. I was just looking at the wrong thing. I will look into it.

**Comment by Jessseee** [comment]
The address book was fixed a while ago, but I now also added the menu item back to the for members tab.
