### ISSUE TITLE
Revoke up/downvote on Good Idea Board

### ISSUE THREAD

**Issue by MaartjeHuveneers** [saproto/saproto#1237]
When you accidentally click on upvote or downvote you can't revoke your vote anymore afterwards :( You can only switch votes, from upvote to downvote and the other way around.

Would be nice if revoking your vote would also be possible by clicking on the thumbs up/down again.

**Comment by Jessseee** [comment]
Yeah, we already spotted this issue. This is a duplicate of #1181.

**Comment by MaartjeHuveneers** [comment]
Oops, didn't see it before :p
