### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by maximdeleeuw** [saproto/saproto#1240]
About 2 weeks ago, I sent a mail about the fact that I was unable to log in anymore. I have received a new phone, but the 2FA was coupled to my old phone. I need the 2FA to login, and to relink the 2FA to my new phone, but my current one is obviously not linked so I am unable to do anything. Can you guys manually remove my 2FA so that I can relink it?

**Comment by thomasvklink** [comment]
We looked at this yesterday, you should be able to set a 2FA again now.
