### ISSUE TITLE
Proto Wiki Poster Request added field

### ISSUE THREAD

**Issue by PhilippeTu** [saproto/saproto#1245]
![image](https://user-images.githubusercontent.com/16576216/102923571-421b5900-4490-11eb-9986-85930b52a4f1.png)

Please add a box below the requester's name for the requester to input their e-mail. We've come across a few instances where the poster-designer had no easy access to the contacts of the requester.

**Comment by Jessseee** [comment]
The field has been added.

**Comment by PhilippeTu** [comment]
Thanks :)
