### ISSUE TITLE
Incorrect Mollie payment calculations

### ISSUE THREAD

**Issue by JonaMata** [saproto/saproto#1248]
The numbers of Mollie payments on the website do not correspond correctly to the money received from and paid to Mollie. You can ask me for exact numbers to check things.

**Comment by JonaMata** [comment]
Mollie apparently update its pricing. It now differs for different payment methods (https://www.mollie.com/nl/pricing). This probably needs to be looked into.

**Comment by Jessseee** [comment]
Is this still an issue?

**Comment by Jessseee** [comment]
Bump?

**Comment by Jessseee** [comment]
Seemingly fixed
