### ISSUE TITLE
Search function within the Photo Albums overview

### ISSUE THREAD

**Issue by PhilippeTu** [saproto/saproto#1253]
Title says it all :)

**Comment by Jessseee** [comment]
Do you mean to search by name of the album? Because you can already do this with the search bar in the menu of the website.

**Comment by PhilippeTu** [comment]
No this is not true from what I've seen.
Searching for "Kick-In" shows events but not their photo albums.
Searching for "Kick-In 2017: Kick-Off" which is a photo album leads to no results.

**Comment by Jessseee** [comment]
Hm, yeah you might be right. I'll look into it.
