### ISSUE TITLE
Long link breaks table on company admin page

### ISSUE THREAD

**Issue by Sebastiaanjai** [saproto/saproto#1268]
Company admin tool second page is looking a bit.... funky
![image](https://user-images.githubusercontent.com/48732717/110345480-e55f2180-802e-11eb-9b4f-017a9e5c19cc.png)

**Comment by Sebastiaanjai** [comment]
page zoom is just at 100% btw

**Comment by Jessseee** [comment]
This problem is fixed in a pending update of the website. For now you can replace the large link with a shortened link. Using the short_url service in our website.
