### ISSUE TITLE
Integrate day of the year api in smart xp screens

### ISSUE THREAD

**Issue by Janwillemtv** [saproto/saproto#127]
This is a nice api to inegrate in the smartxp screens. A nice way to keep up to date and inform the people around proto.

https://www.daysoftheyear.com/contact/

**Comment by jonathanjuursema** [comment]
Unfortunately they (don't currently have a public API)[https://www.daysoftheyear.com/api-data-services/]. I'll close the ticket for now. If you've found another API or this one is available again, please let me know!
