### ISSUE TITLE
OmNomCom input issues

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#128]
On-screen keyboard: possibility for indication of Caps-Lock ON? (blue caps lock button)

cursor placement in text: even when putting cursor in the middle of the text, it still edits at the end.

**Comment by jonathanjuursema** [comment]
Won't fix. There is already a caps-lock indication: toggling caps lock toggles the display of the entire keyboard between caps and lowercase. In other words: the keyboard is very accurate. If a lowercase a is pressed a lowercase a is entered, if an uppercase A is pressed an uppercase A is entered. As for the cursor placement, this is the behavior of a keyboard library we're using. Changing this behavior means modifying the library defeating the purpose of using it.
