### ISSUE TITLE
"nodig" committee still exists, gives me extra email, pls fix

### ISSUE THREAD

**Issue by Vlieking** [saproto/saproto#1290]
I think I asked this before, but the "nodig"  committee (which you can find on my profile) is still linked on my account. It also forwards me all mail which is supposed to go to the videography. Could this committee please be removed? Thank you

**Comment by Jessseee** [comment]
This committee is indeed very broken and needs to be deleted manually in the database. We'll look into it.

**Comment by Jessseee** [comment]
Fixed!
