### ISSUE TITLE
Proto register form broke

### ISSUE THREAD

**Issue by hslagman** [saproto/saproto#1320]
Dear committee,

The SAPROTO register form is broke, the g-recaptcha does not render.

(function(){var w=window,C='___grecaptcha_cfg',cfg=w[C]=w[C]||{},N='grecaptcha';var gr=w[N]=w[N]||{};gr.ready=gr.ready||function(f){(cfg['fns']=cfg['fns']||[]).push(f);};w['__recaptcha_api']='https://www.google.com/recaptcha/api2/';(cfg['render']=cfg['render']||[]).push('onload');w['__google_recaptcha_client']=true;var d=document,po=d.createElement('script');po.type='text/javascript';po.async=true;po.src='https://www.gstatic.com/recaptcha/releases/6OAif-f8nYV0qSFmq-D6Qssr/recaptcha__en_gb.js';po.crossOrigin='anonymous';po.integrity='sha384-1BZAnvmSVrwc6MUiBUzN82/4puGcz95u2otz3KTBCb37nXefOfr/FBrXT4s8Xcuq';var e=d.querySelector('script[nonce]'),n=e&&(e['nonce']||e.getAttribute('nonce'));if(n){po.setAttribute('nonce',n);}var s=d.getElementsByTagName('script')[0];s.parentNode.insertBefore(po, s);})();

Putting this in the console when on the page will load it, to show you the problem.

Pls fix 😊

**Comment by Jessseee** [comment]
This issue has been fixed with the latest hotfix commit
