### ISSUE TITLE
Double allergy information in event admin

### ISSUE THREAD

**Issue by Vlieking** [saproto/saproto#1323]
Sup, 

When looking at the admin page for an event, certain people's allergies/dietary wishes are listed twice. (See Lustrum BBQ for an example), I'm assuming this is not supposed to be the case.

Kind regards,

**Comment by Jessseee** [comment]
This is probably because the participants are both signed up for the event and as helpers. This is not very nice but not a breaking issue. None the less it can probably be fixed quite easily.
