### ISSUE TITLE
Outside Menu first for drafter Omnomcom

### ISSUE THREAD

**Issue by Vlieking** [saproto/saproto#1330]
Aloha

When starting up the Drafter omnomcom application, the "inside" menu is currently displayed first. However, as the drinks are currently outside due to 'rona, it would be more useful if the outside menu can be displayed first. Would this be possible?

Kind regards,

**Comment by Jessseee** [comment]
I have already looked at this issue, but unfortunately it is not trivial to make this change in the source code. The easiest(?) way to change this might be to rename the `inside` category to make it sort first in alphabetical order, but I am not sure if this might brake anything.

**Comment by Jessseee** [comment]
As this is not something we can easily change in the source code I will close this issue.
