### ISSUE TITLE
Eelco: Counter voor VisCie donaties

### ISSUE THREAD

**Issue by jurvangeel** [saproto/saproto#140]
Het zou super leuk zijn als een counter bestaat voor de aantal VisCie donaties (misschien makkelijk te doen door een voorraad counter te laten lopen en die *-1 te doen o.i.d., desnoods negatief laten zijn)

**Comment by jonathanjuursema** [comment]
This is not done in a clean manner because that means rendering different products in a different way. Is this feature greatly desired, or is it also ok to reject this feature request?

**Comment by jurvangeel** [comment]
Fine, skip it

On Tue, Jan 24, 2017 at 9:02 PM, Jonathan Juursema <notifications@github.com
