### ISSUE TITLE
Eelco: Zichtbare terugknop in Omnomcom

### ISSUE THREAD

**Issue by jurvangeel** [saproto/saproto#141]
Bij het linken van een RFID kaart is geen terugknop aanwezig, waardoor effectief iemand de "geheime" resetknop moet gebruiken als niemand een RFID kaart koppelt.

**Comment by jonathanjuursema** [comment]
This is a bug, the categories have a z-index higher than the gray overlay. Normally, tapping anywhere outside the box should close the overlay. Will fix this.
