### ISSUE TITLE
link team seas omnomcom item to "donate" achievement

### ISSUE THREAD

**Issue by Mart1nus** [saproto/saproto#1410]
**DON'T POST PERSONAL INFORMATION OR SECURITY VULNERABILITIES ON GITHUB, THESE ISSUES ARE PUBLIC.**

First time submiting an issue? See [this guide](https://wiki.proto.utwente.nl/ict/issues). Incorrectly submitted issues will be closed without response.

Need to submit a security vulnerability? You can find our responsible disclosure policy [here](https://wiki.proto.utwente.nl/ict/responsible-disclosure).

**Comment by Mart1nus** [comment]
link team seas omnomcom item to "donate" achievement, so that the achievement works again for this new donation item

**Comment by JonaMata** [comment]
Might to smart to link this to an OmNomCom category instead. That way it doesn't have to be hardcoded.

**Comment by JonaMata** [comment]
The achievement is linked to the 'donation' category. So just assign that category to any donation product and it simply works.
