### ISSUE TITLE
Banner Issue,

### ISSUE THREAD

**Issue by jurvangeel** [saproto/saproto#142]
HoiHoi, de Huidige banner op de homepagina van de website zorgt ervoor dat plaatjes lelijk worden weergegeven. Ik zal de plaatjes even zo bewerken dat ze in ieder geval transparant zijn, maar de vierkanten logo's worden veel te klein gegenereerd

**Comment by jonathanjuursema** [comment]
I can make it like on the old website, with the little sliding thingy?

**Comment by thijsdortmann** [comment]
Maybe not give the logo's a fixed amount of room on the front page, but just let them keep their own width.

**Comment by jonathanjuursema** [comment]
If we do that we need to make changes again, I'd prefer a catch-it-all solution.
