### ISSUE TITLE
Replacing the orderline and dinner form

### ISSUE THREAD

**Issue by LouisVanMaurik** [saproto/saproto#1430]
At the moment: I need to make a google form. Add a dinner form on the website. (Then I order what was in the dinner form but that cant be done automatically). But after that, I need to write down every order of every person with the price in a orderline wizard.

If there would be a feature that I can make a dinner form, which already has a google form build in, I wouldn't have to make google form. AND I wouldn't have to type it over as an orderline. If you want to make my life really easy, it would be great if I can add the price of the bill as an after thought. Maybe you could make it check automatically if the bill corresponds with the sum of the prices people filled in. This creates one problem: helpers should have helpers discount. So on the google form, there should be option to say you are a helper. If you really want to make it fancy, you can maybe link dinner form to events. Then you could already see if people are helping during a event. So only if they are helping you have that option. If this is to much, it would be great that there is a message somewhere (probably at the place where you fill in the price of the bill) which says who filled in that they are a helper.

I know this is a bigggg feature, but I think it would be so handy.

**Comment by MaxLiebe** [comment]
Nils already started development on this with pull request #1272 . Whether or not this will necessarily be built on has to be decided.
