### ISSUE TITLE
I cannot enter the most recent withdrawal page

### ISSUE THREAD

**Issue by Mart1nus** [saproto/saproto#1444]
![image](https://user-images.githubusercontent.com/74311196/149140801-b06961f0-47ea-4a3b-85c0-6333899aa538.png)

Computer says no

when going to "withdrawals"; I get this error when clicking on "withdrawal" on withdrawal 83

**Comment by Mart1nus** [comment]
pls tell me when fixed, i kinda need this

**Comment by Jessseee** [comment]
Is this still an issue?

**Comment by Mart1nus** [comment]
Yes, but its just for withdrawal 83 (so not the most recent anymore)

Op wo 16 feb. 2022 20:46 schreef Jesse Visser ***@***.***>:
