### ISSUE TITLE
"Error 419: CSRF token mismatch" when trying to update bank account information

### ISSUE THREAD

**Issue by JRitmeester** [saproto/saproto#1451]
When trying to update my bank account information on my dashboard, I get the following screen:

![image](https://user-images.githubusercontent.com/35365196/151936800-6807570e-ede4-4124-9bdf-cb9685843190.png)

Since I figured this is authentication related, I tried to log out and back in, both using just my Proto account, and through the UT, but both give the same result. This is the only part of the website I get this, as far as I can tell. I saw issue #1417 describes similar problems, but I figured a making separate issue was more appropriate.

**Comment by MaxLiebe** [comment]
As you mentioned, duplicate of #1417. Therefore this issue has been closed.
