### ISSUE TITLE
unable to scroll through the withdrawal information

### ISSUE THREAD

**Issue by Mart1nus** [saproto/saproto#1472]
admin > withdrawals > account

you get a list with all used accounts. You can click on accounts to see more elaborate information about where the money was spent. But in some cases these lists become so long that they do not fit on screen anymore, simply solved by scrolling normally... However, scrolling does nothing. Dragging the scrollbar also has no effect.

**Comment by ysbrandB** [comment]
The withdrawals are scrollable, you may have to sometimes refresh the page.
