### ISSUE TITLE
Color inverted profile pictures in events

### ISSUE THREAD

**Issue by Sebastiaanjai** [saproto/saproto#1490]
Probably a super specific issue where the profile pictures of users appear to be colour inverted in events. 

Normal user profile
![Screenshot_20220302-200313](https://user-images.githubusercontent.com/48732717/156431078-d7ba9781-3db3-4ebf-a5f7-a41a6a1aeafd.jpg)

The same user in the event
![Screenshot_20220302-200307](https://user-images.githubusercontent.com/48732717/156431093-e02535d3-f23b-46a9-a59a-508220bc795f.jpg)

Screenshots taken on chrome on an android device.

P.s. the cake is not a lie, it'll come someday

**Comment by Jessseee** [comment]
Included in #1539
