### ISSUE TITLE
Pls disable my 2FA

### ISSUE THREAD

**Issue by Vlieking** [saproto/saproto#1491]
Hi, 

For a while now I haven't been able to log in to the proto website on my phone cuz of 2FA. This is kinda weird since it already has been disabled before but, without me activating it at any point, it's still an issue. AAAAAAAAAAAA.

Kind regards,

**Comment by Jessseee** [comment]
This is not a place for personal issue with the website, next time please send an email or whatsapp one of the committee members personally. However, it should be fixed by now.
