### ISSUE TITLE
Request: archive old website pages

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#150]
Book page
Board pages
Educational pages
About Proto page
Company database pages

(So bassically any page with information that might need to make a useful return on the new website)

**Comment by jonathanjuursema** [comment]
For the educational pages (and the book page if you want to merge them) as well as the board pages we have specific plans, so I'd wait putting them back manually as page. The company database is already back up. 

Regardless, you'll receive everything you need via e-mail. :)
