### ISSUE TITLE
Error 419 CSRF token mismatch (Cannot update bank information)

### ISSUE THREAD

**Issue by JRitmeester** [saproto/saproto#1510]
I was trying to update my IBAN on the dashboard after switching banks, but this gives me the title's error, CSRF token mismatch. I tried logging out and back in, but this had no effect.

**Comment by ysbrandB** [comment]
Hey, this is a known issue and while we currently are still looking for a more permanent fix there is a solution as described in the following document: https://wiki.proto.utwente.nl/_media/ict/csrf_token_mismatch_write-up.pdf
