### ISSUE TITLE
I hate photo albums

### ISSUE THREAD

**Issue by MaxLiebe** [saproto/saproto#1515]
AAAAAAAAAAAAAAAAA
Ok here's a list of everything wrong with photo albums:
- Photo's are too beeg for page
- It takes too long to skip between photo's (why reload the whole page? just use ajax lmao)
- Navigation sucks
- Some photo's thumbnails just don't load in

Instead of only focusing on fixing the navigation, I vouch for a complete rewrite of the photo album system
Thanks for coming to my TED talk,
Max

**Comment by Jessseee** [comment]
Yes, what he said...

**Comment by Jessseee** [comment]
Compiled issues in #1539.
