### ISSUE TITLE
Proper ProTube remote

### ISSUE THREAD

**Issue by thijsdortmann** [saproto/saproto#153]
The current ProTube remote was only built for testing purposes. A new, user-friendly remote should be implemented.

**Comment by renskruining** [comment]
The existing queue is now missing ): Could it come back?

**Comment by thijsdortmann** [comment]
It will in the proper remote. In the temporary remote it was slightly broken and buggy, so I removed it do to quite a lot of complaints.

**Comment by renskruining** [comment]
since last update here was 11 days ago, I figured something undocumented happened. but okay

**Comment by thijsdortmann** [comment]
As long as the issue isn't closed, there is no proper remote, so also nothing to document about.

**Comment by renskruining** [comment]
but it changed! d:

Kind regards/vriendelijke groet,

*Rens Kruining*
+31 6 46 51 86 73 | renskruining.nl

**Comment by jonathanjuursema** [comment]
@regnerus could you provide a status update?

**Comment by jonathanjuursema** [comment]
@regnerus since there has been no status update I'll assume there is no progress on this yet. Peter Wessels (@MrFix93) indicated to be interested in implementing this, so I'll assign the issue to him.
