### ISSUE TITLE
Change committee/event/member links

### ISSUE THREAD

**Issue by opwarmpannenkoek** [saproto/saproto#156]
At the moment all hyperlinks are generated probably on their ID. 
Example: https://saproto.nl/committee/1099
It would be nice if this was https://saproto.nl/committee/pLAN for instance
Same for member IDs and event IDs. Links would be way more informing instead of just 'an ID'.

**Comment by jonathanjuursema** [comment]
Because implementing this (consistently) would take a lot of time, we have decided to reject this feature request. Sorry. :(
