### ISSUE TITLE
Uncapitalized user names

### ISSUE THREAD

**Issue by JRitmeester** [saproto/saproto#1567]
There are a number of people (suspiciously often first names starting with 'j') that don't aren't properly capitalised, and it just looks a bit sad, especially since - IIRC - the capitalisation originates from a UT database that doesn't fix non-capitalised names and these people have no influence in it. It would be pretty to see all names in sign-up lists etc. to be capitalised properly. Maybe easiest to do this during HTML generation? Small non-issue, admittedly, but would be nice to see :)

**Comment by JonaMata** [comment]
There is no real standard for how names capitalised, so this is not feasible for us to implement. The users in question will have to fix their name at either the UT or the Proto board.
