### ISSUE TITLE
Subdomain protube.saproto.nl is necessary

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#161]
This is necessary, because the ease of access for this page enables more members to fill the protube playlist.

**Comment by jonathanjuursema** [comment]
strlen("protube.saproto.nl") == strlen("saproto.nl/protube") ??

**Comment by renskruining** [comment]
substr("protube.saproto.nl",0,3) != substr("saproto.nl/protube",0,3)   !!

Kind regards/vriendelijke groet,

*Rens Kruining*
+31 6 46 51 86 73 | renskruining.nl

On Mon, Sep 12, 2016 at 1:15 PM, Jonathan Juursema <notifications@github.com

**Comment by jonathanjuursema** [comment]
We try to avoid subdomains to keep everything simple. In any modern browser, after a while, you will get the ProTube URL highlighted if you type `pro(tube)`. We won't implement this one.
