### ISSUE TITLE
Better warning for incompatible RFID tags in OmNomCom

### ISSUE THREAD

**Issue by JRitmeester** [saproto/saproto#1623]
I registered my ID card as an RFID for the OmNomCom, but turns out that it cannot be used to pay with, giving the error "Not so hasty" on screen. @JonaMata explained that because it is difficult to distinguish between improperly read RFID tags and RFIDs such as ID cards, which presumably don't work because of their enhanced encryption. If it is at all possible, it would be nice to have a simple distinct error message stating that the card could not be read, preventing people for repeatedly trying to scan their ID card or similar RFIDs. If that isn't possible, it may be nice to have this as a warning in the "Link RFID" menu, stating "ID cards and driver's licenses cannot be used to."

**Comment by Jessseee** [comment]
It turns out it is not that difficult to detect randomized cards as all uids of randomized nfc cards start with `08`. There is now a nice error message when you try to swipe any randomized nfc card or a mobile phone.
