### ISSUE TITLE
Attendee Meter

### ISSUE THREAD

**Issue by jimtolman** [saproto/saproto#166]
As the living embodiment of the quantified self movement, I asked the board of SA Proto if they would be interested in a graphical overview of the amount of attendees at events of SA Proto. They replied with "Yes!" and the _Have You Tried_ suggested that is would be possible.
To measure the involvement of (international) members of SA Proto and to spot trends, **I would suggest to build a nice Attendee Meter for the board.**

**Comment by DennisVinke** [comment]
While the function could be nice to have, this issue does not have enough priority to be implemented in a long time so for the time being we decided to close this issue.
