### ISSUE TITLE
smartXP site doesn't show acurate availability

### ISSUE THREAD

**Issue by Lupus1** [saproto/saproto#1661]
## The SmartXP site doesn't show the availability

On [smartXP.nl](https://www.smartxp.nl/) the availability of smartXP  is always displayed as available even though a lecture is going on.

![afbeelding](https://user-images.githubusercontent.com/36168589/189888572-38822ff8-4d7a-4993-97a6-98694258a1bc.png)

**Comment by Jessseee** [comment]
Fixed!
