### ISSUE TITLE
Change AbScInt to Abscint

### ISSUE THREAD

**Issue by daniepyromanie** [saproto/saproto#1708]
(Ik bedenk me nu dat dit misschien een bestuursfunctie is, right?)

Could AbScInt in the drop down menu of the TIPcie drink request form on the Wiki be changed to Abscint for consistency ? <3
![image](https://user-images.githubusercontent.com/33750931/193647182-e010a57d-19d0-4430-9b7f-436052da7617.png)

**Comment by MaxLiebe** [comment]
Fixed
