### ISSUE TITLE
Withdrawal controller ignores users without bank information

### ISSUE THREAD

**Issue by JonaMata** [saproto/saproto#1772]
Currently the withdrawal generation ignores users with no bank information.

The wanted behaviour would be to show the user that this person exists and to provide an option to add this persons debt to the next withdrawal or to accept the loss and set the users orderlines to paid (maybe a separate paid by association/loss field)

**Comment by Jessseee** [comment]
Where should we aggregate these "paid with loss" orderlines? (for a financial report for example)
