### ISSUE TITLE
Incidential mailinglist for activities

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#179]
Some toolie that lets you add members to an incidential mailinglist (that's used once) so they see 'Dear <name>' in the mail instead of 'Dear member'.

**Comment by jonathanjuursema** [comment]
@xadya, can I implement this as #368, would that cover the use cases?

**Comment by xadya** [comment]
Think so, only thing Dennis wants next to this is that it can be sceduled.

**Comment by jonathanjuursema** [comment]
Clear! I'll close this one as a duplicate of #368, so please subscribe to that issue for updates. :)
