### ISSUE TITLE
Force new members to add utwente account

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#180]
A lot of new members lost their account details, this would be prevented when the have to link their utwente account when making a new account. Will also prevent users making two accounts.

**Comment by thijsdortmann** [comment]
Right now they can also just use password reset, or ask a board member to look up the e-mailaddress they used. I do agree that we should force new members to add their UT account, but we also need to have an override to ensure that people who aren't studying at the UT can also become a member.

**Comment by jonathanjuursema** [comment]
I already discussed this with @xadya and there will be some tools that can be restricted to UT students only (UT address book search for example) and we might also offer the oppurtunity to restrict some e-mail lists to UT students. But there's no way we can check if someone is a UT student without having their UT number, so a forced check is unfeasable. :(

**Comment by thijsdortmann** [comment]
I was thinking of something like a checkbox or a warning that a board member sees when adding a membership to a user. "This user didn't link their UT credentials. Do you still want to make them a member?" The board member can then ask the student to first link their UT credentials, just like we do with addresses and bank accounts.
