### ISSUE TITLE
Forced to click on link when signing up for events.

### ISSUE THREAD

**Issue by OtakuDisease** [saproto/saproto#1813]
Dear HYTTIOAOAC,

For external events sometimes links with a form made by the company is required to be filled in.
So I would like to have a some sort of pop-up or place where people are forced to click on the link or be reminded to click on the link when signing up for an external event.

**Comment by ysbrandB** [comment]
I think it would be nice to make this a more general pop up functionality that cannot be dismissed, for instance when an event has happened that the board gets a popup to fill in how many people attended untill they filled it in, when the new educational system is built the edu gets a popup when a new issue is put on the board until he approves/disapproves it (or the one who should). I think making the pop up system more general for this and add personalised pop ups would be nice.
