### ISSUE TITLE
Optional hidden Queue for Protube

### ISSUE THREAD

**Issue by Sebastiaanjai** [saproto/saproto#1828]
The on-screen protube queue is an awesome feature, thanks for that!
But for some usecases it might be nice to be able to see the entire video instead of having the queue placed on top of the video. 
So... a button! That hides the queue (probably somewhere on the protube admin screen)

**Comment by ysbrandB** [comment]
This issue regards ProTube and therefore should be on the ProTube repo. https://github.com/saproto/ProTube/issues/new.
For now I have copied your issue (https://github.com/saproto/ProTube/issues/71) to there and I will close this one.
