### ISSUE TITLE
Idea for 'having a bad day page'

### ISSUE THREAD

**Issue by rachel323** [saproto/saproto#1831]
Hello, brave soldiers from the Have You Tried Committee. Today I strolled upon a fun webpage on a website that I thought might be interesting to also implement on the proto site.  It is about a webpage shown on the menu bar that reads 'having a bad page' and directs you to a page filled with cute animal pictures. I have added a link and screenshot of the page, 
https://petparty.co/pages/having-a-bad-day
![image](https://user-images.githubusercontent.com/73276849/208669864-86fba0d3-706e-41bd-a6cf-dee4d6315088.png)
Might be fun to add if you have the time and feel like it.
Seasonal greeting,
Rachel

**Comment by robi-wan69** [comment]
Adding to this, I think you should include the song [Have A Nice Day by Bon Jovi](https://www.youtube.com/watch?v=uCg2BoKiuOM).

**Comment by JonaMata** [comment]
Hello, brave chair of the 12th board,

What a nice idea. The easiest way to do this is to create a page using one of the admin tools on the website and to it to the navigation menu using the menuitem admin tool. The great thing about using this method is that you can do it yourself, so you can choose the images you love most. If you like Robin's idea you can also add a link to that song on the page.

Good luck!

On behalf of the Have You Tried Turning It Off And On Again committee,
Jonathan
