### ISSUE TITLE
Some part of site still using wrong Radius endpoint?

### ISSUE THREAD

**Issue by jonathanjuursema** [saproto/saproto#187]
https://sentry.io/saproto/saproto-laravel/issues/160553682/

**Comment by jonathanjuursema** [comment]
I get the feeling that something else is trying to access this endpoint, there's nothing in this repository requesting it. @thijsdortmann: any idea where this endpoint may still be used?

**Comment by thijsdortmann** [comment]
Seems to be @Peeterus dev, as he is still using the old endpoint in his .env.
