### ISSUE TITLE
Liefste Jesse

### ISSUE THREAD

**Issue by rachel323** [saproto/saproto#1905]
Allerliefste leden van de have you tried turning it off and on again committee,

Het is maandagmiddag, wat betekent dat het bier weer rijkelijk stroomt in onze lievelings borrel ruimte die de universiteit Twente rijk is. Maar op deze mooie maandagmiddag liggen mijn gedachtes ver voorbij de in overvloed aanwezige fusten goudkleurig elixir... Want wat mij toch bezig houdt wanneer ik mijn lippen aan een fris knapperig zwetend Grolsch glas zet is mijn liefde voor de beheer commissie van onze mooie vereniging. Deze groep van toegewijde passievolle intellectuele individuen toont mij een voorbeeld van hoe het is om onbaatzuchtig samen te werken en een project naar een hoger niveau te tillen.

Hou van jullie, excuus dat het Nederlands is en dat het een kut issue is maar ik moest dit even van mn hart <3

**Comment by Wilkuu-2** [comment]
### Drunk texting? 
Maar dan op ***GitHub***?
