### ISSUE TITLE
API of ChatGPT build into the promotion text of the website

### ISSUE THREAD

**Issue by LouisVanMaurik** [saproto/saproto#1930]
I know, I know, my board year is over. But you know which skill I learned in my board year what was completely useless? WRITING PROMOTION TEXTS. You need to write them in a way where you need to excite someone. With some sort of happy tone, which feels soooooo forced. 

The future is now old man. You know who can also write such a text? Without spelling mistakes, and much better? Our new overlord: ChatGPT. This magical AI has already some experience, because it wrote the last few promotion texts already, like Schrala, Staf Drink, Lunch lecture, etc.

So what would be more a CreaTe thing, then implementing it into the website. Is it necesarry? No, definitely not. Is beheer too busy fot his bs? Maybe. Is it really stupid to do all this work? Definitely yes. But yeah, still cool if it exists haha. So maybe a fun project which will help future boards.

Doei

**Comment by MaxLiebe** [comment]
Thank you for considering the integration of ChatGPT's API into our website. We appreciate your interest and the potential benefits it could bring. After careful consideration, however, we have decided not to proceed with the incorporation of ChatGPT's API at this time.

Our decision is based on various factors, including our current technical requirements, priorities, and resources. We have evaluated several options and determined that integrating the API does not align with our immediate goals.

We genuinely value your interest and appreciate your understanding in this matter. Should there be any other ways in which we can assist you or alternative solutions we can explore together, please don't hesitate to let us know. We are open to discussing other possibilities that may better suit your needs.

Thank you once again for considering our services, and we wish you the best of luck with your project.
