### ISSUE TITLE
Dinnerform page updates

### ISSUE THREAD

**Issue by BenLigthart** [saproto/saproto#1962]
Dear beheer,

I cannot believe it, this will probably be my last issue to you as a treasurer.. it hurts my feelings, but we did have a great time together. I will cherish our issue-based communication for years to come. This quote will be about saying goodbye.

"It's time to say goodbye, but I think goodbyes are sad and I'd much rather say hello. Hello to a new adventure."

Before I say goodbye I would like to suggest some updates for the dinnerform page:
- Make the process dinnerform button only available to the treasurer. This year it happened that people who ordered the dinner thought they had to process the form, which lead to me not being able to change any mistakes in the dinnerforms. 
- Could you add the date of the dinnerform somewhere in the orderlist? Right now you can see the date in the big overview but if you click 'view orders' there is no date. It is easy for the treasurer to have that available for double-checking :)

That was it. Thank you for everything, I see you in another life. 

Cheers
Your penny-for-a-while,
Poem writer,
Issue expert,
Ben

**Comment by ysbrandB** [comment]
Dear Ben,

Thank you for your heartfelt message, and while it's saddening to hear that this will be your last issue as treasurer, I truly appreciate the great times we've had working together. Your dedication and expertise have made a significant impact on our organization, and I'll cherish our issue-based communication for years to come.

The quote you shared is both poignant and optimistic, and it perfectly captures the essence of bidding farewell to one chapter and welcoming a new adventure in life.

Your dedication to detail and your commitment to enhancing our processes have been exemplary, and your contributions will have a lasting positive impact on our organization. We're grateful for everything you've done and wish you the best in all your future endeavours.

As you move on to new horizons, please know that you'll always be part of our GitHub.
Till a future life!

Cheers,

Your one-line fixer,
Beheerder for a while,
General website developer,

Ysbrand
