### ISSUE TITLE
OmNomCom easy running total view.

### ISSUE THREAD

**Issue by Habenga** [saproto/saproto#198]
There are some members who have asked wether it would be possible to see/be informed how much they have spend in a more passive way than having to go check the site and look at order history. (One of the suggestions was an email every 10euros or so)
We think it would be better to have a more passive view, by for instance  adding the members OmNomCom expenditure (preferably without activities) of the current month to the log-out screen (the one with omnomnomnom sound) of the on the OmNomCom. Or by having it displayed on the eventual login screen. 
Some members might not like seeing this so maybe an option to check on the account management page would be nice.

**Comment by jurvangeel** [comment]
Let OmNomConclave about this some time

**Comment by jonathanjuursema** [comment]
This is indeed something for the board/OmNomCom since I can also imagine the OmNomCom not wanting this (reducing sales) or members not wanting this (not wanting to be remembered everytime).

**Comment by jonathanjuursema** [comment]
@DennisVinke @jurvangeel any progress on this?

**Comment by jurvangeel** [comment]
Ja, it ain't gonna happen

**Comment by jonathanjuursema** [comment]
Okay, I'll close this issue!
