### ISSUE TITLE
Button to stop all current members in a committee

### ISSUE THREAD

**Issue by EmmaBurema** [saproto/saproto#1995]
When entering a new committee, you have to stop all members of the current committee manually, which is not that handy. This is btw not really pressing but might be handy for the next board.

**Comment by ysbrandB** [comment]
This button already exists, it is incorrectly labeled though. The button says "delete" but in my opinion should be labeled "end edition".
It is here: 
![image](https://github.com/saproto/saproto/assets/72889753/eb0b7ed0-c1ce-45d8-b388-2fb5ea4ed838)
