### ISSUE TITLE
Functie aan users-page die kan filteren op primair/secundair/creaTe/ITech (universiteit gerelateerd)

### ISSUE THREAD

**Issue by EmmaBurema** [saproto/saproto#2009]
Is er een mogelijkheid dat er een functie komt dat ik ook kan filteren op create en I-Tech en op primair en secondair lid op de user page?
Het hoeft niet gezien te worden in het overview maar hierop filteren zou echt al heel erg chill zijn.

**Comment by ysbrandB** [comment]
English please :), and why do you want to filter on this? Most usecases I can come up with for this are already covered by other functions in the website.

**Comment by EmmaBurema** [comment]
Yes, delete it, it is already possible!
