### ISSUE TITLE
Vacature pagina/Membercard

### ISSUE THREAD

**Issue by jurvangeel** [saproto/saproto#203]
Lieve Thijs,

Naast dat ik ontzettend veel van je hou, en te moe ben om in het engels te typen, heb ik ook vandaag nog een issue ;-)
Zou het mogelijk zijn om 2 pagina's toe te voegen; een voor een vacature pagina(parrent career), en een voor de membercards (parrent memeber).
Beide met ongeveer dezelfde layout als de huidige career page.
Hoe de backend eruit ziet laat ik volledig over aan je geweldige fantasie.

Kusjes

Jur

**Comment by jonathanjuursema** [comment]
@jurvangeel could you please repeat your issue in English so our English speaking committee members can also parttake in the discussion?

**Comment by jurvangeel** [comment]
Dear Thijs,

Besides that I very much love you, and I am too tired to type in English, I also have an issue today;-)
Would it be possible to add two pages; a vacancy for a page (parrent career), and one for member cards (parrent memeber).
Both with approximately the same layout as the current career page.
How backend looks like I leave entirely to your great imagination.

Kisses

jur
