### ISSUE TITLE
Allergies in OmNomCom

### ISSUE THREAD

**Issue by EmmaBurema** [saproto/saproto#2041]
In the omnomcom the buyer can't see which product contains certain allergies, this can lead to people having allergic reactions fro the omnomcom. To prevent this we could add allergic symbols in the corner of products. If you have an another idea that is ofcourse also up to debate.

**Comment by Jessseee** [comment]
This is a bad idea for the simple reason that if the information is incorrectly presented in the OmNomCom Proto is liable if someone has an allergic reaction to food bought from the OmNomCom. By simply not providing the information in the OmNomCom and making people check the product packaging itself Proto keep plausible deniability.
