### ISSUE TITLE
Quotes in Protube

### ISSUE THREAD

**Issue by EmmaBurema** [saproto/saproto#2044]
When protube is showing pictures, it would be very nice to also have quotes on the screen. The quotes would be perfect in the left corner. But this is an option, if you think this is to much work you can of course just reject this idea...

**Comment by Jessseee** [comment]
I do not think this is a good idea, as the quotes are often in Dutch and less than savory. Also see my rejection of #1065.

**Comment by EmmaBurema** [comment]
Also fine, we just thought it might be fun and add some extra value to adding quotes to the quote corner....

**Comment by ysbrandB** [comment]
> I do not think this is a good idea, as the quotes are often in Dutch and less than savory. Also see my rejection of #1065.

Yeah I agree, the quotes are too immature most of the time. You would then either need to moderate them or need to build something that the board can choose which quotes get featured.
