### ISSUE TITLE
Protube not random enough

### ISSUE THREAD

**Issue by EmmaBurema** [saproto/saproto#2049]
On protube, some pictures from certain albums get the preference of the algorithms. I don't know how or why but it's just not really random. I suspect it has a preference of more "recent" photos in albums....

**Comment by ysbrandB** [comment]
Yeah... it is not entirely random, the entire point was that people did not like pictures from 2012 where no one knows anyone anymore showing up just as much as recent photos.  The division is as follows:
![image](https://github.com/saproto/saproto/assets/72889753/0b62c4ae-94c5-46d9-87ed-d7cc8162b562)
