### ISSUE TITLE
"More activities" button underneath upcoming activities

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#205]
"More activities" button underneath upcoming activities on the homepage, so it's easier to find the calendar

**Comment by thijsdortmann** [comment]
Refs #88

**Comment by opwarmpannenkoek** [comment]
Or just make 'Upcoming activities' a button. Seems more logical

**Comment by jonathanjuursema** [comment]
This all depends on the final layout for the homepage, and the homepage is a project @regnerus is working on! :)

**Comment by jonathanjuursema** [comment]
Bump for @regnerus

**Comment by regnerus** [comment]
This should also be discussed with @Janwillemtv he made the new design of the homepage.
