### ISSUE TITLE
Protography watermarks

### ISSUE THREAD

**Issue by jorriborri** [saproto/saproto#2056]
Hey hey, idk if it's possible or achievable but it's quite a big hassle to make watermarks for every member that makes pictures for the website so I was wondering if we could make it possible to add a function that automatically places a watermark over pictures on the website when a user uploads it (I would totally understand if this isnt gonna work hahah)

**Comment by Jessseee** [comment]
Yes, this would be great! However, I will be closing this issue because it was already requested in #991.
