### ISSUE TITLE
Helper discount dinner form 113

### ISSUE THREAD

**Issue by DutchComic** [saproto/saproto#2063]
The helper discount from dinnerform 113 did not go thourgh. There are multiple people selected as helper, yet each of them has the full price as discounted price. There's also €0.00 in the top bar for helper discount
![image](https://github.com/saproto/saproto/assets/71320938/13d09d10-36de-4173-ba85-fb9b19f8be5a)

**Comment by ysbrandB** [comment]
Did you input an amount to take of the amount when creating the dinner form? It seems to still be on 0. https://www.proto.utwente.nl/dinnerform/edit/113
