### ISSUE TITLE
Download photo album button

### ISSUE THREAD

**Issue by jorriborri** [saproto/saproto#2068]
It would be great if there would be an option to download a whole photo album so it is easy to share a full album with for instance another association that might want to upload them.

**Comment by Jessseee** [comment]
Given that many of the photo albums are actually private and should not be shared with others, I do not think this is a good idea.

**Comment by ysbrandB** [comment]
The question I am asking myself is why, I think Jesses comment is valid but can be negated by only making the button accessible when the album and photos are public. But at the moment I believe it is easier to just ask the protographer for the photos (or in the drive?). In the future you might want to use the automatic watermark from the site but I do not know if any other association would like the photos with our logo on it. Herefore I do not really see the use case.
