### ISSUE TITLE
Events from last year are displayed in the Later category

### ISSUE THREAD

**Issue by Wilkuu-2** [saproto/saproto#2095]
This event from last year somehow ended up in the Later category of events for this year. 
![image](https://github.com/saproto/saproto/assets/94912220/97120c7e-5637-4d42-845c-7b7255e5eeff)
You can't sign up for it, but it's wierd that it's here.

**Comment by ysbrandB** [comment]
Not a bug, they moved the event to the future for some reason. Might be nice to disable editing of the date of an event if it is in the past though. Will discuss next meeting. 
![image](https://github.com/saproto/saproto/assets/72889753/ba779d2a-4925-4ee6-9095-99b99b2f2de1)
