### ISSUE TITLE
CaptCha is Broken

### ISSUE THREAD

**Issue by KaDayKa** [saproto/saproto#214]
When making a new account Captcha gives the error:

ERROR for site owner:
Invalid domain for site key

We can't sign in new members if this stays broken.

**Comment by jonathanjuursema** [comment]
The issues seems to be that proto.utwente.nl was not yet whitelisted for our recaptcha key. :')

I added the domain but it can take up to 30 minutes for it to take effect. I'll keep this ticket open until I see that it works again.
