### ISSUE TITLE
The homepage says there are no events coming up (at all) while there are only no events coming up this month

### ISSUE THREAD

**Issue by ysbrandB** [saproto/saproto#2179]
![image](https://github.com/user-attachments/assets/2b1f2e4a-aa47-46ab-8185-06c02055e25a)
See the image above, there are events, just not in the coming month. I think this is confusing and should be changed to either show the next n events or let the text reflect that there are no events in the coming month.

**Comment by MaxLiebe** [comment]
I mean, it's not very _soon_ if it's in later than a month
