### ISSUE TITLE
Generating QR codes from shortlinks

### ISSUE THREAD

**Issue by Jessseee** [saproto/saproto#2196]
Apparently, people within the association are using paid third-party click-through services to generate QR codes. QR codes are a relatively simple and well-defined data format, which we should easily be able to generate ourselves. I suggest we add this feature to the shortlink service so any shortlink can easily be shared as a QR code.

**Comment by MaxLiebe** [comment]
Disagree. Not needed if you know how to use QR codes capably (sorry Anthony). There are enough sites can generate raw QR codes.

**Comment by Jessseee** [comment]
I agree that it is not necessary, but it would be very convenient and avoid people that are less "capable in using QR codes" from usin third-party applications that tracks clicks and breaks the QR code after a certain time.

**Comment by ysbrandB** [comment]
> I agree that it is not totally necessary, but it would be very convenient and avoid people that do not "know how to use QR codes capably" from using third-party applications that tracks clicks and breaks the QR code after a certain time.

I agree that it would be a nice addition. also shouldnt be that much work since we already have the QR code package for generating the omnomcom qr codes.
