### ISSUE TITLE
achievement system

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#229]
not HYTTIOAOAc only, also board ;-)

**Comment by jonathanjuursema** [comment]
The board cannot see the achievement option in the navigation.

**Comment by xadya** [comment]
Also: possibility to add more than one person at a time, possibility to remove people and to see who got the achievement

**Comment by xadya** [comment]
and maybe, but is more design: have the colors differently, because it doesn't look like epic is better than common

**Comment by renskruining** [comment]
As a small addition to the design: the colors don't make much sense at the moment. nothing indicates what tier is purple, or grey or black, etc.

The grey also look like they are supposed to be hidden/disabled.
I think a decent way to fix this is to have the text a consistent color (black or the standard color the website uses), then if you continue the outline give that a color with the tier in the upper-left or -right inner corner. This would give the colors more meaning/would be a better indication of tiers.

Tiers by themselves don't say much, though. a percentage of people that have achieved the certain thing would make the tier system way more meaningful.

**Comment by jonathanjuursema** [comment]
Topic changed, original issue is fixed. Please continue discussion in #242.
