### ISSUE TITLE
Closing Activities

### ISSUE THREAD

**Issue by jurvangeel** [saproto/saproto#235]
This could be double, but I couldn't find the old ticket

The Close activities page, under Financial, isn't working properly.
I'm not able to view the participants nor the name of the Activity.
Furthermore I have no Idea if the rest of the backend works

**Comment by jurvangeel** [comment]
SUPERHIGH PRIORITY

**Comment by jurvangeel** [comment]
Really Really want ;-)

**Comment by jurvangeel** [comment]
Thanks Darlin

**Comment by jonathanjuursema** [comment]
Where's my printer?
