### ISSUE TITLE
Achievements that should be automatic

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#241]
Big spender = you had the max money subtracted for 1 month (=€250)
I am bread = more than 100 tosti bought
gotta catch ‘m all = at least 10 different committees
Fristimember = you're no CreaTer and you bought a Fristi
Old fart = more than 5 years a member
It’s always 4 o’clock somewhere = a month where more than 25% of OmNomCom purchases is beer
Big kid = month where  more than 25% of purchases is from the kid friendly fridge
Cry baby = bought 15 surprise eggs or more
True German = more than 100 Weizen in beer history
Hangry = bought 5 snickers or more (all time)
Achievement beast = 10 achievements or more
You dandy = you bought 3 different types of merchandise
You’re special = more than 15% is special beer (all time)

**Comment by Peeterus** [comment]
Busy implementing, but got a remark:
True German seems somewhat impossible. Ran a check on the database and the maximum beers in history of one person is 23. Should the required amount for the achievement be lowered?

**Comment by xadya** [comment]
Good one... Maybe 20 weizen?

**Comment by Peeterus** [comment]
only one is not done yet:
Big kid = month where more than 25% of purchases is from the kid friendly fridge
for this I wait till a proper category is implemented by the omnomcom committee.
