### ISSUE TITLE
General Achievements Improvements

### ISSUE THREAD

**Issue by jonathanjuursema** [saproto/saproto#242]
This issue should keep track of general improvements to the achievement system.

**Comment by jonathanjuursema** [comment]
@renskruining in #229:
As a small addition to the design: the colors don't make much sense at the moment. nothing indicates what tier is purple, or grey or black, etc.

The grey also look like they are supposed to be hidden/disabled.
I think a decent way to fix this is to have the text a consistent color (black or the standard color the website uses), then if you continue the outline give that a color with the tier in the upper-left or -right inner corner. This would give the colors more meaning/would be a better indication of tiers.

Tiers by themselves don't say much, though. a percentage of people that have achieved the certain thing would make the tier system way more meaningful.

**Comment by jonathanjuursema** [comment]
I think this ticket is as good as done @Peeterus @Janwillemtv ? If so, could you close it?

**Comment by opwarmpannenkoek** [comment]
Styling issues again 
![screenshot_20161209-154422](https://cloud.githubusercontent.com/assets/18185955/21052714/97d76734-be26-11e6-99b6-d2aa5feaabc5.png)

**Comment by jonathanjuursema** [comment]
@opwarmpannenkoek can you please open a seperate issue for mobile styling issues?
