### ISSUE TITLE
Problem with calendar

### ISSUE THREAD

**Issue by laurier1122** [saproto/saproto#244]
Als ik een evenement aanmaak op de proto site verschijnt deze niet in de kalender. En los er in zetten werkt ook niet meer want ik kan de iCal niet linken met mijn google account.
![screen1](https://cloud.githubusercontent.com/assets/22469477/19437287/0120fb28-9475-11e6-8f5b-d88855ea0aee.JPG)

**Comment by laurier1122** [comment]
ok the screenshot is probably useless

**Comment by jonathanjuursema** [comment]
If you didn't specifically connect the new calendar, this is right. The website only syncs with the new calendar, the old one is completely seperate and doesn't sync anything. You should at least be able to link the calendar to your Google account by copying the calendar URL in the pop-up window (not the hyperlink) into the "Add calendar by URL" dialog in Google Calendar. Can you confirm?

**Comment by jonathanjuursema** [comment]
Reminder @laurier1122

**Comment by jonathanjuursema** [comment]
Closed this issue since there was no response and everything seems to work fine. Please reopen the issue with further information if there is still a problem!
