### ISSUE TITLE
Weekly newsletter not delivered

### ISSUE THREAD

**Issue by laurier1122** [saproto/saproto#245]
I got 30 mails with a delivery failure. I checked the adresses and as far as I know they are all valid, because i do not get a delivery failure when I mail them with my hotmail account.

**Comment by DennisVinke** [comment]
Where the letters sent to a @hotmail address?

**Comment by jonathanjuursema** [comment]
In the delivery failure there should be an error message. Can you forward some of them to me so I can troubleshoot the issue?

**Comment by jonathanjuursema** [comment]
Reminder @laurier1122

**Comment by jonathanjuursema** [comment]
I believe this was resolved and the e-mail addresses did in fact not exist. Please re-open the issue is this is not the case. :)
