### ISSUE TITLE
bestuuur.saproto.nl or alternative replacement

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#247]
Hey lovely programming bunch of dearies,

I have heard of the ever elusive page for old-board members that sent a sound message of love to the board at the press of a button.

Could this page make a comeback or be brought to our attention?

Thank you very much <3

**Comment by jonathanjuursema** [comment]
@renskruining if you gave an actual good description of your feature request also the newer members of our committee might be able to help you.

**Comment by thijsdortmann** [comment]
Herbert now has an HTTP endpoint for playing soundboard sounds:
`env('HERBERT_SERVER') . "/soundboard?secret=" . env('HERBERT_SECRET') . "&sound=bestuuur"`

**Comment by renskruining** [comment]
@jonathanjuursema (and everyone else that actually reads this): The page I am looking for is a simple website that the old boardmembers can access, to activate the "Bestuuuuur" sound in the soundboard. This was working last year and is missing now.

The page should have some way of verification/login so only old boardmembers can access it. It should be clear what to click to activate the sound. That is actually all the website needs.

Other optionally features might include a fancy layout, a big red button, a counter how many times it has been pressed, a timeout-function (so the board doesn't get spammed to death), etc.

Hopefully the task at hand became more clear now. If you have any other questions, feel free to approach me IRL (or ask a old-boardmember that actually used the website (Jonathan for example))

**Comment by jonathanjuursema** [comment]
@DennisVinke can you discuss with the board if you want this feature in the website?

**Comment by jonathanjuursema** [comment]
I've heard nothing from the board, so I'll close this issue. To re-open this issue, please contact the board.
