### ISSUE TITLE
Touchscreen is not registering input properly.

### ISSUE THREAD

**Issue by MrFix93** [saproto/saproto#248]
The keyboard is slow, not accurate and sometimes it produces random touches. For the password, when you can't see what you're typing, it is really a problem.

**Comment by jonathanjuursema** [comment]
This seems to be an issue with the touchscreen. :(

**Comment by jonathanjuursema** [comment]
@DennisVinke I have the feeling that this isn't so much a problem in the past few weeks (at least, I haven't heard about it). Could you confirm whether it is still an issue or not? If it is still an issue, we will start looking for a new touchscreen.

**Comment by MrFix93** [comment]
A new member tried to couple her card and failed so many times that this is still an issue.

**Comment by jonathanjuursema** [comment]
The issue is acknowledged, but right now we're not sure if there's funds to actually buy a new touch screen. We'll keep looking, but I don't expect a swift replacement. Sorry. :(

**Comment by jonathanjuursema** [comment]
We're putting this issue on hold untill there is money available to buy a new touchscreen. This money needs to be freed by the treasurer, this is not something for the HYTTIOAOAc budget. If there is budget available, we can start selecting a new screen.

**Comment by jonathanjuursema** [comment]
We have discussed this with OmNomCom/board, and the general consensus was that there was no money available, and there probably also won't be. To really solve the problem we would need to buy a more expensive monitor, which is not proportional to the usage. Buying a similarly priced monitor will only solve the problem for a few months. Sorry. :(
