### ISSUE TITLE
Assisting committeemember with live / hotmail dont get a mail

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#249]
when 'activity needs your help' mail in sent, the people with hotmail / live never get it and thus will almost never help

**Comment by jonathanjuursema** [comment]
There's two options. Either the e-mail is rejected by Hotmail, or the e-mail is flagged as spam by Hotmail.

If the e-mail is rejected by Hotmail, either we or the board should have received a 'Message rejected' e-mail. If this is the case, please forward it to me so I can troubleshoot the issue.

If the e-mail is marked as spam, I need the e-mail headers from Hotmail so I can troubleshoot the issue. Please forward them to me. [Instructions.](https://www.lifewire.com/display-header-lines-outlook-1173510)

Alternatively, the e-mail server is trying to send the e-mail, but has not yet given up. If you can send me some of the recipients via a private channel I can see if there's e-mails hanging for these recipients and why.

**Comment by jonathanjuursema** [comment]
I've digged deeper in the e-mail you provided and as far as our server knows the e-mail has been successfully delivered to Hotmail (the Hotmail mail server acknowledged receipt). I've also performed a more extensive check in our sending IP and Microsoft is not blacklisting them. I'll check with the recipient to see if I can find out more.

**Comment by jonathanjuursema** [comment]
This issue has something to do with strange behavior of the Hotmail mail server, that sometimes says it accepted an e-mail but then doesn't deliver it. We have signed up for both e-mail monitoring tools from Microsoft and Google to be able to further investigate the issue.
