### ISSUE TITLE
Calender "This month" shows next month

### ISSUE THREAD

**Issue by opwarmpannenkoek** [saproto/saproto#250]
This month? That's next month!
![image](https://cloud.githubusercontent.com/assets/18185955/19606726/a6f8a95e-97c4-11e6-96b5-c87d6f9e2bb0.png)

**Comment by jonathanjuursema** [comment]
"This month" in this context means "within the next 30 days". I could change it on the page, but it would look less slick. Let's have a vote! Using the +smiley button in the top right of this post, please leave a 👍 to change the text, and a 👎  to keep the text. :)

**Comment by opwarmpannenkoek** [comment]
If it's within 30 days, I should have seen the things of 14 november as well? 

Apart from that, I find it hard to get familiar with this interface. I would rather have it like this:
Recently - Soon - Later
I don't see why a 'This month' column is relevant when the 'Later' column is chronologically ordered anyway. 
And; that way you can easily reflect on recent events without having to go through the entire archive of that year. And maybe even link photo albums to past events then? 

Still, here's a tip of the fedora  
![image](https://media.giphy.com/media/zHCMd7DteVM6k/giphy.gif)

**Comment by jonathanjuursema** [comment]
For linking photo albums to events you can follow #246 . :)

**Comment by jonathanjuursema** [comment]
@DennisVinke could you let me know what the board thinks about the proposed devision in recent - soon - later? I haven't had much feedback here, so I'll leave the decision on whether to restructure to you. If the board has reached a conclusion, please let it know!

**Comment by jonathanjuursema** [comment]
I haven't heard any feedback so I'm closing this issue. If there's still a change desirable, @DennisVinke, please re-open the issue!
