### ISSUE TITLE
Addition Withdrawltoolie

### ISSUE THREAD

**Issue by jurvangeel** [saproto/saproto#259]
Beheeeeeer!!!!

During my preparation for the first Audit I noticed that the New withdrawal tool misses an essential feature.
Could you make it so, that after closing a withdrawal a text field appears (rather permanent) stating the summation off all orders in that withdrawal, ordered by account. This enables me to submit the withdrawal into the Bookkeeping.

E.G.

if a order consitst of;
Jur        Sailingtrip 65
Jur        Snickers    1
Petra    Snickers     1
Hestia  Snickers     1
Hestia Take away   7

the result would be;
account              amount
4040 (sailingtrip) 65
3600 (OmNomCom) 3
1555 (take Away) 7

**Comment by jonathanjuursema** [comment]
This is relatively easy to implement. Can you let me know if I need to make this a high-priority issue?

**Comment by jurvangeel** [comment]
yes, Ultra high if possible,

I'm a little stressed out about it to be honest

**Comment by jonathanjuursema** [comment]
I'll try to get it done by Thursday, unless @thijsdortmann can free some time earlier than that.

**Comment by thijsdortmann** [comment]
There you go :) You can view accounts for withdrawals by clicking on accounts in the withdrawal overview.
