### ISSUE TITLE
The I'll help button doesn't work properly

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#262]
![image](https://cloud.githubusercontent.com/assets/8876164/20003748/75a7ec60-a288-11e6-853f-eece9842b481.png)

In the picture above 1 person was needed, but 5 people could help. And Dennis could help trice. This should be limited to the 1 person needed

**Comment by xadya** [comment]
Also I  cannot remove people, because they do not exist in the database 

![image](https://cloud.githubusercontent.com/assets/8876164/20003797/ae993204-a288-11e6-8d14-e28e860c3515.png)

**Comment by DennisVinke** [comment]
And I can still sign up :) 
![capture](https://cloud.githubusercontent.com/assets/9927347/20003827/d7239e12-a288-11e6-8c20-3bf9cff1b2bc.PNG)

**Comment by xadya** [comment]
![image](https://cloud.githubusercontent.com/assets/8876164/20003903/50c20682-a289-11e6-89b5-94ead62c3fde.png)

**Comment by jonathanjuursema** [comment]
I already know where the problem is, but I don't have time to fix it right now. No more info is needed. :)
