### ISSUE TITLE
card printer doesn't work

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#276]
when i press 'print card' there is no card printed and the printer says 'ready'. The database does change the 'first card' to '23-11-2016'

![image](https://cloud.githubusercontent.com/assets/8876164/20557937/0402a6aa-b16e-11e6-8e38-53af33b047a5.png)

**Comment by thijsdortmann** [comment]
If @jonathanjuursema doesn't have time to look at this issue today, I will look at it tonight before / during / after the Lasercut Workshop.
