### ISSUE TITLE
Custom OmNomCom for Alfred

### ISSUE THREAD

**Issue by jonathanjuursema** [saproto/saproto#28]

**Comment by thijsdortmann** [comment]
Alfred also really liked the idea of just having a regular Omnomcom screen, like the Pilscie, with a card reader after seeing the new Omnomcom.

**Comment by renskruining** [comment]
Something administrative: Alfred needs to be able to ask B.J. Pals to make an invoice for Proto. Therefore Alfred should be able to see what Proto owes him at any certain moment. That in combination with being able to set periods as paid, or, being able to get amount of money per period (where it isn't necessary to set orderlines as paid for alfred)
