### ISSUE TITLE
Styling issue 

### ISSUE THREAD

**Issue by robi-wan69** [saproto/saproto#280]
![screenshot_20161202-131139](https://cloud.githubusercontent.com/assets/18185955/20833696/41d17590-b891-11e6-9d5b-93ed94fcc8bc.png)
Hij is shtuk

**Comment by jonathanjuursema** [comment]
@regnerus any reason why fixing this is taking so long? Otherwise I'll reassign the issue to myself to fix it somewhere in the next 2 weeks.
