### ISSUE TITLE
Order of photo albums on the site is no longer based on date uploaded

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#288]
_What page or functionality is this issue about?_ homepage

_What were you trying to do?_ look at photos

_What did you expect would happen?_ to have camp group first, geoguessr second, murder dinner third etc.

_What did happen instead?_ first geoguessr, camp group, camp. But the order does change every half an hour

_Where there any error or confirmation messages?_ NOPE

**Comment by thijsdortmann** [comment]
Please keep in mind that the sorting for everything uploaded before we moved from Picasa to Flickr isn't right and won't be right, as those albums all have the date on which we moved to Flickr as their `date_create`.

**Comment by jonathanjuursema** [comment]
Maybe we may be able to have improved date sorting as soon as we implemented some EXIF data extraction, which can also include stuff like date shot?

**Comment by thijsdortmann** [comment]
I tried implementing that, but sadly the Flickr API doesn't seem to provide any EXIF data... I'll look into another way to do that later on.

**Comment by jonathanjuursema** [comment]
Made a follow up ticket for these improvements. #294
