### ISSUE TITLE
Tosti is Done SMS

### ISSUE THREAD

**Issue by TomOnderwater** [saproto/saproto#290]
Okay, here is an idea:

If someone buys a tosti they end up on a constantly refreshing list called recentTosti's (or something like that) then they probably leave the protopolis and forget all about their tosti. (dûh) Let's say the board sees this tosti and nobody in proto knows who's tosti it is. What can you do?

Well, the board can press a button which will send an SMS notification to all people who have bought a tosti in the past 10 minutes. thus reminding the person who has bought the tosti that his/her tosti is ready to be nommed.

Lemme know what you think

:) Tom

**Comment by jonathanjuursema** [comment]
By the way, we don't have any SMS functionality (or WhatsApp or whatever) yet. SMS costs money. So when we implement this it will probably be by e-mail unless we get budget to send SMS's. :)

**Comment by TomOnderwater** [comment]
ook goed, maar kan het niet met een whatsapp API?

*Tom Onderwater*

*Student Creative Technology | Pre-Master Computer Science*

*t.c.onderwater@gmail.com <t.c.onderwater@gmail.com>*
*+31 6 53 16 11 47*

On Wed, Dec 7, 2016 at 12:42 PM, Jonathan Juursema <notifications@github.com

**Comment by jonathanjuursema** [comment]
We have looked into WhatsApp, but it unfortunately doesn't have an oficially documented API. All we have to go on are community projects, and even then WhatsApp is not built to be accessed programmatically. The earlier project we had was hacky and far from stable. Having said that, WhatsApp integration is something we would like and which we will undoubtedly try again sometime.

**Comment by thijsdortmann** [comment]
Maybe we can implement this as a push-notification in the upcoming Proto App :)

**Comment by DennisVinke** [comment]
First want to have a good working solution from JayWay before I will greenlight this.

**Comment by DennisVinke** [comment]
See https://github.com/saproto/saproto/issues/290#issuecomment-304698897
