### ISSUE TITLE
Omnomcom manual menu layout 

### ISSUE THREAD

**Issue by Habenga** [saproto/saproto#296]
_What page or functionality is this issue about?_
Omnomcom Frontend display feature request

_What feature do you want to request_
Can functionality be added to manually adjust the layout of the omnomcom interface?

We (the Omnomcom) want to be able to change the order in which product appear in the onmoncom, This will allow us to group product on a page, like putting tosti and vlamtosti and cheese sandwich or fristi and chocomilk next to each other. 
I don't think this can automated in a meaning full way (for all the interesting groupings we might think off) so some kind of manual interface would be good.

My simple suggestion would be to add a field to products that, when filled, overrules the standard sort methode used for the omnomcom screen layout. (Other options may be easier or more workable)

**Comment by jonathanjuursema** [comment]
This can be implemented in much the same way as company or page sort I think.
