### ISSUE TITLE
CoffeeCam

### ISSUE THREAD

**Issue by TomOnderwater** [saproto/saproto#297]
Point of Jaway, He has to make a coffeecam

**Comment by jonathanjuursema** [comment]
@Janwillemtv is this a project that you will take on? 
@TomOnderwater, do you have an idea where we'll get the budget for a webcam from?

**Comment by thijsdortmann** [comment]
Can't we put an el-cheapo scale underneath the coffee machine? And generate a nice readout for the SmartXP screens?

**Comment by TomOnderwater** [comment]
Hee, dat is helemaal geen slecht idee!

Op di 24 jan. 2017 om 21:38 schreef Thijs Dortmann <notifications@github.com

**Comment by jonathanjuursema** [comment]
The deadline for next week is only for the implementation plan, next week we'll discuss the progress. :)

**Comment by Janwillemtv** [comment]
Begin next study year - attach sensors to arduino and read them out\
week later - make a frame for the sensor for under coffee machine
week later - log data of coffee machine
week later - review data and make algorithm
week later - implement prototype

**Comment by Janwillemtv** [comment]
Current status - Ina122P amplifiers used for reading out 50kg loadcells
A accurate gain needs to be found, different gain resistors are being tested.
When a good gain is found the loadcells can be read out correctly.
After this the cells can be placed under the coffee machine.

**Comment by jonathanjuursema** [comment]
@Janwillemtv it has been a month since the last update, could you provide a new one?

**Comment by Janwillemtv** [comment]
after a lot of testing with different gains the load cells don't appear to work. I have to take them to a oscilloscope to see if they even sense something. If not we have to come up with another method.

**Comment by Janwillemtv** [comment]
I have bought two cheap scales from the actoin. The strain gauges were able to be read out using the opamps that were already purchased. I was already able to make a small script that detects of the pot of coffee is present on the scale. Now i am in the process of soldering all the connections of the two scales to ensure reliable readouts. 
The next step would be logging de data of a days use of the coffee machine for simulation purpose. This data then can be used to create a suitable algorithm.

**Comment by jonathanjuursema** [comment]
Can you also give a realistic timeline?

**Comment by jonathanjuursema** [comment]
@Janwillemtv bump.

**Comment by Janwillemtv** [comment]
I will post the timeline when the new module starts, then i have time to continue with the project

**Comment by Janwillemtv** [comment]
update: made a prototype during the holidays on my coffee maker at home. I will fit an improved version to the coffee maker at proto before or during the hyttioaoa evening

**Comment by jonathanjuursema** [comment]
The prototype has been demoed during a committee evening.

@Janwillemtv could you upload the code to GitHub and publish API documentation before next week? If you need another repo for it, let me know. You can also upload it to the existing [kaku](https://github.com/saproto/kaku) repo.

**Comment by Janwillemtv** [comment]
Ill upload the new code, could either @jonathanjuursema or @thijsdortmann facilitate a network connection near the coffeemachine so we can place the coffeetracker 9000.

**Comment by jonathanjuursema** [comment]
As everything is nearly done I'll close this issue! We'll just need to sort out some final networking challenges, but the actual project is finally complete!
