### ISSUE TITLE
Legendary achievement has wrong color

### ISSUE THREAD

**Issue by Peeterus** [saproto/saproto#299]
Legendary tier achievements are colored light blue instead of Proto Green!

**Comment by jonathanjuursema** [comment]
@Janwillemtv is there any chance you will be fixing this issue soon, or does it have to be reassigned?

**Comment by Peeterus** [comment]
Wait is this open or closed now?

**Comment by jonathanjuursema** [comment]
Closed, but for archival and statistical purposes I like to have each closed issue to have an assigned person that is most related to the issue. ;)

Maybe for this one that should be @Janwillemtv
