### ISSUE TITLE
Tool for OmNomCom Inventory and Order Management

### ISSUE THREAD

**Issue by jonathanjuursema** [saproto/saproto#30]

**Comment by renskruining** [comment]
Hey! If this would be a page that replaces the functionality of tools.saproto.nl/omnomcom, I'd like to add some requests.

I'd love if the following is possible:

- Search terms: make it possible to find orders of specific periods, specific persons or specific products.

- Order input in a slightly different way: 
   - make it easier to select products and persons. This might be done by enabling search on the products. (typing cola and also getting coca cola as well as cola zero, cola light, cola cherry and cola vanilla)
  -enable bulk orders: easily and in a fast way add multiple product orders for 1 person, or 1 product with multiple persons ordering it.

(:


OmNomCom inventory: something might be needed (as database access might change) to replace the page we're using to set up an order: _http://proto.renskruining.nl/omnomcom/_ This uses the following SQL query and script:
``
$query="SELECT products.product_id, products.name, categories.name, COUNT(orders.member_id) 
            AS 'sold', products.available, products.makro_units, products.preferred_stock, products.max_stock 
            FROM products, orders, categories 
            WHERE orders.product_id = products.product_id  
                AND products.category_id = categories.category_id 
                AND orders.date > '2015-09-09' 
            GROUP BY products.product_id
            ORDER BY products.category_id, products.name";
``



``
while(list($product_id, $name, $category, $sold, $available, $unit, $preferred, $max) = mysqli_fetch_row($orders_result))
        {
            if($category!="Activities" AND $category!="Proto Merchandise" AND $category!="Archive - Hidden" AND strpos($name,"ProTube")==FALSE){
                if ($unit==0 OR $unit==NULL){
                    $order = "ZTFZU";
                }
                elseif ($preferred == NULL){
                    $order = "ZTFZU";
                }
                elseif ($preferred == 0){
                    $order=0;
                }
                else {
                    if ($max != NULL){
                        $order = ($preferred - $available)/$unit;
                        $order=ceil($order);
                    }
                }
                if ($available < $preferred){
                    print("<tr><td>$name</td><td>$category</td><td>$order</td></tr>");
                }
            }
        }
``

**Comment by renskruining** [comment]
Just realised something I use very often: I'd love to filter the overview of orders by product and/or category. I use this to see if dinner orders have been put in the system and how many of specific products have been bought on specific days (pilscie products)

**Comment by jonathanjuursema** [comment]
The most important functions have been committed, I'd propose to see what smaller function are useful after the holidays and implement those as they are needed. :)

**Comment by renskruining** [comment]
Hey! 
If it's possible, could you tell me whether a new tool replacing [http://proto.renskruining.nl/omnomcom/](http://proto.renskruining.nl/omnomcom/) is possible before you migrate the databases? (as the OmNomCom NEEDS this tools to set up the right Makro orders)

if not, is it still possible for me to use the current tool around the 19th or 20th of August?

**Comment by jonathanjuursema** [comment]
As for the second question, probably not. We'll be migrating the website somewhere in the week before the Kick-In.

As for the first question, as far as I get from the queries you just need a table that shows all relevant items  and how many collos you need to order? If so, how do you want to calculate the amount of items you need to order, by going 'we have so many, and we need to buy so many to get to our preferred stock', or is there more logic behind it?

**Comment by renskruining** [comment]
Basically, that's all the logic there is (:

Having an amount we have, calculating an amount of Makro products (collos) needed to get to the preferred stock and then displaying some table with name of product, amount available and amount of collos needed would be fine.

**Comment by jonathanjuursema** [comment]
Then I'll do that for all products that are listed as 'default in stock'.

**Comment by renskruining** [comment]
Awesome!

On Mon, Jul 18, 2016 at 7:50 PM, Jonathan Juursema <notifications@github.com
