### ISSUE TITLE
Newsletter inprovements

### ISSUE THREAD

**Issue by laurier1122** [saproto/saproto#300]
een vinkje waarmee ik kan beslissen of een activiteit in de newsletter komt en plaatjes van de activiteit in de newsletter.

**Comment by jonathanjuursema** [comment]
It's in the association admin menu under "edit newsletter"! You can toggle whether events appear in the newsletter, and if there are no events scheduled to appear in the newsletter it will not be sent on monday morning. You can preview the newsletter [here](https://www.proto.utwente.nl/newsletter). Per default events are set to not appear in newsletters, so the newsletter is currently empty. :)
