### ISSUE TITLE
Bug report: Event staat wel aangegeven in de calendar op de homepage maar niet op de calendarpage

### ISSUE THREAD

**Issue by KaDayKa** [saproto/saproto#303]
_What page or functionality is this issue about?_
the calendar function

_What were you trying to do?_
view and edit an event from the calendar page

_What did you expect would happen?_
to see the event I made (it was visible in the google calendar)

_What did happen instead?_
I didn't see the event but Xadya did on the homepage

_Where there any error or confirmation messages?_
no, but it was repeatable with not only my computer.

![bugcapture1](https://cloud.githubusercontent.com/assets/8152033/21310922/dcf89390-c5e4-11e6-98c2-4b9235351fe7.PNG)
![bugcapture2](https://cloud.githubusercontent.com/assets/8152033/21310923/dd0bbd08-c5e4-11e6-99d6-9369c63e7f28.PNG)

UPDATE:
I apparently accidentally made the end date earlier then the begin date. changing this solved the issue. Feature request: an error message if the enddate of an event is earlier then the start date.

**Comment by thijsdortmann** [comment]
Can you please create a separate issue for the feature request? As this isn't all-that related to the original issue this issue was about. Also, please write your issues in English in the future, so non-Dutch members of our committee can also read and understand them. :)
