### ISSUE TITLE
Search button non-functioning on mobile

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#310]
At least on mobile, not sure about desktop.
The search button (spyglass) does not do anything upon tapping it. "Enter" has to be used to execute a search.
This is found in the search tool of the omnomcom products

**Comment by jonathanjuursema** [comment]
Confirmed on Chrome Desktop as well. :)

**Comment by renskruining** [comment]
I'd say some javascript would suffice in the form of 
```
<form method="post" action="http://saproto.nl" class="navbar-form navbar-right navbar__search" id="navbar__form">
   <div class="input-group">
      <input class="navbar__search__input form-control" id="navbar__search__input"
                               type="search" name="query" placeholder="Search">
         <span class="navbar__search__icon input-group-addon" onclick="((document.getElementById('navbar__search__input').value)) && document.getElementById('navbar__form').submit();">
            <i class="fa fa-search" aria-hidden="true"></i>
      </span>
   </div>
</form>
```

Although, I do not know your opinion on js

**Comment by jonathanjuursema** [comment]
If you like you can submit a pull request with the change (after you've tested it of course!). Otherwise I'll try to find time to fix it after I'm done with the ticket system.
