### ISSUE TITLE
Print attendee checklist for events

### ISSUE THREAD

**Issue by jurvangeel** [saproto/saproto#312]
This is a feature request;

Wouldn't be handy if you can print the participants of an event in a checklist form?
So you can check if everybody is present/in the bus :D

**Comment by jonathanjuursema** [comment]
Sounds like a good idea and easy to implement. As soon as event ticket stress is over, this can be easily done!

**Comment by thijsdortmann** [comment]
Can be found on the edits page of the event, in the Participants details box :)
