### ISSUE TITLE
Can't add total flowchart (in HTML) in webpage

### ISSUE THREAD

**Issue by KaDayKa** [saproto/saproto#317]
hallo,

Als ik de bijgevoegde HTML in een webpage probeer te stoppen dan wil hij de pagina niet juist laten zien. Het lijkt alsof hij het laastse deel van de html weghaalt.

Kasper

[Total flowchart.txt](https://github.com/saproto/saproto/files/739197/Total.flowchart.txt)

**Comment by thijsdortmann** [comment]
Your text is larger than 64kb, which is currently the maximum content size for a page :') Gonna fix that.

**Comment by thijsdortmann** [comment]
And the flowchart is working now :)
