### ISSUE TITLE
Feature Request: Proto Photo Voto 

### ISSUE THREAD

**Issue by robi-wan69** [saproto/saproto#318]
Everyone likes photos, but some are just better than others. 
We'd like a proto photo vote system, so higher rated pictures will be shown more often than less liked.

**Comment by PeterVerzijl** [comment]
Hey All,

This features is worked on and is almost implemented. @Peeterus will do more work on the design end of things but the main functionality for the front- and back-end is completed. Good luck with the rest Pepijn.

Greetz, Tony (Peter) Verzijl

**Comment by jonathanjuursema** [comment]
I'll close this issue for now. We'll take it along with the redesign.
