### ISSUE TITLE
'Frist Member' Achievement is given to primary members, should only be given to secondary

### ISSUE THREAD

**Issue by opwarmpannenkoek** [saproto/saproto#325]
![image](https://cloud.githubusercontent.com/assets/18185955/22714524/31bbd200-ed8d-11e6-867a-0f5d645e00a4.png)

 :cry:

**Comment by thijsdortmann** [comment]
Please provide a clearer title next time :(

**Comment by Peeterus** [comment]
I think this issue initially was about the 'icon not available', not about wrong fristi member assigning. that still is a bug though.
Titles, descriptions and requirements are provided by the board. Title, description and Icon can be changed in browser by the board. if the requirements are not good, they should inform me what the new requirements should be.

**Comment by thijsdortmann** [comment]
Ok. That means that the issue really is too unclear for us to take proper action on...

@opwarmpannenkoek Please create a new issue for the issues with the Fristi Member-achievement, if that was in fact the issue you wanted to submit. Please be clear: provide a description of what you expect to happen and what happened instead. A screenshot is awesome, but not on it's own without context. Check out [this guide](https://github.com/saproto/saproto/wiki/Creating-Issues-101) for more information on what we would like to see in an issue :)

For issues regarding styling, description of achievements and requirements for getting them, please add a comment to #241. This way we can keep the Github issues clean. We as a committee use them as our todo-list, and having a lot of unclear issues makes it difficult for us to see what we have to do and prioritize those things.
