### ISSUE TITLE
Non members in committees/ ticket admin

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#326]
So they can keep track of the amount of tickets sold

**Comment by jonathanjuursema** [comment]
@thijsdortmann do you think this'll interfere with our systems?

**Comment by thijsdortmann** [comment]
Hmm. Should work, as committee memberships are technically given to users, not members. I do see some problems with middleware controlling the access to those tools, though.

**Comment by jonathanjuursema** [comment]
I think we mostly check for middleware `auth`, not `member`, since we need to do additional checks anyway. We'll see. :)
