### ISSUE TITLE
Links in activity descriptions

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#334]
Activities often have links(URLs) as text instead of actual links (same for email addresses)

Maybe it would be interesting to have automatic link implementing

or just have the board, who types and inserts the descriptions, be aware of how to make them actual links

thanks
-a hopeful member

**Comment by jonathanjuursema** [comment]
For some older activities there is an explanation for this related to the import of data from the old site in the new site (see also #95). For newer activities this would have to be done by the people writing the description :)

**Comment by jonathanjuursema** [comment]
Received no reply, so assuming sufficient feedback.
