### ISSUE TITLE
OmNomCom (menu) editable page

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#340]
Hi! This is a feature request regarding website functionality for the OmNomCom.
We'd like the following functionality:
A page under the OmNomCom menu which we can edit ourselves. This merely has to be a page with textual option much alike other pages the board has made.

Optionally we'd like to have access to editing the menu by adding links to external pages and such.

I hope this is clear enough, otherwise, let me know.

**Comment by jonathanjuursema** [comment]
This is difficult as the OmNomCom menu has more dynamic entries that cannot be managed by the menu editor (various roles required to view various menu items), as well as the fact that only the board can edit pages (pages cannot be delegated to committees). The changes involved to realize this are rather large. What is the specific use case? @thijsdortmann , most of these features are yours. What do you think?

**Comment by renskruining** [comment]
Hey! Thanks!
The specific use case: we'd like to use this page to gather instructions,
tutorials, useful links and more.

With kind regards,
Rens Kruining

06-46518673

**Comment by jonathanjuursema** [comment]
I've discussed this with @thijsdortmann and we think the implications for the current functionality outweigh the benefits for this specific use case, so we'll not be implementing this one. 

We do however want to let you know you can get a network share to put all your committee information! If you're interested, please send us an e-mail!
