### ISSUE TITLE
Achievements op firefox hebben problemen - Pepijn

### ISSUE THREAD

**Issue by robovs** [saproto/saproto#341]
Please provide us with enough information to respond to your issue. If you're unsure what this means, please see [this guide](https://github.com/saproto/saproto/wiki/Creating-Issues-101).

Issues with insufficient information will be rejected without a response. Please remove this text before submitting your issue.

**Comment by jonathanjuursema** [comment]
As noted in the issue description, there is insufficient information to determine the "problems". This issue will be closed.

**Comment by Peeterus** [comment]
Achievements dont display right in firefox and on mobile screens
