### ISSUE TITLE
If signup is not possible yet, people can signup for the backuplist

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#344]
For schrala, signup is possible from friday on, but people did already signup for the backup list. This is not so convenient, because now people can signup before we can hype :(

**Comment by jonathanjuursema** [comment]
I'm actually surprised this bug hasn't surfaced earlier than this. :P 

The bug is fixed, where applicable you can manually remove people from the sign-up list. Back-up participations are not automatically converted to real participations!

**Comment by jonathanjuursema** [comment]
Ok, this wasn't actually fixed. Or we fixed something different. Let's check.
