### ISSUE TITLE
Search field impossible to select on certain page widths

### ISSUE THREAD

**Issue by WDeenik** [saproto/saproto#349]
On certain page widths, the normal top menu is still in use. However, when hovering over the search button, the search field will expand, causing the menu to 'hit' the 'Study Association Proto' text in the top left and moving down to fit on the page. When moving the cursor to select the search field in its new position, the search field collapses again, causing the menu and search box to move all the time.

Maybe change to the compact menu as soon as the width is too low for the expanded search box to fit?

**Comment by jonathanjuursema** [comment]
@WDeenik I don't have a good solution for this yet, but in the meantime: you can always (both mobile and desktop) click in the search icon to get to the search page, so you can at least use the search functionality. :)

**Comment by WDeenik** [comment]
Yeah figured that out and it's not a MAJOR issue now, just thought it looks glitchy and makes the site look less professional than it actually is ;)

**Comment by jonathanjuursema** [comment]
I totally agree. :) @regnerus said he has a fix and will fix it soon!
