### ISSUE TITLE
back up list fails

### ISSUE THREAD

**Issue by jurvangeel** [saproto/saproto#352]
Emiel tried to sign up for the backuplist of the schrala and the system told both of us (I impersonated) that it broke.

He now is 46th in the sign up, but that should be 1st on backup

**Comment by jonathanjuursema** [comment]
Please do not forget that if you 'force subscribe' someone as board, you bypass any checks (e.g. whether they are a member, whether sign-up was closed, etc.).

**Comment by jurvangeel** [comment]
I know, but I wanted to ensure is spot as first on the backuplist (so that
was sort of a bugfixpatch).
but that doesn't solve the fact that he (personal and via impersonate)
couldn't sign up of the backuplist.

On Sat, Mar 4, 2017 at 12:22 PM, Jonathan Juursema <notifications@github.com
