### ISSUE TITLE
Increase ProTube maximum allowed video time

### ISSUE THREAD

**Issue by opwarmpannenkoek** [saproto/saproto#354]
A lot of (classic) rock songs are > 5 minutes. Therefore I propose setting the maximum length of a video at 8-10 min instead of 5. 
Examples:
https://www.youtube.com/watch?v=K9GcoCV31gc
https://www.youtube.com/watch?v=x2KRpRMSu4g
https://www.youtube.com/watch?v=JwYX52BP2Sk

**Comment by jonathanjuursema** [comment]
@saproto/board is this something you want?

**Comment by DennisVinke** [comment]
No, we think the time limit now is good enough.

**Comment by jonathanjuursema** [comment]
I closed this issue because the board doesn't want to have the ProTube limit changed, sorry!
