### ISSUE TITLE
Styling issue ProTube - Firefox

### ISSUE THREAD

**Issue by opwarmpannenkoek** [saproto/saproto#356]
![image](https://cloud.githubusercontent.com/assets/18185955/23621809/7be058c8-029c-11e7-9b81-8845ae68a524.png)
In FireFox small up/down buttons appear in the ProTube login screen. You can still type to login, and post-login is working fine, but the buttons are nonfunctional and distracting. They are stuk.

**Comment by jonathanjuursema** [comment]
This is most likely something @regnerus didn't test for in the ProTube client.

**Comment by regnerus** [comment]
It was actually reported as a Firefox bug, but there is a workaround.
