### ISSUE TITLE
Webdesign improvement: Search engine

### ISSUE THREAD

**Issue by robi-wan69** [saproto/saproto#359]
![search engine](https://cloud.githubusercontent.com/assets/18185955/23628761/aaad4a3a-02b5-11e7-9f8d-efb6c4b70e17.png)

The new search engine should automatically categorize the results in three results; persons, events and pages. Events should be sorted on date. Others on relevance.

**Comment by jonathanjuursema** [comment]
This issue will be closed in favor of #520, but referenced so that the design work is not lost.
