### ISSUE TITLE
SmartXp Screen

### ISSUE THREAD

**Issue by jonathanjuursema** [saproto/saproto#36]

**Comment by jonathanjuursema** [comment]
RFC: https://www.fb.com/1172016646163144

**Comment by jonathanjuursema** [comment]
Features that will currently be implemented are (>5 votes):
Upcoming Proto Activities (24 votes)
CreaTe Timetable (20 votes)
The Time (18 votes)
Bus Information for UT/Westerbegraafplaats and UT/Hallenweg (11 and 7 votes)
ProTube Now Playing (11 votes)
Fishcam (6 votes)

Quote corner will not be shown on the screen because these are usually vulgair. :)

**Comment by regnerus** [comment]
For some design/layout inspiration look at the Panic Status board. https://panic.com/blog/panic-status-board-2013-edition/
