### ISSUE TITLE
ProTube Skip is not correctly implemented

### ISSUE THREAD

**Issue by jonathanjuursema** [saproto/saproto#361]
The ProTube skip is currently not working. The product is there (although invisible) but the logic is missing.  :(

**Comment by jonathanjuursema** [comment]
@thijsdortmann would you please make a webhook for me? :D

**Comment by thijsdortmann** [comment]
Herbert now has an endpoint for skipping tracks: `env('HERBERT_SERVER') . "/skip?secret=" . env('HERBERT_SECRET')`
