### ISSUE TITLE
Navigation bar too wide for > 1280px width screens.

### ISSUE THREAD

**Issue by regnerus** [saproto/saproto#363]
With the addition of the Slack item in the navigation bar it is getting too wide for > 1280px width screens.

<img width="1280" alt="screen shot 2017-03-08 at 11 15 32" src="https://cloud.githubusercontent.com/assets/285450/23699755/9cce9c3e-03f0-11e7-8f1e-332f4c946ae2.png">

A second issue which could become a problem is people with a relatively long last name, the nav bar will then even take more space. We could for example switch to just using a profile picture, similar to what Github is doing it it's navigation bar.

**Comment by jonathanjuursema** [comment]
I like the profile picture suggestion!

**Comment by regnerus** [comment]
Great, I will self-assign this issue.
