### ISSUE TITLE
Customizable navigation bar (hide slack button)

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#367]
Hi!

I'd love to have the option (in dashboard for example) to hide the slack button)
It takes up a lot of space (like mentioned in issue #363 ) and as I already know of the slack, I wouldn't mind it not being there.

I hope this is a possibility.
😘

**Comment by jonathanjuursema** [comment]
You can now dismiss the Slack navbar thingy with a button in the pop-up.
