### ISSUE TITLE
Extension to mail tool to include future mails to include activities

### ISSUE THREAD

**Issue by DennisVinke** [saproto/saproto#368]
Like discussed earlier, we would like to have automatic mails for certain activities. Would it be possible to include this in the mail tool so we can schedule mails in advance for the activities we would like to use this for. 

The idea is that we can add the activity as a mailing list that will send to all the participants signed up at the moment the mail is send. This way we can tailor the mails to activities instead of having an automatic mail toggle with a standard template.

If you have a better idea for this, please discuss.

**Comment by jonathanjuursema** [comment]
There you go. You can select an event as destination for an e-mail. The drop down list contains all events up to a month ago to keep it tight. The recipients include only the participants, not back-up users or committee members. You can preview recipients like you normally would. It is not possible for users to unsubscribe from e-mails for events.

Also highlighting @xadya
