### ISSUE TITLE
If participant amount is increased, the people from the backuplist are not automatically put in the participant list.

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#369]
Schrala amount is increased from 45 to 60, but the people on the backuplist are not automatically put on the 'normal' list of participants.

**Comment by jonathanjuursema** [comment]
If you wish to quickly fix this right now, impersonate someone and let them sign in and out for the activity until everybody is moved from back-up to participants. A sign out for the event triggers a "move someone from the back-up list" update.

Will probably get to this tonight.
