### ISSUE TITLE
Feature request: Digital Library

### ISSUE THREAD

**Issue by robi-wan69** [saproto/saproto#374]
To promote the use of literature by members, it would be great to have an online catalogue of the books/magazines available in the Protopolis. 
PDFs/ePubs could also be in there; however is this legally possible?

**Comment by jonathanjuursema** [comment]
Well, debatable. Usually books and magazines are protected by copyright. We cannot (and thus should not) publish PDF's or ePub's unless we have permission, they are released to the public domain, or they are ours. What kind of magazines are we talking about?

**Comment by opwarmpannenkoek** [comment]
Thought so about digital books.
I was thinking an online catalogue of the books/magazines available in Protopolis to read/lend, showing an overview of the titles, authors, categories etc. So also Make magazines for instance. To stimulate the use of books/magazines and increasement of the association's collection. 
Like a simplified version of https://www.utwente.nl/nl/lisa/bibliotheek/#digitale-bibliotheek

**Comment by jonathanjuursema** [comment]
That is possible without any copyright issues. I'll leave this here as a [feature proposal](https://github.com/saproto/saproto/wiki/Feature-Proposals) for now. :)

**Comment by jonathanjuursema** [comment]
I'll close this feature proposal since there hasn't been any expressed interest as per the [guidelines](https://wiki.proto.utwente.nl/ict/issues#special_notes_for_feature_proposals).
