### ISSUE TITLE
Backup list people that are now on participant list don't get an email

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#375]
People don't know that they have a ticket, because they don't receive an email when they are no longer on the backuplist. Can they get an automatic email?

**Comment by jonathanjuursema** [comment]
These people should already receive an e-mail. I just checked, and  there are also no stuck e-mail jobs. Can you send me some e-mail addresses (in a private message) that should've received the e-mail? And can you confirm whether all or only some of the people didn't get the e-mail?

**Comment by xadya** [comment]
Apparently, some people do not read their mail at all. Discard this ..

**Comment by jonathanjuursema** [comment]
I'm just glad it wasn't broken. :)
