### ISSUE TITLE
Feature Request: Text To Speech Engine (TTS)

### ISSUE THREAD

**Issue by robi-wan69** [saproto/saproto#376]
In the ProTube admin panel, a TTS engine would be of added value to the soundboard.
There are several wrappers/APIs for the Google Translate TTS for instance. Like: https://github.com/AlboVieira/google-speech-tts

We can also make it a form of income by asking members €0,05 per TTS line. MONEY. But that's optional.

**Comment by DennisVinke** [comment]
I can only foresee a lot of chaos and abuse of this and the board agreed with my reasoning.
