### ISSUE TITLE
The popular quote does not seem to work

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#388]
The popular quote at the moment is one of march 6th. We hoped to renew this more than happens now. Is it possible to have the popular quote maximally be there only for a week or so (and then a new one)?

**Comment by Peeterus** [comment]
it is currently set to take the quote with the most votes from the last month. would you like this to be the last week?

**Comment by xadya** [comment]
I'd love that:)

**Comment by jonathanjuursema** [comment]
Closed by @Peeterus via #390
