### ISSUE TITLE
The edit event page layout is broken

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#389]
See picture:
![image](https://cloud.githubusercontent.com/assets/8876164/24148387/da86cf94-0e3e-11e7-924f-a1906b6d633e.png)

**Comment by jonathanjuursema** [comment]
This is not isolated. On the dashboard also the backgrounds and borders of the panel-in-panels is gone (RFID cards and Studies for example).

**Comment by regnerus** [comment]
I can style the "panel-in-panels" based on the fact that they are panels inside other panels but we can also give them a different class to prevent unwanted behaviour?
