### ISSUE TITLE
Allergies included on site

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#391]
We thought it would be a nice idea to have an option on your dashboard where you can state your allergies. Maybe these allergies can than be included as text behind someone name when you click on the participants checklist. 
![image](https://cloud.githubusercontent.com/assets/8876164/24151032/e2be3996-0e47-11e7-9eea-92ddf8299700.png)

or have them as 
![image](https://cloud.githubusercontent.com/assets/8876164/24151208/59167d60-0e48-11e7-8e4d-0a93429aa4df.png)

**Comment by renskruining** [comment]
Is this close to implementation? d:
The dies dinner is coming, so it would be awesome to see it in action

**Comment by jonathanjuursema** [comment]
Not yet. Will make this a priority!

**Comment by renskruining** [comment]
Awesome!

With kind regards,
Rens Kruining

**Comment by jonathanjuursema** [comment]
On the dashboard you can now enter allergy and diet info. If the board indicates an activity includes food (this can be done by editing an event) the event admins (committee + board) can see this info for the relevant participants in the event admin page. This information is hidden again a week after the event is ended. #privacybydesign

**Comment by renskruining** [comment]
Hey!
Is it broken, or just not accessible after an activity has closed (for example [Dies Dinner](https://www.proto.utwente.nl/events/admin/660)) ?
Thanks!

**Comment by jonathanjuursema** [comment]
See me previous comment. :)

> This information is hidden again a week after the event is ended. #privacybydesign

**Comment by renskruining** [comment]
oops, misread that/forgot I read it before. Too bad, though ): I guess I just don't like design, insight can be more important (especially when making budget plans for activities).
There's no way we can know how many vegetarians are among the active Proto members, right?

**Comment by jonathanjuursema** [comment]
Not easily. The allergies and diets field is a text field, so it's not something we can easily interpret programmatically. Also, knowing how many vegetarians are in Proto doesn't help if you can't identify who are likely to visit activities (although at this point probably only active people have their allergies and diets info registered). And since medical information (which at least the allergies is definately a subset of) is a personal information that is extra protected by law, I'm a bit hestitant to reveal it too often and too much linked to specific persons.

**Comment by renskruining** [comment]
Ah, okay. I guess I'll just guesstimate. 
I'm working on the budget plan for the OmNomCom BBQ, and vegetarian dishes can fall in a different price range. If like 50% is vegetarian, the extra costs can't be covered as easily as when it's only 10% of the participants (exaggerated example, of course (:   )

**Comment by jonathanjuursema** [comment]
Might I suggest asking the ACE how many vagetarians have been on their midwinter barbecues to get a rough estimate?

**Comment by renskruining** [comment]
Ah, yes, thanks!
