### ISSUE TITLE
'Skippy-Bal' achievement suggestion

### ISSUE THREAD

**Issue by Habenga** [saproto/saproto#398]
I would like suggest an achievement called the Skippy-Bal: 'You're too decadent to enjoy other people's music!'

It would be granted for those who buy a lot of skips in a certain period of time, say more than 40 a year or so. 

I would suggest a pink skippyball a icon for the achievement.

**Comment by DennisVinke** [comment]
The board did not see a benefit in having this achievement other than to have people spend money to buy an achievement.
