### ISSUE TITLE
Feature Request: Helped Events - Photo album linked

### ISSUE THREAD

**Issue by robi-wan69** [saproto/saproto#399]
For the Protography committee I would like to see if a photo album is linked at the helped events. 
My suggestion is that a small checkmark or cross will tell this.  
Another option would be to show a small camera icon at every event (even in the calendar), to show that a photo album is linked.

**Comment by jonathanjuursema** [comment]
How exactly do you mean "for the Protography"? Would you like all events in the calendar to show a "this event has photos" thingy, or do you mean specifically on the Protography committee page? Or if it's something else, can you please describe in a bit more detail what exactly you mean?

**Comment by robi-wan69** [comment]
For me it would be of use to see if an event where Protography help was requested, has a photo album linked. So on the Protography page with all the events would be my choice. 
 
However; this can be expanded site-wise. Instead of just a checkmark on the Protography page this could be site-wide with a camera icon, showing that an event has a photo album linked. So it's also of use for other people. For instance like in the screenshot.

![image](https://cloud.githubusercontent.com/assets/18185955/24527688/957efdce-15a3-11e7-9ce1-c5778937e331.png)

**Comment by jonathanjuursema** [comment]
I'll close this feature proposal since there hasn't been any expressed interest as per the [guidelines](https://wiki.proto.utwente.nl/ict/issues#special_notes_for_feature_proposals).

Also, the use case is relatively small and mostly covered by the fact that you can link albums to activities.
