### ISSUE TITLE
Participants checklist for members (event admins)

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#400]
I heard that board has access to a checklist of participants of events. This would be awesome for normal members (event admins), too!

**Comment by xadya** [comment]
Maybe for the organising committee?

**Comment by jonathanjuursema** [comment]
@thijsdortmann I believe there was a reason we didn't do this but I'm not sure. Can you remember?

**Comment by renskruining** [comment]
Is there an update on this? @thijsdortmann @jonathanjuursema ? (:

**Comment by thijsdortmann** [comment]
I don't there is a good reason not to allow this. So let's make it accessible to event admins :)

**Comment by renskruining** [comment]
Dear Have You Tried Turning It Off And On Again committee,

I would like to ask you to improve this existing tool. Preferably the checked members are saved (automatically) for later access. This would also be useful for the treasurer and board to later see which members actually showed up.

Another improvement is to list the people together with their age (or paired with <18 if that is the case) and allergies if possible.

**Comment by jonathanjuursema** [comment]
Can you make that a new issue? :)
