### ISSUE TITLE
Website is crooked?

### ISSUE THREAD

**Issue by WDeenik** [saproto/saproto#401]
What page or functionality is your issue about?
Seems all pages are affected

What were you trying to do?
Just visiting the website really...

What did you expect would happen?
That I would get to see a straight levelled website like most other websites and like what the Proto website looked like yesterday

What did happen instead?
Well, instead everything on the page was crooked a bit if you know what I mean. Every page is crooked, and always a bit differently. I tried holding my laptop on different angles while reloading the page but that did not seem to matter. I have no idea, are you sure the server is levelled and stable in a rack? Maybe it is wobbling about causing the page to be rendered differently. Or maybe my laptop is possessed by a drunk virus/ghost, but every other page I visit looks normal, so that would be a virus/ghost having some weird obsession with Proto.

Where there any error or confirmation messages?
No everything else acts normal.

**Comment by jonathanjuursema** [comment]
I checked server diagnostics and apart from the [Russian Hack](https://www.facebook.com/groups/574894482542033/permalink/1478255138872625/) the server's leveling sensor seems to indicate it is indeed not levelled in the rack. We'll need to investigate the server rack...

**Comment by WDeenik** [comment]
Weird, maybe the Russians needed physical access to get into the server and messed things up there too? Ah well, compared to the hack itself it's a small side-problem, wouldn't want the Russians to know how much I spend on beer... :/

**Comment by jonathanjuursema** [comment]
Good news! Although the Russians were able to get away with [a little bit of data](https://pastebin.com/87ba9TZ3) the visual issues on the website had nothing to do with Russian industrial design hackers, but indeed with the fact that for some reason the Proto server was mounted upside-down in the rack like @WDeenik suggested. The server is now mounted correctly and all issues seem to be fixed! Thanks @WDeenik for the tip.
