### ISSUE TITLE
Non-Proto Activities

### ISSUE THREAD

**Issue by regnerus** [saproto/saproto#410]
Related to the calendar issue of #409, lately there are a lot of "activities" which are not Proto related (UTchallenge, Jesus Christ Superstar, etc.). Previously there was a separate calendar for these kind of events, maybe add such a separate calendar again?

**Comment by jonathanjuursema** [comment]
We can make a toggle in activities (external or internal) and two seperate iCal feeds. Also, in the calendar on the site we can distinguish the two. @saproto/board, what's your opinion?

**Comment by robi-wan69** [comment]
I wouldn't want two separate agendas. My proposal is a small (colour) tag to distinguish them

**Comment by thijsdortmann** [comment]
Maybe we could create 'custom' iCal feeds? So that a user can select which types activities they are interested in.

I also really like the idea of colour tags (as mentioned by @robi-wan69 and Margot in #418).

**Comment by jonathanjuursema** [comment]
@robi-wan69 do you mean for the iCal or the calendar on the website?

**Comment by robi-wan69** [comment]
@jonathanjuursema Calendar on the website.

**Comment by jonathanjuursema** [comment]
Made a new combination issue for this in #432. :)
