### ISSUE TITLE
Back-up-list to sign-up-list automatic placement

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#413]
Hi!

my question is: is the board also notified, alongside the member, when the member is automatically moved from a back-up list to the sign-up list when a spot has become available?

If not, could this be changed? This helps the board keep up to date and stay aware of members that they might have to send an email (EWI-trip for example)

**Comment by jonathanjuursema** [comment]
Not yet, but this can be done. @saproto/board would you like the board, the committee, or both to be notified?

**Comment by xadya** [comment]
Yes, I'd like this :)

**Comment by jonathanjuursema** [comment]
And who should be notified?

**Comment by xadya** [comment]
The board would be sufficient.

**Comment by renskruining** [comment]
👌🏻
