### ISSUE TITLE
Feature request - Label calender items by category

### ISSUE THREAD

**Issue by margotr** [saproto/saproto#418]
<img width="372" alt="screen shot 2017-04-10 at 15 35 47" src="https://cloud.githubusercontent.com/assets/9929190/24864080/6d4964ee-1e03-11e7-9723-e08412821304.png">

**What -** See title. For example give Educational stuff a different color. 
**Why -** This view is meant to be a quick glance into the calendar of S.A. Proto. 
Now I have to actively search for stuff that's relevant to me. For non-CreaTe-studying members this is mostly activities that are not related to study. 
**Idea for implementation -** Colored labels in the upper right corner a la Github, e.g. an orange label for all educational activities.

**Comment by jonathanjuursema** [comment]
Similar to #410, can be done in one consistent update?

**Comment by jonathanjuursema** [comment]
Made a new combination issue for this in #432. :)
