### ISSUE TITLE
incorrect avatar format? (website keeps calling me silly)

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#420]
Dear,

The website keeps calling me silly
![screen shot 2017-04-10 at 20 31 53](https://cloud.githubusercontent.com/assets/9930890/24876678/e1511b24-1e2c-11e7-9190-e3b03505cd33.png)

I'm trying to put a .png as my new avatar, but upon clicking the green button, the page refreshes with the above message. This .png file does exist on my laptop and has no weird or special characteristics as far as I know.

Is the file format wrong? (this would preferably be mentioned somewhere) Is my picture just too silly? Am I really too silly to do this?

**Comment by renskruining** [comment]
also, issue 42 * 10!
or four-twenty...

**Comment by renskruining** [comment]
So, is the whole thing broken, or does it need a very specific format?

**Comment by jonathanjuursema** [comment]
It *should* accept at least jpg and png.

**Comment by renskruining** [comment]
🙃 I guess I'll keep being called silly until it's fixed.
Thanks for working on it!

Kind regards/vriendelijke groet,

*Rens Kruining*
+31 6 46 51 86 73 | renskruining.nl

On Sun, Apr 16, 2017 at 5:42 PM, Jonathan Juursema <notifications@github.com

**Comment by regnerus** [comment]
Why am I assigned to this issue, it seems back-end related? A front-end form sends data to a back-end url, no front-end check is done for checking for the file format.

**Comment by jonathanjuursema** [comment]
@renskruining you cannot accidentally submit the form anymore when you didn't select a file to upload, and the upload controller checks whether what you've uploaded is an image and gives you appropriate feedback. :)

**Comment by renskruining** [comment]
Thanks!
