### ISSUE TITLE
PilsCie tool to see how much products were bought during a drink

### ISSUE THREAD

**Issue by DennisVinke** [saproto/saproto#423]
The PilsCie wants to keep track of how much beer gets waisted during a drink, so they need a tool to see how much beer, wine and other products have been sold during a drink.

**Comment by thijsdortmann** [comment]
Something like this is already possible for the treasurer. I will look into making a specific version of that tool for the Pilscie.

**Comment by jonathanjuursema** [comment]
@thijsdortmann the addition here is that it is only necessary for the pilscie financial account, and per day there should also be a break-out of the income per product (instead of only per account).
