### ISSUE TITLE
proto.ink articles no longer on front page

### ISSUE THREAD

**Issue by jonathanjuursema** [saproto/saproto#426]
The proto.ink articles no longer show up on the homepage, just the proto.ink logo. The API seems to work but I get `Uncaught TypeError: Cannot read property 'date' of undefined` in my console.

**Comment by regnerus** [comment]
It seems that the javascript is broken, has someone removed the Angular dependency but not the references for example? I get `ReferenceError: Can't find variable: angular`

**Comment by regnerus** [comment]
Can't find something like that in the most recent commits, will look into it.

**Comment by regnerus** [comment]
Dependencies were missing from the bower file. Fixed in pull request #428
