### ISSUE TITLE
Feature request: Concatenate the "My Profile" and the "Dashboard" pages.

### ISSUE THREAD

**Issue by PeterVerzijl** [saproto/saproto#427]
It is very confusing to have, essentially, two profile pages. One where you can just view you profile, and another where you can edit your profile. I would like it, from a usability perspective, to just be one page. Where you can view, and edit your own profile and account settings.

**Comment by jonathanjuursema** [comment]
It's definately doable and indeed maybe preferable. Can the design group (@regnerus @robi-wan69 @Janwillemtv) do something with this so the devvers can implement it?

**Comment by robi-wan69** [comment]
I agree. Will discuss and get to it hopefully soon.

**Comment by jonathanjuursema** [comment]
This issue will be closed in favor of #520, but referenced so that the design work is not lost.
