### ISSUE TITLE
Feature request: Protube scoring system

### ISSUE THREAD

**Issue by WDeenik** [saproto/saproto#429]
People keep complaining about the limit on video lengths in Proto. Of course this limit has to be set somewhere and it makes sense to keep it a bit short to make sure songs that are generally 'unwanted' do not stay on for too long and the better music can continue soon.

However, there are quite some people that try to match the music most people want to listen to at that moment and I think it would be nice to encourage this behaviour. Maybe it is an idea to make a like/dislike option for the current song in the new remote, and if the system knows who added that song , that person's 'ProTube-score' is adjusted, and the score per person determines the maximum length of the videos that person can add. With of course still some hard lower and upper limits.

This encourages people to add songs that people actually want to listen to, and makes it possible for people to add longer videos once they proved they can handle that 'responsibility'.

**Comment by jonathanjuursema** [comment]
Before we'll consider technically implementing this I'd like the opinion of the @saproto/board. Also, since this a request involving substantial code changes, please check the [notes for feature proposals](https://github.com/saproto/saproto/wiki/Creating-Issues-101#special-notes-for-feature-proposals).

**Comment by xadya** [comment]
Hmm. I do see pros and cons, but rating someone makes it a bit harsh for people that just want a very bad musicvideo in there for once, so the fun goes a bit off. You could just ask the board/protopener and they can put the video in for you.

**Comment by WDeenik** [comment]
Personally I wouldn't want to bother the board with every song that's a bit longer than 5 minutes. In the proposed system it would also still be possible to ask the board when you want a bad music video. Probably it happens more often that people want a somewhat longer music video than a bad music video.

**Comment by robi-wan69** [comment]
This proposed system feels very unnecessary and will give a clear distinction between furniture and people who visit Proto once in a while, discouraging the last one.
 
I would still propose #354 then; I do agree that a lot of good songs are longer than 5 minutes. While we may not need 20 minute progrock songs, a slight increase of maximum time is easier to implement than this voting system. 
And perhaps a countermeasure could be implemented to decrease abuse, but it's very hard to define  "what's wrong".

**Comment by Vleugelhoff** [comment]
I know the venga-hurt is still felt by many furniture people, but these songs last for 3 to 4 minutes. so shortening someones entry rights is of nu use against "bad" music. Most classical music however is 15 minutes or more and generally accepted as good music. My point is, music length is not related to music quality. Therefore reducing the time of songs someone can enter achieves nothing. However, voting per song could work if a certain song is banned after X down-votes. Don't punish the 'crime' prevent it from happening again.

**Comment by xadya** [comment]
I don't see any good in banning songs and thereby preventing people to show their taste in music to the Protopolis.

**Comment by jonathanjuursema** [comment]
Due to mixed opinions and negative feedback from the board I'm closing this feature proposal.
