### ISSUE TITLE
Proto.ink articles lay-out overlap other style elemants when lines break.

### ISSUE THREAD

**Issue by jonathanjuursema** [saproto/saproto#431]
This should have some nice overflow protection.

![capture](https://cloud.githubusercontent.com/assets/1134192/24966415/26730ad4-1fa7-11e7-92d9-e5b26a8fc902.PNG)

**Comment by jonathanjuursema** [comment]
The issue still persists on Edge, Chrome and FireFox, after explicitly clearing the cache.

![image](https://cloud.githubusercontent.com/assets/1134192/25405280/2190c0ea-2a03-11e7-868a-71144a081911.png)

**Comment by regnerus** [comment]
The issue had to do with the ellipsis in the titles right on the right side? Meaning that they did overflow when the titles were too long. I can't test on Edge but it should be fixed in Chrome and Firefox also don't see this issue in the latest screenshot?
