### ISSUE TITLE
Make categories for events, distinguish on website

### ISSUE THREAD

**Issue by jonathanjuursema** [saproto/saproto#432]
This issue combines #410 and #418. The idea is to make some categories (external, education, sponsored etc.) that events can be in. This can then be reflected and or filtered on the site, and optionally in the iCal stream.

I'd like the opinion of the @saproto/board and the @saproto/website-developers on this one as well. :)

**Comment by robi-wan69** [comment]
Within design we've also talked regarding having a couple of events as Featured/Highlighted. 
While on the topic of events, I would also like the opinion on this.

**Comment by xadya** [comment]
We do see the use in categorizing internal/external activities, so we can put, for example, create tomorrow in the external calendar. We do not see much use in other categories though.

About the featuring events, we do not really like this idea. We think it is unfair that some activities have priority over other activities and therefore do not like this.

**Comment by jonathanjuursema** [comment]
Then we'll implement the variant where you can make an event external. We'll also make an option to not have external activities imported in your iCal.
