### ISSUE TITLE
IMPORTANT: comma input for number fields

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#442]
Hi! 

The website uses dots in decimal numbers, but doesn't say this explicitly. This has not been a big problem with the omnomcom system, as most of the time (though not always) it was noticed and changed. (people typing 1,25 which changes to 1)
However, as prices of activities can only go down, when 17,99 changes to 17 , it becomes a problem.
Preferably, the number fields would accept both commas and dots as decimal indicators. However, if not possible, could they check if a comma was typed? 
last resort solution: make the page notify the format with a text above the field, telling the person it should be a dot.

Thank you!

**Comment by thijsdortmann** [comment]
Should be easy. A simple `str_replace(',', '.', $form);` should do the trick. Do you have a list of the pages where this is a problem?

**Comment by renskruining** [comment]
With kind regards,
Rens Kruining

06-46518673

**Comment by renskruining** [comment]
The page of editing/new product (omnomcom)
the page of editing/new activity (board)
are as far as I know at least the pages that have this problem.
maybe Xadya could help with the board pages (I don't know how to mention her github account)

**Comment by xadya** [comment]
I think you covered all of them :) Thanks for pointing out though.

**Comment by jonathanjuursema** [comment]
For the specific situation you mentioned, @renskruining, I believe the original price before sign-up closed was €20,00. I can manually change the activity price to €17,50 if nobody signed up since it was €17,00. Please let me know if this is what you want. :)

**Comment by renskruining** [comment]
Hey! Would be appreciated if you could do that for us. Thanks!

Kind regards/vriendelijke groet,

*Rens Kruining*
+31 6 46 51 86 73 | renskruining.nl

On Thu, Apr 20, 2017 at 1:04 PM, Jonathan Juursema <notifications@github.com

**Comment by jonathanjuursema** [comment]
There you go, another €20. :)

**Comment by renskruining** [comment]
€19,50 * 🙃

Kind regards/vriendelijke groet,

*Rens Kruining*
+31 6 46 51 86 73 | renskruining.nl

On Thu, Apr 20, 2017 at 1:18 PM, Jonathan Juursema <notifications@github.com
