### ISSUE TITLE
Proto log-in gives unclear pop-up about UT login

### ISSUE THREAD

**Issue by margotr** [saproto/saproto#445]
When I click Proto-login with my UT credentials, it tells me to log in with the UT button. See the screenshot below!

_Apologies in advance for the long read, and the inconsistency in the spelling of the word login/log-in._

**Why is this confusing?**

- There is a prominent change going on here: log-ins are now meant to be done via the UT log-in.
- This change is not being communicated initially, with the Proto log-in field being very prominent.
- Therefore a member will thoughtlessly enter his credentials there, and those will be their student credentials.
- Suddenly this is no longer the correct course of action, but the user does not know this and could have had no way of knowing this. A pop-up with the basic message 'You're doing it wrong' is not very user friendly and very confusing. 

**A more fundamental issue with this login screen**
By making the log-in fields of the Proto login the most prominent on the page, the user will favour it above the login that's hidden behind a UT button. You will therefore motivate people to login through custom Proto login credentials, but a) that is exactly the type of behaviour you are wanting to change with the UT login and b) people will not immediately know what a Proto login is and what the correct credentials for it are, whether they should know and use those, and how or why.

**Suggested fixes**
- Put, for the time being, a note on the login page that the login method has changed, and encourage people to login with their UT credentials. Don't make them find that out through a pop-up.
- In the pop-up, please mention that there is a change from your side, so that the user does not have to question themselves. Suggestion: "_Students should now login using their University of Twente credentials! To login with your University of Twente account, please click the appropriate button to be taken to the UT-login screen. The Proto login field should be used with Proto-only credentials, in case you do not have a UT account._"
- Hide the Proto login fields until you click the Proto login button (not a new page, just hide and unhide them on a button click event). This will force people to make a considered choice between logging in via UT or via their Proto account.
- Rename the buttons to: "_Login using UT credentials_" and "_Login using Proto credentials_" or something like that. Why? Because you're _in both cases_ trying to log in to the Proto website, making Proto login the most intuitive choice if you're not thinking it through. Renaming the buttons makes clear that the only difference is the way you enter credentials. 

Take an example from websites that want you to login with Google or Facebook due to safety concerns/desired world domination of said companies - similar to what you guys are trying to do. They will give those logins as very prominent options, with underneath it a smaller link with something like '... or click here to login using a custom username'. This steers a user in the right direction without having to tell them that Google/Facebook is the preferred option, while not 'hiding' the old login if you want to or need to use it.

<img width="632" alt="screen shot 2017-04-20 at 11 30 53" src="https://cloud.githubusercontent.com/assets/9929190/25223931/28f30338-25bd-11e7-8a50-e8d03cce255c.png">

**Comment by jonathanjuursema** [comment]
I think I want to go with proposed fixes 2 and 4. Proposed fix 1 will probably mean too much text on the page with a relative small design and 3 adds another action for people who use their Proto username regularly (e.g. all non-student members). 

---

Regardless of this issue (and this is some background) the website and other IT is more steering towards using Proto accounts than UT accounts. We have full control over them and can safely provide log-in methods with them, as opposed to UT accounts. Plus not all members have UT accounts.

This move is something of the past few months and admittedly confusing to longer time members who signed up for Proto using the student number. Also, since it's a transition in the background it's not clear to regular user what exactly changed. I hope that we can bridge this transition with small user-focused fixes like this one. New members already actively use their Proto account, since it's the first thing they set-up before becoming a member. And in a year or two this hopefully becomes a minor issue. :)

**Comment by thijsdortmann** [comment]
I agree with the above.

I think we should make the UTwente login option a bit less prominent, and focus on the Proto login. For the reasons mentioned above, but also for the fact that we now provide some services (mostly to active members, committees and the board) that require you to use those credentials. The Omnomcom also doesn't accept UT logins anymore.

**Comment by jonathanjuursema** [comment]
I updated the login views. Is this satisfactory? :)

**Comment by margotr** [comment]
Check, the fact that is actually _is_ desirable to use your Proto account was not clear to me. In which case my story changes a bit, but it also reinforces the fact that right now it is not clear to the user what the desired workflow is regarding accounts.

In this case, fixes 2 and 4 are indeed appropriate. However, I would like to add

- Make somehow clear that the usages of a Proto account is preferable (for example, because Omnomcom), and where I can find/get Proto credentials if I'm used to UT credentials. Right now, the pop-up message actively steers towards logging in with UT credentials. I suggest altering the text of fix 2 to reflect this.

- If Proto log in has priority, consider making that the first option instead of the UT login.

EDIT: Regarding your updated view: awesome. However to me, it still seems as though a high priority is given to UT login. Also, I suggest putting blank lines between sentences to make the structure of the text clear and readable.

**Comment by jonathanjuursema** [comment]
Along with some other changes to the login screen, I changed the order of the log-in buttons, improved the help text and made the already existing help buttons for Proto accounts more prominent. :)
