### ISSUE TITLE
OmNomCom Supplier Order grouped by category

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#446]
Hi!

Is it possible to group the products on [this page](https://www.proto.utwente.nl/omnomcom/supplier) by category? 
Since the introduction of multiple categories per product, I can image this might result in difficulties.

Thank you for your answer!

**Comment by Peeterus** [comment]
I have now made it so that it groups items by the first category it can find. I hope this is somewhat what you had in mind?
![image](https://cloud.githubusercontent.com/assets/15989311/26325289/9f96a732-3f36-11e7-88fc-0f898162251b.png)
let me know, then I'll change it or put it online!

**Comment by renskruining** [comment]
Yes, I think this will be fine. However, I'll ask the other members of the committee if they can react to this as well.
