### ISSUE TITLE
OmNomCom sales statistics

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#452]
Hi!

For the OmNomCom, it would be helpful if we were to easily see how many items of a product have been sold within a specific time span.

Preferably in an overview of all products on bookkeeping-account 1501, but if necessary on a product's page.

We hope this can be implemented. Let us know if you want more information.
Thanks!

**Comment by Habenga** [comment]
side info/request addendum: 
- a 'from' and 'to' date input box would be more useful than defined 'this week', 'last week' period buttons.
- a  a current stock count in a collum next to sales in specified period would also be useful for out insights.

**Comment by renskruining** [comment]
Hi!
Could this become a priority for the beginning of next year?

**Comment by jonathanjuursema** [comment]
Let's see if we can make this happen over the next weeks.
