### ISSUE TITLE
Upgrade video playback hardware on ProTube machine

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#455]
Every minute or so, ProTube pauses itself and starts playing again after a second or 5.

**Comment by jonathanjuursema** [comment]
We're not quite sure what causes this issue, but we'll look into it.

**Comment by xadya** [comment]
Doesn't work at all at the moment. There is no sound, song is playing though.

**Comment by jonathanjuursema** [comment]
Conclusion till now:
* Sound doesn't seem to be affected, this was just a temporary volume thing.
* **All** screens freeze simultaneously, not only the ProTube screen.
* The freezes seem to happen both when only radio and when YouTube is playing, so it's not necessarily related to ProTube.
* The Windows system logs show no events from crashing devices or whatnot.

This is bound to be an interesting one.

**Comment by jonathanjuursema** [comment]
We now have the money, we need to upgrade the graphics cards in Iris. :)

**Comment by jonathanjuursema** [comment]
It's now WAY better, at a fraction of the cost. :)

Instead of relying on an old unsupported video card, we now rely on USB-VGA adapter to create extra video outputs. This improves the stability of the system up to the point where the freezes are less often and way shorter.
