### ISSUE TITLE
FishCam shows red screen

### ISSUE THREAD

**Issue by chazekamp** [saproto/saproto#456]
The FishCam only shows a red screen. I am using Chrome and had the problem on two laptops.

**Comment by jonathanjuursema** [comment]
It looks like the fishcam is down. This should be fixable with a good ol' _have you tried turning it off and on again?_, and maybe mostly the latter part.

**Comment by thijsdortmann** [comment]
For some reason the fishcam likes to have it's Ethernet plug pulled after powering on, so maybe somebody accidentally powered it off after cleaning the fish tank? If that's the case, just remove the Ethernet cable from the back and plug it back in after a couple of seconds.

**Comment by chazekamp** [comment]
Fixed it! Unplugged the power cable, after that the ethernet plug. Waited a couple of seconds, plugged the power cable back in and after a couple of seconds the ethernet cable.

**Comment by jonathanjuursema** [comment]
Then I'll close the issue.

Please note that while in this instance it doesn't matter much in general please do switch power or (un/re)plug stuff on your own. This can make problems worse without somebody being around to fix it.
