### ISSUE TITLE
When there are no job offers, the website returns an indescript error.

### ISSUE THREAD

**Issue by jonathanjuursema** [saproto/saproto#457]
On the job offer page (https://www.proto.utwente.nl/joboffers/list) when there are no job offers available, the website returns a generic error page without much information. This should be gracefully handled.

**Comment by thijsdortmann** [comment]
For me it doesn't; I get a page telling me there are no job offers, asking me if I want to create a new one. Which error do you get?

**Comment by jonathanjuursema** [comment]
I forgot to add: it's for users without admin priviliges.

**Comment by thijsdortmann** [comment]
Then I'm still not getting any weird errors. `/joboffers/list` is the admin interface, and results in a 403 for people without admin privileges, the non-admin interface `/joboffers` shows a message saying there are no job offers.

**Comment by jonathanjuursema** [comment]
Wow. I have been confusing these two pretty good.

The 403 doesn't have a message though, so the fact it is a 403 is only visible in the HTTP response code.
