### ISSUE TITLE
No participant mail list with tickets

### ISSUE THREAD

**Issue by DennisVinke** [saproto/saproto#459]
At the moment it is not possible to get a list of email addresses of people that bought a ticket for an event. Could this be implemented?

**Comment by jonathanjuursema** [comment]
@saproto/board The e-mail list now includes all people related to an event (participants, ticket buyers and helping committee people) and has been moved to the event admin together with the participant checklist. Note that even in the event admin the e-mail addresses are only visible for the board, not committee members.
