### ISSUE TITLE
'Click here to learn how to report errors!' button on haveyoutriedturningitoffandonagain.nl is not displayed correctly on mobile

### ISSUE THREAD

**Issue by thijsdortmann** [saproto/saproto#460]
The button is too wide and gets cut off. Credits to Antoine Veenstra for pointing this out! Without him we would have never known.

![whatsapp image 2017-05-09 at 21 47 00](https://cloud.githubusercontent.com/assets/7880407/25869640/5ce1c7a8-3501-11e7-8311-ea203367660b.jpeg)

**Comment by bobvandevijver** [comment]
Button is still to wide with certain screen sizes.
