### ISSUE TITLE
The tickets are minimalized after scanning one ticket

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#463]
Is very annoying when scanning multiple tickets..
![image](https://cloud.githubusercontent.com/assets/8876164/25946160/43fa5d0a-364a-11e7-8be3-220df006f2f1.png)
before scanning
![image](https://cloud.githubusercontent.com/assets/8876164/25946175/52dc5f58-364a-11e7-8d19-b477634f182a.png)
after scanning

**Comment by jonathanjuursema** [comment]
We could build an AJAX solution to prevent this.
