### ISSUE TITLE
Quickfixable: Make 'extra info' no show fee a clear button

### ISSUE THREAD

**Issue by margotr** [saproto/saproto#470]
<img width="313" alt="screen shot 2017-05-22 at 14 55 37" src="https://cloud.githubusercontent.com/assets/9929190/26309822/d7b9faca-3efe-11e7-9255-1942b28f2a0b.png">

If you're making an 'additional info' button make sure it looks like a button and not an out-of-place question mark :P. Because this info is very useful and it would be a shame to hide it + it makes the button less pretty than it should be.

Suggestion: a simple circle or something around it should suffice. 

Additional suggestion: If you all are getting annoyed by my quickfixable UI requests, I can also do this myself ;)

**Comment by thijsdortmann** [comment]
Not annoyed, but you're of course always welcome to do a pull request :)

**Comment by thijsdortmann** [comment]
@robi-wan69 Can you provide some design guidance?

**Comment by Janwillemtv** [comment]
There is already a standard icon for these kind of things. Since we are using font awesome: http://fontawesome.io/icon/info-circle/

Example of info-circle a

kind regards,

Janwillem te Voortwis | Creative Technologist
