### ISSUE TITLE
[Feature] Show on the Protube admin page whether protube is toggled off or on

### ISSUE THREAD

**Issue by KaDayKa** [saproto/saproto#482]
It should superfluous because Study Association Proto is an international association, but issues have to be written in English.

Please provide us with enough information to respond to your issue. If you're unsure what this means, please see [this guide](https://github.com/saproto/saproto/wiki/Creating-Issues-101).

Issues with insufficient information will be rejected without a response. Please remove this text before submitting your issue.

**Comment by jonathanjuursema** [comment]
@KaDayKa please next give the right example as a board member and follow the instructions we expect all people to follow...
