### ISSUE TITLE
Flickr album private

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#494]
There are some photos that are liked and favorited more often, to prevent the security of our members' privacy. Can you make it such that album can be on private on flickr?

**Comment by jonathanjuursema** [comment]
@xadya you can now mark albums or part of albums (individual photos) private in Flickr. Our site will still be able to see them and recognize that they should be private. Albums and photos marked as private will only be show to logged in members. This replaces the 'toggle an album private' functionality that existed previously. The Flickr sync will now happen every hour.

There is also a small manual for configuring the Flickr sync for the first time if your access token expires. I will put it on the todo list for the wiki.

**Comment by jonathanjuursema** [comment]
Private photos are by the way also recognizable on the site as such.
