### ISSUE TITLE
Incorporate Alex.IA into the Proto Site

### ISSUE THREAD

**Issue by DennisVinke** [saproto/saproto#496]
While we have a lovely system incorporated to ask Committees to help with events. For drinks however Alex.IA has to be used to make clear to other associations there will be a drink held by Proto, so it would be wonderful if both the Proto and Alex.ia could participate in a good jolly old co-operation. 

My wish for this beautiful symbiotic relationship would be to have an activity made on the Proto site when a new drink is created on Alex.ia, with which the Guild of Drafters is linked to as an assisting committee automatically. 

Thijs already got all the rights I could grant him for Alex.ia. If something does not seem clear or is impossible with the current setup for Alex.ia, I could ask Inter-Actief if they could build/give access or whatever when needed.

**Comment by thijsdortmann** [comment]
There are currently no endpoints to create Alexia events. @DennisVinke: can you check whether these can be created?

**Comment by jonathanjuursema** [comment]
@DennisVinke can you remove the feedback label as soon as the endpoints are available?

**Comment by thijsdortmann** [comment]
Due to a lack of implementation on Alexia's side this will be dropped for the foreseeable future.

**Comment by thijsdortmann** [comment]
Due to a lack of implementation on Alexia's side this will be dropped for the foreseeable future.
