### ISSUE TITLE
Automate calculate profit during a drink

### ISSUE THREAD

**Issue by DennisVinke** [saproto/saproto#497]
Drafters have to fill in the amount of alcohol and other liquids, they used during a drink onto Alex.ia. 

Could you look into and possibly incorporate a function to calculate the difference in the received money and the used goods during a drink?

**Comment by thijsdortmann** [comment]
@DennisVinke: can you check whether they can create API endpoints for getting this data? This is currently not available.

**Comment by jonathanjuursema** [comment]
@DennisVinke can you remove the feedback label as soon as the endpoints are available?

**Comment by thijsdortmann** [comment]
Due to a lack of implementation on Alexia's side this will be dropped for the foreseeable future.
