### ISSUE TITLE
Previous board members complain button return

### ISSUE THREAD

**Issue by pwillems** [saproto/saproto#500]
Dear,

In the previous Proto website we had a button which previous board member (oud bestuur) could use to make Frank automatically say: " Bestuuuuuuur ". In the new website this feature is missing, but how can we now make clear to the board that there is too much noise? 👍 

Would love to have this feature back in the current website. 

Love,
Pim

**Comment by jonathanjuursema** [comment]
This is a duplicate of #247. :(
