### ISSUE TITLE
Make a function on the Proto website to see what achievements are obtained by who 

### ISSUE THREAD

**Issue by HarladusCoenradusKlene** [saproto/saproto#502]
Dear Proto, 

I would like to see a function on the website of S.A. Proto for which I can see who owns what achievement. I see this in a way of clicking the particular achievement and having an overview of everyone that has that achievement. This makes a lot of sense, since I can already see what achievements were obtained by who when I search for someone. With this function it has a much clearer overview.

Kind regards,

Harladus Coenradus Klene II

**Comment by jonathanjuursema** [comment]
I'll close this feature proposal since there hasn't been any expressed interest as per the [guidelines](https://wiki.proto.utwente.nl/ict/issues#special_notes_for_feature_proposals).
