### ISSUE TITLE
Kick In Member Subscription Feature

### ISSUE THREAD

**Issue by jurvangeel** [saproto/saproto#503]
Lief Beheer,

Would it be possible to enable FirstYears that join Proto during the Kick In to also subscribe for ProtoCamp on the spot? 
With something like a button or checkbox in the contactdetails..

Kind Regards 

Jur

**Comment by jonathanjuursema** [comment]
In https://github.com/saproto/saproto/blob/master/config/proto.php#L91-L104 you can now set an event which is considered to be the Kick-In event, and a start and end date of the campaign.

- All people who have a membership starting between the begin and end date of the campaign are considered 'new students'. Any edge cases need to be manually resolved.
- All 'new students' will be shown a banner on the homescreen notifying them of the existence of the camp, along with a link to the camp activity page.
- For this activity, even when sign-up is not open yet, 'new members' can still sign-up. You can thus close the activity for all other members, and have the 'new members' be the only ones able to sign-up during the campaign.
- All of this special behaviour (banner, sign-up override) stops at the end date of the campaign.

I have set some sensible defaults for now. Please open a ticket (or submit a pull request) if you want to have the configuration changed.
