### ISSUE TITLE
Mollie Overview Detailling

### ISSUE THREAD

**Issue by jurvangeel** [saproto/saproto#509]
Lief Beheer,

Would it be possible to allow the FinAdmin to see the date of the transaction under the accounts it belongs to under the month it belongs to in the Mollie overview.

Oke, ik kan dit niet in het engels; als je naar de mollie overview gaat wil ik per maand de transacties kunnen zien zoals dat nu ook kan als je via een withdrawal naar the accounts pagina gaat en van een grootboekrekening per datum kunt zien wat het totaalbedrag is. Hierdoor is het bedrag namelijk nog terug te vinden via Omnomcom orders by date.

Groetjes jur

**Comment by jonathanjuursema** [comment]
@jurvangeel is this still necessary after our discussion yesterday?

**Comment by jurvangeel** [comment]
please do, for jaimy's sake

On Tue, Jul 4, 2017 at 12:26 PM, Jonathan Juursema <notifications@github.com

**Comment by jonathanjuursema** [comment]
Like this?

**Comment by jurvangeel** [comment]
Geweldig
