### ISSUE TITLE
Implement youtube playlists in Protube

### ISSUE THREAD

**Issue by WDeenik** [saproto/saproto#510]
It is quite a hassle to search and add songs independently if you want to add multiple songs (and not just the popular ones) of one artist or genre. 

It would be great if you can enter a youtube playlist ID to just add songs from that playlist (also in the admin). Don't think searching for playlists needs to be implemented (for now), as it already saves so much time, the hassle of finding the ID yourself is not that big of a deal. 

Protube can either just add all songs from a playlist, or present the songs in the playlist as search results (in which case it is the question how to make it possible to add other songs than just the first 50 of the playlist, as protube only shows 50 search results, right?)

**Comment by jonathanjuursema** [comment]
I like the idea. Perhaps the second one (presenting the videos from the playlist as search result) is the most suitable one. @thijsdortmann?

**Comment by thijsdortmann** [comment]
I'll look into it on Monday :) Shouldn't be too difficult.

**Comment by thijsdortmann** [comment]
Fixed in saproto/herbert#dbc7e68881f8097c011cf6cf2df1446ac326dc77 :)
