### ISSUE TITLE
Validate IBAN numbers on change.

### ISSUE THREAD

**Issue by jonathanjuursema** [saproto/saproto#517]
Using perhaps [this super handy toolie](https://github.com/globalcitizen/php-iban).

Note that this would only validate whether the IBAN is correctly formatted (checksum, length, format etc). It would NOT check if the IBAN exists. So this only checks for errors and can easily be defeated by something like [this](https://www.generateiban.com/test-iban/).

**Comment by xadya** [comment]
I heard at Inter-Actief (for example) they automatically check the IBAN, which might be a good idea for Proto as well.

**Comment by jonathanjuursema** [comment]
@xadya how do you mean "check the IBAN"?

**Comment by xadya** [comment]
check whether it's not a fake one & works properly

**Comment by thijsdortmann** [comment]
From what I heard from Inter-Actief they also just do the checks Jonathan is proposing above. I'm not sure if it's actually possible for mere mortals to check whether an IBAN is actually linked to an active bank account.

**Comment by jonathanjuursema** [comment]
You can with an iDeal payment of €0,01. You get back which bank account number has been used in that case.

But I don't think there is another way to verify without involving the user in an active way. That would probably violate some privacy rules.

**Comment by jonathanjuursema** [comment]
Ok, not really closed... Check if we can use this in the background to get BIC: https://openiban.com/
