### ISSUE TITLE
OmNomCom category sorting option

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#523]
Dear all,

I would like to inquire the implementation of a sorting option in the "edit category" page. This way, categories could be sorted by name, price, id, or something else (amount? later implemented things?). This would be awesome!

Thank you!

**Comment by jonathanjuursema** [comment]
This **should** be pretty easily doable, as long as there is no intention to manually sort items in a category. Do you have any intention of wanting that?

**Comment by renskruining** [comment]
Nah, I think it will be fine with existing options (no weird things to
change in or add to the database)

Awesome!

With kind regards,
Rens Kruining

06-46518673

**Comment by thijsdortmann** [comment]
Manually sorting the products within a category has been possible for a long time, it was fixed in  8481e99be050ed735fcb6642798322486c692373. The sorting screen can be accessed by clicking on the category name. Does this cover what you wanted?

**Comment by renskruining** [comment]
Ah yes. It will suffice. 
However, I noticed this does in no way work on mobile. Are there any plans for that?

**Comment by jonathanjuursema** [comment]
It does now!
