### ISSUE TITLE
Weizen achievement issue

### ISSUE THREAD

**Issue by PetervanderBurgt** [saproto/saproto#529]
Hello,

I am writing you on behalf of a issue I heard was present with the weizen achievement.
When someone buys weizen in the AbScInt or MBasement then it would supposedly not be added.
Can you guys please check for this issue if this is present.

Thank you very much,

Peter van der Burgt

**Comment by jonathanjuursema** [comment]
Can you send us a list of people for who this occurs via haveyoutriedturningitoffandonagain@proto.utwente.nl (please do not post names publicly)?

**Comment by PetervanderBurgt** [comment]
Hey Jonathan,
As we discussed there are not specific people having this problem.
This was more of a general thing to look in to if you want a intermezzo from your more serious work ;)

**Comment by jonathanjuursema** [comment]
Wasn't this because the TIPCie uses different beer products than the OmNomCom? If so, the simple solution would be to add both products to the achievement...

**Comment by jonathanjuursema** [comment]
@PetervanderBurgt would it be preferable to have products 211, 758 and 805 counted towards the achievement?

**Comment by PetervanderBurgt** [comment]
@jonathanjuursema If these products would be added to the products that count towards the achievement than it would be perfect :)

**Comment by jonathanjuursema** [comment]
It seems to link to all Weizen variances is already [present](https://github.com/saproto/saproto/blob/master/app/Console/Commands/AchievementsCron.php#L187-L202), so would it still be possible to send us a list of people that report not having the achievement while they should have it? Kthnx. :)

**Comment by jonathanjuursema** [comment]
I'll close this issue until we know receive some names. :)
