### ISSUE TITLE
Resize issue for OmNomCom application on lower resolution

### ISSUE THREAD

**Issue by DennisVinke** [saproto/saproto#530]
On the screens in the drinking rooms of the Zilverling, the names cannot be seen of the people that are younger than 18 years old. Could this be fixed, so people actually see the names with the pictures?

**Comment by jonathanjuursema** [comment]
Bump

We need the resolution before we can do anything.

**Comment by DennisVinke** [comment]
![image](https://user-images.githubusercontent.com/9927347/31441165-a82f7560-ae92-11e7-894d-8331859d8c2b.png)
