### ISSUE TITLE
Omnomcom adding and deleting categories from the application

### ISSUE THREAD

**Issue by PetervanderBurgt** [saproto/saproto#538]
Hello,

Yet another omnomcom issue :) / new feature.
I would like to be able to add and delete categories to the omncomcom and TIPCie application.
I was wondering if this could be done :)

Peter

**Comment by jonathanjuursema** [comment]
I'm sorry but I'll be closing this issue since after thinking about it a little I've found no neat way to implement it easily, and an advanced system seems overkill since (given the rate of pull request for category changes) it's only used a few times per year. Sorry!
