### ISSUE TITLE
Checklist participants event Improvements

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#543]
Dear Have You Tried Turning It Off And On Again committee,

I would like to ask you to improve the existing tool "checklist participants". Preferably the checked members are stored (automatically) for later access. This would also be useful for the treasurer and board to later see which members actually showed up.

Another improvement is to list the people together with their age (or paired with "<18" if that is the case), and allergies if possible.

**Comment by jonathanjuursema** [comment]
@saproto/board @renskruining 

- The participant checklist now only shows people who **participate**, so not those who buy tickets.
- The participant checklist now shows age (18+/-), whether they're participants or helpers and, if applicable, dietary requirements.
- On the participant checklist you can now toggle presence. Please not that this **toggles** presence, so if two people click the link at the same time they revert it back to what it was.
- Presence is **not used anywhere else**, this is only for the participant checklist. For example, also 'absent' participants will still get charged for the activity.

- Presence mangement for ticket buyers can be done, as it already was, via the ticket scanner.
- The event admin page now also shows age and, if applicable, dietary requirements for ticket buyers.
- The list of dietary requirements on the admin page includes both ticket buyers and participants and may show duplicates if a user is both participant and ticket buyer (although this should never happen).

- Both the participant list and event admin have a specific printing style so printouts are legible.
