### ISSUE TITLE
fishcie@proto.utwente.nl receives a lot of spam

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#544]
Dear,

I would like to point out a lot of spam is being received on fishcie@proto.utwente.nl. About twice per two weeks spam comes in on this email address and it is quite annoying. I hope you can help us out.

On some other email addresses, spam is also received (dies@proto.utwente.nl)

**Comment by jonathanjuursema** [comment]
We have a spam filter installed on our server, but as you may know it is very difficult to reliably detect spam without also filtering non-spam e-mail. Most notably, since we're an association, we can be e-mailed by companies who may want to advertise their products to us. These e-mails are properly formatted and authenticated, and are therefore very difficult to distinguish from real e-mails.

You can post some of the message headers of the spam here, so we can see if there's something common we can blacklist. We can not make any guarantees though.

If the problem is really bad you can consider changing your committee alias so you can start with a clean slate, but I assume this is not something you want to do.

**Comment by renskruining** [comment]
If this is what you mean with headers:

Delivered-To: rens.kruining@gmail.com
Received: by 10.202.224.70 with SMTP id x67csp4239956oig;
        Tue, 17 Oct 2017 02:37:28 -0700 (PDT)
X-Google-Smtp-Source: AOwi7QCPGrE+bZk81w1IhxQ4OKuRkoi1q9RQRn/IyXap95VFTcn/h1wBMdWv6ey5+UZ4nTDOHjhM
X-Received: by 10.80.131.98 with SMTP id 89mr16455125edh.66.1508233048117;
        Tue, 17 Oct 2017 02:37:28 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1508233048; cv=none;
        d=google.com; s=arc-20160816;
        b=c3raK7vWi8jpOG4bPL+fXgewWN4uGFYSO2Yqy5FN0WQMj5Iiz6bi7bs8uE6o11Ak26
         s2j0bvI1IfIxf3M2wkocWqacrGpAan6YQKG0ktu+8dfNS38sVsurTm4bD81WlwRGz2Z4
         nH7DYcmE4aNgmlp3q7H4WUO0DILuwUlCRjblcxiRwRVLdkMbeSIQx99NdZfB0kZmactS
         Ve5SrM9kiHp7/0/DAOyCqgi/nOBXmCiGwpBtXiTTJoXQNSmqPR2OZgbBsJ5rnr4/0PYm
         rXjxUf+D8OlDZq6QOGsCrk3zWKGW1XMlF0vrH+2hlJu6eAUzjVbggRg3zo8SoK4sElUR
         DLQA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=spamtally:dkimcheck:blacklistcheck:forward-confirmed-reversedns
         :spfcheck:content-transfer-encoding:message-id:mime-version:subject
         :to:from:date:domainkey-signature:dkim-signature
         :arc-authentication-results;
        bh=usG3scyFSur3zVSXeJxaoPuwH6OoXUEmfQRfcJwZnF4=;
        b=y9gg2fV465UTDzM55tbdH1O6DvLc7XlcoDCYv0L8r6cKIljQ/pYr8HBAdsRUwe0H1f
         iPN8dFtTpUxCqzWOno8I7PGzQbI73cEJqY2c2l/WuQzqGInetgMO/W/no2wRTKlW2BkD
         Rrxz6Vf2xqOBvjX4lfVWSPwEuO+baD6AMs9rinkrGRwT+6DZH8bdUuMF+To7Gsm/68XP
         x4ZU/he18kdSR8gKXhZXnvlxPwak7nze4dBLBXfl3CBlw+WxsVjGOSuLu2pStGGS6utS
         7CDXTIp2/VWcpX5RTwJ+jyV98Zr+FvM/518Any+r8Bt8Fz5Q0H1tbQYOX66WXghHWl0V
         8XsQ==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@lora.wmuz.cn header.s=default header.b=GFvw8h4n;
       spf=pass (google.com: domain of srs0=n7waak=bq=lora.wmuz.cn=sue-382-24249022.lmvlywvolmnvbq-pma-94-1-1879-379-belinda@proto.utwente.nl designates 2a01:7c8:aabc:5c8::1 as permitted sender) smtp.mailfrom=SRS0=n7wAaK=BQ=lora.wmuz.cn=sue-382-24249022.LmVlYWVoLmNvbQ-pma-94-1-1879-379-belinda@proto.utwente.nl
Return-Path: <SRS0=n7wAaK=BQ=lora.wmuz.cn=sue-382-24249022.LmVlYWVoLmNvbQ-pma-94-1-1879-379-belinda@proto.utwente.nl>
Received: from atalanta.saproto.nl (atalanta.saproto.nl. [2a01:7c8:aabc:5c8::1])
        by mx.google.com with ESMTPS id x33si2059638edm.58.2017.10.17.02.37.26
        (version=TLS1_2 cipher=ECDHE-RSA-CHACHA20-POLY1305 bits=256/256);
        Tue, 17 Oct 2017 02:37:26 -0700 (PDT)
Received-SPF: pass (google.com: domain of srs0=n7waak=bq=lora.wmuz.cn=sue-382-24249022.lmvlywvolmnvbq-pma-94-1-1879-379-belinda@proto.utwente.nl designates 2a01:7c8:aabc:5c8::1 as permitted sender) client-ip=2a01:7c8:aabc:5c8::1;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@lora.wmuz.cn header.s=default header.b=GFvw8h4n;
       spf=pass (google.com: domain of srs0=n7waak=bq=lora.wmuz.cn=sue-382-24249022.lmvlywvolmnvbq-pma-94-1-1879-379-belinda@proto.utwente.nl designates 2a01:7c8:aabc:5c8::1 as permitted sender) smtp.mailfrom=SRS0=n7wAaK=BQ=lora.wmuz.cn=sue-382-24249022.LmVlYWVoLmNvbQ-pma-94-1-1879-379-belinda@proto.utwente.nl
Received: from mail by atalanta.saproto.nl with spam-scanned (Exim 4.89) (envelope-from <sue-382-24249022.LmVlYWVoLmNvbQ-pma-94-1-1879-379-belinda@lora.wmuz.cn>) id 1e4OJQ-0007Lg-7g for fishcie@proto.utwente.nl; Tue, 17 Oct 2017 11:37:26 +0200
Received: from lora.wmuz.cn ([103.234.52.158]) by atalanta.saproto.nl with esmtp (Exim 4.89) (envelope-from <sue-382-24249022.LmVlYWVoLmNvbQ-pma-94-1-1879-379-belinda@lora.wmuz.cn>) id 1e4OJP-0007LH-Rt for fishcie@proto.utwente.nl; Tue, 17 Oct 2017 11:37:24 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; s=default; d=lora.wmuz.cn; h=Date:From:To:Subject:MIME-Version:Message-ID:Content-Type:Content-Transfer-Encoding; i=belinda@lora.wmuz.cn; bh=QAmnHSnxPQ+5tEOtRN+VY6dCcrk=; b=GFvw8h4n9qZqgyi2/ueAayfNswvShYJIfs1WrPMFOWJJy6YOzEn6ARx659ueRxEdl+8r4Oso+XwR
   74+ELPFELCTy6f7f9iAYdwvlNARgiufid3TNza2c9rIoXUVZBIPLt/+T4bvhoN8mg9Qexd3SOvgc
   s0Zcw0/G7uUIzO0cA5o=
DomainKey-Signature: a=rsa-sha1; c=nofws; q=dns; s=default; d=lora.wmuz.cn; b=N6PRlHcTqJnVfDyKkjSjxWprhSWL4IrOpjEDaLvVqejiiVcPHrT8ueMVn1Vv7Q+qtIDHrdJi7k8p
   Sdf3QfashXz/HN7SQSnPy6+jopjcEXO32VPQy9vvAI0AjZKjR7tYbRIopMWRWrUdY+Jw/O75etRK
   2vjtbR2PHUX0LKVNyN8=;
Date: Tue, 17 Oct 2017 05:37:15 -0400
From: MK <belinda@lora.wmuz.cn>
To: fishcie <fishcie@proto.utwente.nl>
Subject: Hey, have you seen these?
MIME-Version: 1.0
Message-ID: <c37e92e34ed8e9a55c38d154894837d0@lora.wmuz.cn>
X-Mailer: Fmail 1.8[en]
X-Mailer-LID: 65
X-Mailer-RecptId: 24249022
X-Mailer-SID: 379
X-Mailer-Sent-By: 1
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: 8bit
SPFCheck: Server passes SPF test, -30 Spam score
Forward-Confirmed-ReverseDNS: Reverse and forward lookup success on 103.234.52.158, -10 Spam score
BlacklistCheck: Blacklisted address, +50 Spam score
X-DKIM: signer='lora.wmuz.cn' status='pass' reason=''
DKIMCheck: Server passes DKIM test, -20 Spam score
X-DKIM: signer='belinda@lora.wmuz.cn' status='pass' reason=''
SpamTally: Final spam score: -30


Delivered-To: rens.kruining@gmail.com
Received: by 10.202.224.70 with SMTP id x67csp4680099oig;
        Tue, 17 Oct 2017 10:37:44 -0700 (PDT)
X-Google-Smtp-Source: AOwi7QAJUhVgx9P/RM1arfc6y4txt1NNZ/xZWrl2WqFL5raZqpbo1Acz72fy4lMTqtVMHK4gt02t
X-Received: by 10.80.146.98 with SMTP id j31mr18208556eda.298.1508261864793;
        Tue, 17 Oct 2017 10:37:44 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1508261864; cv=none;
        d=google.com; s=arc-20160816;
        b=aUQOr9t01z5gFxiUjv8dHqK/O5nk+krASUbNOW1oh1FsrKEoAErXwocpDqcniE9Ld0
         nbT5u687Qe1KOQT3WFnWvMpJvXqQ0y60a6Od9yUPz0G6ln8b030lXerKhHO0V/G1YoNg
         aXkdM8R1T76JjbM5lWiTMl0m3mxlH9TQRL/iSybz022QmWYt1bX0Wbxc5clVB6aAuAjy
         xU9JazpJOLKsOF9jte14pEAQDtIAtiq6IOWI0PXxJDH0nz5UNcyQdgf8Vg2OzNyQzDpv
         iOROrF3N2t/EHvV0HRw8OQAWb3bbTaJc/0rhlGit5ygxwwdpzi+CznPCOLf+OJCtItfj
         aA1Q==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=spamtally:dkimcheck:blacklistcheck:forward-confirmed-reversedns
         :spfcheck:content-transfer-encoding:message-id:mime-version:subject
         :to:from:date:domainkey-signature:dkim-signature
         :arc-authentication-results;
        bh=La9XeY3F95J0qUHWipGyObaUWMeU93pcdJSjYiUdxUg=;
        b=qgcc3UQ1NxC7LhnMuvDEqIjpyPd1DzI91cwaDcNJeD5u16+jROgtFojSt78xgbylH1
         /uQRAYIJ3uOcdNTi/R5qC9t+EKECSbPS0gz5Vm8hbSiV0aS5n0R0+zdk07f6gp+iYErC
         4s/YdSQR+HmG9IsP3RqNbdPIucn2bG/hBpCNl57XITHKw59JyROuTn7Oi1idaiuqurQN
         kmel12o7GfIfM433N+T3xoCv1pejKlapPwKj2jKlE1t8EnktEgmRYgdWEmcTq7OIHH8r
         vTztMEQQoizvra7K4/FTmndcDj1FYh5eLZROpoKFoNAmy6dXNBeDNv6TbPAEUc+nnv61
         UFag==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@jijian.itroye.com header.s=default header.b=d+8Yrj2i;
       spf=pass (google.com: domain of srs0=2l1i4h=bq=jijian.itroye.com=nkn-278-15189001.lmjqzwzmzs5jb20-pm-1-0-1555-272-berthae@proto.utwente.nl designates 2a01:7c8:aabc:5c8::1 as permitted sender) smtp.mailfrom=SRS0=2l1i4h=BQ=jijian.itroye.com=nkn-278-15189001.LmJqZWZmZS5jb20-pm-1-0-1555-272-berthae@proto.utwente.nl
Return-Path: <SRS0=2l1i4h=BQ=jijian.itroye.com=nkn-278-15189001.LmJqZWZmZS5jb20-pm-1-0-1555-272-berthae@proto.utwente.nl>
Received: from atalanta.saproto.nl (atalanta.saproto.nl. [2a01:7c8:aabc:5c8::1])
        by mx.google.com with ESMTPS id 36si626039edf.43.2017.10.17.10.37.43
        (version=TLS1_2 cipher=ECDHE-RSA-CHACHA20-POLY1305 bits=256/256);
        Tue, 17 Oct 2017 10:37:44 -0700 (PDT)
Received-SPF: pass (google.com: domain of srs0=2l1i4h=bq=jijian.itroye.com=nkn-278-15189001.lmjqzwzmzs5jb20-pm-1-0-1555-272-berthae@proto.utwente.nl designates 2a01:7c8:aabc:5c8::1 as permitted sender) client-ip=2a01:7c8:aabc:5c8::1;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@jijian.itroye.com header.s=default header.b=d+8Yrj2i;
       spf=pass (google.com: domain of srs0=2l1i4h=bq=jijian.itroye.com=nkn-278-15189001.lmjqzwzmzs5jb20-pm-1-0-1555-272-berthae@proto.utwente.nl designates 2a01:7c8:aabc:5c8::1 as permitted sender) smtp.mailfrom=SRS0=2l1i4h=BQ=jijian.itroye.com=nkn-278-15189001.LmJqZWZmZS5jb20-pm-1-0-1555-272-berthae@proto.utwente.nl
Received: from mail by atalanta.saproto.nl with spam-scanned (Exim 4.89) (envelope-from <nkn-278-15189001.LmJqZWZmZS5jb20-pm-1-0-1555-272-berthae@jijian.itroye.com>) id 1e4VoD-0003iP-SC for fishcie@proto.utwente.nl; Tue, 17 Oct 2017 19:37:43 +0200
Received: from jijian.itroye.com ([172.247.207.40]) by atalanta.saproto.nl with esmtp (Exim 4.89) (envelope-from <nkn-278-15189001.LmJqZWZmZS5jb20-pm-1-0-1555-272-berthae@jijian.itroye.com>) id 1e4VoD-0003iL-Kn for fishcie@proto.utwente.nl; Tue, 17 Oct 2017 19:37:41 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; s=default; d=jijian.itroye.com; h=Date:From:To:Subject:MIME-Version:Message-ID:Content-Type:Content-Transfer-Encoding; i=berthae@jijian.itroye.com; bh=yNXoFhTmzRWB+Fd4t096pCjUiMo=; b=d+8Yrj2iz2dvXG+Q6uqFgfAJyo5qg7UeGU0YBxMkFpI6rmc6yWKpASdFh9M+m5DGeTf2b5IZxOkX
   L+Pp2MMfF7LTupAnE7ISz3S6tO4fTPfRS3j1ECinls/O/c4GhHoH+J6oAOZ1FWj1ZlvIOi+v4h6a
   j27GC2WerXQuoynYp8o=
DomainKey-Signature: a=rsa-sha1; c=nofws; q=dns; s=default; d=jijian.itroye.com; b=am51qkzKjonkBHUMYLSxlOV7bLWXrd/znv4fH6dLPx1v8D6UYyC/A4bl263aCW3ASJeIff0p2WuJ
   rXfNBodQ7U5tm6q2L1hPG2OispYEo2kWyYWQSIhr+ZENpQcqTGTvUW/DYMPvYmICZYb7HRCx3up7
   vW6WczKVv9xnwAYhiyY=;
Date: Tue, 17 Oct 2017 13:36:23 -0400
From: MichaelKors <berthae@jijian.itroye.com>
To: fishcie <fishcie@proto.utwente.nl>
Subject: Don't miss out! Extra 90% off clearance
MIME-Version: 1.0
Message-ID: <6939e09289ede9255a1c7e0c9a6b0046@jijian.itroye.com>
X-Mailer: Gxmail 1.6[en]
X-Mailer-LID: 61
X-Mailer-RecptId: 15189001
X-Mailer-SID: 272
X-Mailer-Sent-By: 1
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: 8bit
SPFCheck: Server passes SPF test, -30 Spam score
Forward-Confirmed-ReverseDNS: Reverse and forward lookup success on 172.247.207.40, -10 Spam score
BlacklistCheck: Blacklisted address, +50 Spam score
X-DKIM: signer='jijian.itroye.com' status='pass' reason=''
DKIMCheck: Server passes DKIM test, -20 Spam score
X-DKIM: signer='berthae@jijian.itroye.com' status='pass' reason=''
SpamTally: Final spam score: -30


Delivered-To: rens.kruining@gmail.com
Received: by 10.202.224.70 with SMTP id x67csp770303oig;
        Thu, 5 Oct 2017 11:06:34 -0700 (PDT)
X-Google-Smtp-Source: AOwi7QCcXkgJryyeWueBG7QY1alacsZPc0hMJJxf9l0ZtFI5o7PrAUMoaF7VeB+Yz5g1MDzexzEy
X-Received: by 10.80.183.193 with SMTP id i1mr699567ede.167.1507226794502;
        Thu, 05 Oct 2017 11:06:34 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1507226794; cv=none;
        d=google.com; s=arc-20160816;
        b=pDdMgFc8iXNGTUb26KM42G9fKgQaVFcpB4rE6ZDNws0ZrN85Uww5+QQ1F/kUavdKyk
         bpEZRP+wXoWzmD0LxqwjrOAE7g1Zn9CvEPdip46iqxwP8h6rj0F7PK7hYZYcxdZrqvNK
         0x9XZupaTJwM5U1NZxSc6uMGzPBkfkjVQWl8Vte8CIgvdY1Ha+jNc1PlMuPObV8ZXRKo
         NW1gtHRLz07i6NXyzsX9972g7fYHWVbPlMlEe9IvndaGjwAtgfyIwoy1bzyycNS/3w/W
         eHfijiN9H3L/dSLrkAoPOJl/kyOQ4YAx4mcBo9nDtwGeBMbmuilSgAwXXDI+yEOPLe1n
         Onpw==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=spamtally:dkimcheck:blacklistcheck:forward-confirmed-reversedns
         :spfcheck:content-transfer-encoding:message-id:mime-version:subject
         :to:from:date:domainkey-signature:dkim-signature
         :arc-authentication-results;
        bh=2RufIW5PQA2yBl4dvXORgrv2rTLF03XUTsXU6qN0z+A=;
        b=U5IvpIk2XulMlWGA/RoF4B8qFt/c4zUVTyy4sQSEM2PySF6OZ59bF5ebyNLvsfD5/N
         g9Gt+P8IbB4O9QXg2wBZ61I51jazRjJRUVvwsh+mi6g2TFY/GIIcnFMfn9Q7uLlQC3z4
         Jb061UhVwnH6C4inon/n7DRZtTngYgpbVHRyldLreK2lz4z3MdOnx16z+Xr3AEN4poIb
         B+gRr9DP16bMI1VK85JK0L00rK8l50etkvkcVy7zN0o+uui87Af0slorwvIa3JIKR+9z
         4hBYDDTk0pqzUSEBtov/u5V61I7zIR3RwnXXs0yxnzKJO4IjqCPecFBeD0uFBQJSfmeq
         j8Pw==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@hutai.bashleyb.com header.s=default header.b=RMR/O/LT;
       spf=pass (google.com: domain of srs0=1gusha=be=hutai.bashleyb.com=cujue-269-15622894.lmjlc3rlbgxlyi5jb20-pm-1-0-668-262-bigong@proto.utwente.nl designates 2a01:7c8:aabc:5c8::1 as permitted sender) smtp.mailfrom=SRS0=1GusHa=BE=hutai.bashleyb.com=cujue-269-15622894.LmJlc3RlbGxlYi5jb20-pm-1-0-668-262-bigong@proto.utwente.nl
Return-Path: <SRS0=1GusHa=BE=hutai.bashleyb.com=cujue-269-15622894.LmJlc3RlbGxlYi5jb20-pm-1-0-668-262-bigong@proto.utwente.nl>
Received: from atalanta.saproto.nl (atalanta.saproto.nl. [2a01:7c8:aabc:5c8::1])
        by mx.google.com with ESMTPS id f8si1362906edd.79.2017.10.05.11.06.33
        (version=TLS1_2 cipher=ECDHE-RSA-CHACHA20-POLY1305 bits=256/256);
        Thu, 05 Oct 2017 11:06:34 -0700 (PDT)
Received-SPF: pass (google.com: domain of srs0=1gusha=be=hutai.bashleyb.com=cujue-269-15622894.lmjlc3rlbgxlyi5jb20-pm-1-0-668-262-bigong@proto.utwente.nl designates 2a01:7c8:aabc:5c8::1 as permitted sender) client-ip=2a01:7c8:aabc:5c8::1;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@hutai.bashleyb.com header.s=default header.b=RMR/O/LT;
       spf=pass (google.com: domain of srs0=1gusha=be=hutai.bashleyb.com=cujue-269-15622894.lmjlc3rlbgxlyi5jb20-pm-1-0-668-262-bigong@proto.utwente.nl designates 2a01:7c8:aabc:5c8::1 as permitted sender) smtp.mailfrom=SRS0=1GusHa=BE=hutai.bashleyb.com=cujue-269-15622894.LmJlc3RlbGxlYi5jb20-pm-1-0-668-262-bigong@proto.utwente.nl
Received: from mail by atalanta.saproto.nl with spam-scanned (Exim 4.89) (envelope-from <cujue-269-15622894.LmJlc3RlbGxlYi5jb20-pm-1-0-668-262-bigong@hutai.bashleyb.com>) id 1e0AXX-0007hn-IH for fishcie@proto.utwente.nl; Thu, 05 Oct 2017 20:06:33 +0200
Received: from hutai.bashleyb.com ([23.225.248.158]) by atalanta.saproto.nl with esmtp (Exim 4.89) (envelope-from <cujue-269-15622894.LmJlc3RlbGxlYi5jb20-pm-1-0-668-262-bigong@hutai.bashleyb.com>) id 1e0AXX-0007hj-BN for fishcie@proto.utwente.nl; Thu, 05 Oct 2017 20:06:31 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; s=default; d=hutai.bashleyb.com; h=Date:From:To:Subject:MIME-Version:Message-ID:Content-Type:Content-Transfer-Encoding; i=bigong@hutai.bashleyb.com; bh=7nkkSH0Mo4Zl21lHcj7RaNrJkkc=; b=RMR/O/LTX1tUSwAaK4tirRX12ZnC70s5upJ7TaR8eNI8tDOw/mkqx0NBpaamjEkt6B2u4ye4wQN9
   9WEI746qSAf2qBXiyLJJsJVGBIbdFa0e5AXX+3qbXbwx38UZ8N6+7a3mvl8DAlN8e1gu/rlrkZbO
   5w7FqSQy53DjdrGxl1g=
DomainKey-Signature: a=rsa-sha1; c=nofws; q=dns; s=default; d=hutai.bashleyb.com; b=UAIp9W1ymW6nWOMrXzIDk+N66RPsG939NqXamXA6YNjaa6LZfDYwIVcLP9Y2DvQPp75g5SeOcEyq
   iFZc5q9CO2dX/2Io46JAZB7Hjj7qYU6hmi6Lkku8CuGTA1i8IPhevJK3ZsI02Yv0sXMyl7wJ+ojx
   8KRyDZz7kiuTq8qh5Os=;
Date: Thu, 05 Oct 2017 14:07:42 -0400
From: MichaelKors <bigong@hutai.bashleyb.com>
To: fishcie <fishcie@proto.utwente.nl>
Subject: You Don't Want To Miss This!
MIME-Version: 1.0
Message-ID: <1f9144c4cea4b1c27ede0a5f5d6d6553@hutai.bashleyb.com>
X-Mailer: Fmail 1.8[en]
X-Mailer-LID: 61
X-Mailer-RecptId: 15622894
X-Mailer-SID: 262
X-Mailer-Sent-By: 1
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: 8bit
SPFCheck: Server passes SPF test, -30 Spam score
Forward-Confirmed-ReverseDNS: Reverse and forward lookup success on 23.225.248.158, -10 Spam score
BlacklistCheck: Blacklisted address, +50 Spam score
X-DKIM: signer='hutai.bashleyb.com' status='pass' reason=''
DKIMCheck: Server passes DKIM test, -20 Spam score
X-DKIM: signer='bigong@hutai.bashleyb.com' status='pass' reason=''
SpamTally: Final spam score: -30

**Comment by jonathanjuursema** [comment]
It seems like our anti spam software was not running on e-mails it forwarded (only on e-mails delivered locally, which we don't usually do). I configured it to also run on forwarded e-mail. However, since the filtering is probably going to have to be done on e-mail content, and that filtering is difficult, I don't expect a large improvement. Please let me know your findings.
