### ISSUE TITLE
Tosti achievement

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#545]
Dear,

We would like to confirm with you that the tosti achievement involves all tosti products (vlam, cheese and regular)

**Comment by jonathanjuursema** [comment]
At the moment these [are included](https://github.com/saproto/saproto/blob/master/app/Console/Commands/AchievementsCron.php#L220-L235).

If people miss the achievement that should have it, please let us know and send us an e-mail with whom it is about. Otherwise I'll close this issue. :)

**Comment by renskruining** [comment]
Cool, thanks, that is exactly what I meant. I will ask, but I don't think
it has gone wrong (yet)

With kind regards,
Rens Kruining

06-46518673

**Comment by jonathanjuursema** [comment]
Then I'll close the issue for now, and reopen it if it turns out there is a problem!
