### ISSUE TITLE
Protube idea

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#550]
I thought it maybe would be a nice idea to include some kind of voting system in Protube. As in, people can add the same song to the queue and it would get prioritized.

**Comment by jonathanjuursema** [comment]
I have two (subjective) objections:

- This can already been done by someone in the room with admin. Does this really happen that often that it is necessary to automate this process for users?
- This way more obscure songs can get pushed to the end of the queue with no hope of being played.

I'm curious to the opinion of the @saproto/board and @saproto/team-herbert.

**Comment by xadya** [comment]
Point 1 I do not agree, since it just members whining to the board again and we should kind of prevent that.
Point 2 is true, but it's still quite some effort to look up the exact same song via protube.

**Comment by sbkoomen** [comment]
While I recognize the original intent of the suggestion, I think it would be too easy for groups of people to completely take over ProTube by combining efforts to get certain songs to the top. Also, the board members currently don't have a lot of problems with people asking for songs to be put at the top.

**Comment by thijsdortmann** [comment]
Everything I had to say has already been said; I agree with Sander and Jonathan.

**Comment by jonathanjuursema** [comment]
Due to the reactions I'll close this feature proposal. You may still petition this at the board together with more people if you believe this to be important though. :)
