### ISSUE TITLE
Linking card using confirmation email

### ISSUE THREAD

**Issue by KaDayKa** [saproto/saproto#551]
The problem I see happening is that people struggle with linking a new card because the touchscreen doesn't work as great as it should, so typing text is a great struggle especially if you can't see what you've typed.
So instead of using your Proto password it might be easier and quicker that you only type your username or email and get send a confirmation mail of linking your card.
This is similar to what Abacus does with their snack system and I found it really easy to link my card.

**Comment by thijsdortmann** [comment]
Can't we just show the RFID ID of the card and make it possible to add it on your dashboard?
