### ISSUE TITLE
Orders via OmNomCom are sometimes entered multiple times

### ISSUE THREAD

**Issue by jaimydk** [saproto/saproto#561]
Some people have experienced that they have paid for food that they did not want to within a couple of seconds. An example is below. 
![image](https://user-images.githubusercontent.com/33654528/32773544-c9f513d8-c929-11e7-8650-68c93fd40a91.png)

**Comment by jonathanjuursema** [comment]
So, is the first order correct, and does it 'accidentally' enter that valid order multiple times, or shouldn't there by **any** orders at all?

**Comment by jaimydk** [comment]
He ordered one pink cake and one beer. So the other orders are not okay

2017-11-14 11:09 GMT+01:00 Jonathan Juursema <notifications@github.com>:

**Comment by jonathanjuursema** [comment]
Should be solved. If it still occurs I don't know why it happens, and we need to investigate deeper.
