### ISSUE TITLE
OmNomCom reset button for board and OmNomCom

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#568]
Hey you 💚

Since the OmNomCom sometimes has some issues, and needs a full reboot at those times, I would like to ask you to try and implement a reset button that reboots the OmNomCom (whole NUC or just the application and rfid-application). This would be better for the NUC as well, since gard resetting isn't what windows likes.

Thank you <3

**Comment by thijsdortmann** [comment]
Server-side part is implemented in saproto/herbert@c984f7e5c84f3a7ff84024d8b936a3e54812fc0f.
