### ISSUE TITLE
Proto Webmail; no data on login

### ISSUE THREAD

**Issue by hesje** [saproto/saproto#570]
L.S.

After loggin in on the Proto webmail (webmail.saproto.nl) round cube is loaded, but shows no emails.
all received and sent emails are not displayed.

**Comment by jonathanjuursema** [comment]
Should be fixed. Problem was [missing JavaScript dependencies](https://github.com/roundcube/roundcubemail/issues/5579).

Also, the webmail now has the Proto address book imported by default, so you can immediately e-mail to members and committees.
