### ISSUE TITLE
honourary members missing on website

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#575]
Dear,

I would love it if I could once again admire our honourary members

**Comment by jonathanjuursema** [comment]
@renskruining and maybe also @saproto/board: how would you like this to look? The honorary members are that for a reason, so what would you like to accomplish/highlight on such a page?

**Comment by renskruining** [comment]
We, the board and I, are discussing it (: further info and requests will probably come from the board

**Comment by jonathanjuursema** [comment]
Sure thing!

**Comment by jonathanjuursema** [comment]
@saproto/board any updates?

**Comment by jonathanjuursema** [comment]
I'll close this issue for now due to a lack of updates. Please reply to this issue if there is any consensus over what the honorary members page should be like.
