### ISSUE TITLE
OmNomCom Database readout to .csv

### ISSUE THREAD

**Issue by Habenga** [saproto/saproto#582]
Dear,

Would it be possible to add a button (on the products page for instance) to down load the current product database status to a .csv file. This would really help with counting/checking the current stock, as well a verify prices and check/analyse other product information in general.

Please include all the information that is also available on the product page (including image link/ref or whether there is an image) of all products in the 1501 financial account.

Cheers!

**Comment by jonathanjuursema** [comment]
There is now an extra button [here](https://www.proto.utwente.nl/omnomcom/products).
