### ISSUE TITLE
Anonymous Protube toggle in combination with user-ban

### ISSUE THREAD

**Issue by QuintenTenger** [saproto/saproto#587]
Could you make a toggle switch that allows ProTube admins to either show or hide the pin required for adding media to the queue to prevent people outside of Protopolis from adding media nobody is actually interested in?

**Comment by jonathanjuursema** [comment]
For full transparency, @thijsdortmann and I think this is not a good idea, but the board voted to have it implemented anyway. We suggested other solutions like disconnecting or banning certain users or IP's, but the proposed solution by Quinten was still the one desired by the board.

**Comment by jonathanjuursema** [comment]
Moving this issue back to a feature proposal because the fine details still need to be discussed by the board. I'm adding @sbkoomen as assignee because he'll organize a meeting where we can discuss this stuff.

**Comment by thijsdortmann** [comment]
After a discussion with @saproto/board we have decided to implement this differently. A toggle will be added which makes logging in to the Proto website mandatory for adding songs to Protube. Additionally, it will become possible to ban certain users for a set amount of time.

**Comment by jonathanjuursema** [comment]
Is currently awaiting the GMM because multiple people have announced they will bring it up.

**Comment by jonathanjuursema** [comment]
This was discussed and rejected by the GMM yesterday, and will thus not be implemented.
