### ISSUE TITLE
TipCie overview in menu, inaccessible for OmNomCom members, but visible

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#589]
Dear,

this button to [TIPCie Order Overview](https://www.proto.utwente.nl/omnomcom/tipcie) is visible for OmNomCom members, but inaccessible.

**Comment by jonathanjuursema** [comment]
You'll have access after the next commit because the OmNomCom already has access to all the data involved in the tool. :)

Please note that the tool is intended for the TIPcie and calculates totals over days ranging from 06:00 to 06:00, not midnight to midnight!
