### ISSUE TITLE
Custom Cookie Monster in the OmNomCom

### ISSUE THREAD

**Issue by PetervanderBurgt** [saproto/saproto#590]
Hello H.Y.T.T.I.O.A.O.A. committee,

I am writing this piece on behalf of Mr. Eversmann and Mr. Steegh.
They would like to add a custom cookie monster in the omnomcom and made the images for them.
They can be found here:
https://drive.google.com/drive/folders/1r6pLwSLCRKQrrGfKf0SMB0n98Fs039H4?usp=sharing

Other Cookie Monsters will be added.

Peter van der Burgt

**Comment by HarladusCoenradusKlene** [comment]
+1

**Comment by jonathanjuursema** [comment]
Please open a new issue for other seasonal OmNomCom monsters.

**Comment by jonathanjuursema** [comment]
[OmNomMonsterhetzijner3trouwens.zip](https://github.com/saproto/saproto/files/1806485/OmNomMonsterhetzijner3trouwens.zip)
