### ISSUE TITLE
S.A. Proto Webmail cannot connect to storage server

### ISSUE THREAD

**Issue by kvogelzang** [saproto/saproto#591]
When I try to log-in to the webmail (https://webmail.saproto.nl/?_task=login), the login fails and I get the error "Connection to storage server failed". I do know that my credentials are correct, since they are remembered by the computer.

**Comment by jonathanjuursema** [comment]
Should be fixed. Please let us know if the problem still persists.

In the configuration we were explicitly disallowing older, vulnerable security protocols. After a service upgrade support for those protocols was apparently removed, which caused our configuration to refer to now nonexistent configuration options, crashing the e-mail storage server. :)
