### ISSUE TITLE
https://wiki.proto.utwente.nl/ has an error

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#592]
Dear,

[This page](https://wiki.proto.utwente.nl/) displays an error:
------
DokuWiki Setup Error

The datadir ('pages') at /home/admin/domains/wiki.proto.utwente.nl/dokuwiki_private/data/pages is not found, isn't accessible or writable. You should check your config and permission settings. Or maybe you want to run the installer?
------

**Comment by thijsdortmann** [comment]
Fixed that :)
