### ISSUE TITLE
Activity sign-up on OmNomCom

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#593]
Dear,

It would be awesome if we, the members of this awesome association, could sign up for activities using the magnificent "Have You Tried Turning It Off And On Again committee"-powered OmNomCom system.

I think they would "act" like normal products in terms of interaction on the screen, with option to view information on the activity.

Many thanks and love,
Frank & Rens

**Comment by sbkoomen** [comment]
@saproto/board likes this idea :) it might be nice to make the tiles for activities a bit bigger on their separate page to be able to properly put in a picture or some text.

**Comment by jonathanjuursema** [comment]
We cannot show if someone already signed up for an activity. How do you figure this limitation in the user flow?

**Comment by renskruining** [comment]
I imagine that when a user tries to sign up, it can show something like "you already signed up"

And then sign out can be done on the website itself.

**Comment by jonathanjuursema** [comment]
@renskruining we can only show that after they've completed their purchase.

Can you provide a complete suggested application flow that we can discuss? :)

**Comment by renskruining** [comment]
@jonathanjuursema of course

The user approaches the omnomcom
(The user clicks a product of choice)
The user clicks an activity
The system shows information on activity (photo big, name, date, time, location, description, signup info, places(available) and a sign-up button in form of "add to cart"
The user clicks "add to cart"-button
The system closes lightbox of activity info and continues as usual omnomcom with activity in shopping cart
The users checks out (in any possible way)
The system shows cookie monster with emphasized message on signup (red of green for example) indicating success or failure and what activity/activities

I hope this conveys my image of the system addition

**Comment by jonathanjuursema** [comment]
And how would you handle multiple activities? Also, most people walk away even before the omnomcom movie starts, so they won't even read the messages. I imagine what you would like to achieve is to provide more exposure to activities, we can also just add cards for activities with the info, without a way to sign-up?

**Comment by renskruining** [comment]
Yes, you have a point, that is why I recommend using a outstanding colour for it, saying:
[Green] **success** you **are** signed up for "crazy sweater party"[/green]
[Red] **failure** you **are not** signed up for "HABHAK": **FULL**[/red]
[Green] **success** you **are** signed up for "handheld workshop"[/green]


However, if it is deemed to be difficult (for user of programming wise, exposure is the next best thing. (Although I imagine questions like "why can't I immediately sign up as well?")
Maybe the addition of qr codes or links to the information lightbox might in that case be interesting

**Comment by jonathanjuursema** [comment]
We'll discuss it tomorrow evening. You can drop by if you like. :)

**Comment by thijsdortmann** [comment]
I think most of these issues can be avoided by just having a 'sign-up' button in the activity pop-up, and doing a separate authentication + submit for signing up.

**Comment by jonathanjuursema** [comment]
@thijsdortmann, @sbkoomen and me discussed this and will not implement this at this time due to the following concerns:

- We wish to avoid the queues during the break to be even longer (due to people reading activity summaries and deciding whether they want to join).
- We would like to avoid adding to many features to the OmNomCom that are already supported on the main site. The OmNomCom is a point of sale for products, we should not make it a 'mini' version of the website.

Sorry. :(
