### ISSUE TITLE
Previous boards page.

### ISSUE THREAD

**Issue by jonathanjuursema** [saproto/saproto#601]
The previous boards page is currently missing for some time and I forget every time it still needs to be implemented. This ticket should be a reminder that we still need a previous boards page, preferably with photo's and some 'bio' like functionality.

**Comment by jonathanjuursema** [comment]
Thijs will discuss with Laura how this will be done because she will be away for a while.

**Comment by renskruining** [comment]
Hello committee,

As a previous board member, I was wondering how this "reminder issue" is doing?

**Comment by jonathanjuursema** [comment]
As discussed, now refers to the board committee page. Shows all previous boards and a photo album is linked with all old board photos. :)
