### ISSUE TITLE
Can we get a 'send reminder' button for assisting committees

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#613]
As chair of an assisting committee, I would find it convinient to have a possibility to send a mail to all committee members when no one signed up for assisting yet. This is mainly since mail is a bit more serious than whatsapp/other form of communication. I do understand the abuse possibilities, so maybe restrict it to only one reminder per activity maximally, or something different of course.

**Comment by jonathanjuursema** [comment]
This is similar to #581 which apparently people were not interested in. If you are going to send an e-mail manually, you can already send an e-mail to your committee e-mail address. I think that rebuilding this functionality in the website will not have much additional use.

I'll close it for now, but if you feel differently please do reply.
