### ISSUE TITLE
Pastries tool

### ISSUE THREAD

**Issue by mindfreek** [saproto/saproto#62]
Can the pastries tool be added to the account of old board members? 
The pastries tool is now only for current board members, and old board members also want some pastry!! :)

**Comment by jonathanjuursema** [comment]
If the e.t. board members would like pastries, that is something we cannot help with. They really need to do that themselves. :)

As for access to the pastries tool, we will not do this for now. Next year, together with the new board, we'll set out a policy for what we want to do with this tool!

Closed for now.
