### ISSUE TITLE
OmNomCom Admin UI: Move delete button to Administration page.

### ISSUE THREAD

**Issue by Habenga** [saproto/saproto#620]
Currently, the only way to delete a product (or category) is to use the delete button in the OmNomCom xxx Administration page (as seen below). This deletion also happens without a confirm popup.
<img width="1266" alt="current location omnomcom xxx administration page" src="https://user-images.githubusercontent.com/9976407/35275086-d0c251fc-003e-11e8-9289-9ab3b89d3505.png">

Can the delete button be moved to the Edit/Administration page of the product or category itself?
(and then also there be an 'Are you sure you want to delete XXXX? [/green: cancel] [/normal: confirm]' popup) 
Like this for instance:(or with the trash icon)
<img width="1306" alt="suggested coaction-catagory administration page" src="https://user-images.githubusercontent.com/9976407/35275106-e44a68ae-003e-11e8-8c8a-81c16b7a2fcd.png">
<img width="1305" alt="suggested location - product administration page" src="https://user-images.githubusercontent.com/9976407/35275107-e4600baa-003e-11e8-9485-01b02dfb4db7.png">

Cheers!
Abel

**Comment by renskruining** [comment]
Hey! I would like to point out the delete button on the edit page returns the user to the (non-existing) edit page after deleting.
