### ISSUE TITLE
Protube remote mobile friendly UI

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#621]
Dear lovely people,

The new protube remote is awesome! However, I would like to ask you if it is possible to change the behaviour of the profile pop up. Hitting back on the phone system UI closes the entire website, instead of the pop up.
Is this possible?

Love!

**Comment by jonathanjuursema** [comment]
[This](https://stackoverflow.com/questions/18997793/javascript-backbutton-event-listener-overrides-the-android-device-back-button) is the result of a quick Google search so it should be possible.

**Comment by thijsdortmann** [comment]
Not as quickfixable as I had hoped :(

**Comment by thijsdortmann** [comment]
As fixing this in a proper way involves quite a bit of work, and this is just a very minor inconvenience, this will not be implemented.
