### ISSUE TITLE
Something to see which activities on the proto-site you are signed up for.

### ISSUE THREAD

**Issue by CChantal** [saproto/saproto#623]
Would be nice to be able see which proto-activities you signed up for so you do not forget to go there or so know you have to sign out if you can not go any longer.

**Comment by jonathanjuursema** [comment]
@CChantal would this be fixed by #630?

**Comment by CChantal** [comment]
Yes, think so!

**Comment by jonathanjuursema** [comment]
Cool, then I'll close this one. :)
