### ISSUE TITLE
Quote corner: add member before the quote.

### ISSUE THREAD

**Issue by Frankieknarf** [saproto/saproto#624]
in the quote corner there is one input field, but often something along the following is entered:
Person x: "[insert Quote here]"

This causes the last quote to have the following formatting:

" Person x: "[insert Quote here]" "

Could there be a new input field for the member involved? This helps with formatting and could clear the way for new functions (e.g. search member for quotes)

**Comment by thijsdortmann** [comment]
Maybe we could implement this in a way where the user submitting the quote can tag one or more members that appear in the quote? That way we can also support quotes where multiple members are interacting.

**Comment by jonathanjuursema** [comment]
I personally think this would make the Quote Corner functionality more complex than intended. If the quotes are truly confusing we should perhaps consider removing the pre-places quotes or making them more obvious a party of the design.

**Comment by xadya** [comment]
I think we should be very careful regarding the gdpr, because this is unnecessary data storage of persons who do not place these data there themselves.

**Comment by thijsdortmann** [comment]
We've discussed this in the committee. Due to the concerns mentioned above by @xadya and @jonathanjuursema, we're not going to implement this.
