### ISSUE TITLE
Text box in newsletter

### ISSUE THREAD

**Issue by sbkoomen** [saproto/saproto#634]
The @saproto/board would like a small text box to send a small piece of text at the top of the newsletter. This could be optional, so if it is left blank there won't be an empty space where the text should be in the newsletter.

**Comment by jaimydk** [comment]
We would like a new text part at the top of the email, so above the activities. The style can be the same as the info of activities boxes. It would also be nice if there is an optional part for a picture is possible. It will mostly be used for small updates about Proto relating to something other then promoting activities. There will most likely not be a lot of text in them.

**Comment by jonathanjuursema** [comment]
There is (very probably) not going to be a way to add pictures. If you need a fancy e-mail with pictures, it's better to send an e-mail via the e-mailing system. We will implement a way to include a small intro with the weekly newsletter though. :)

**Comment by jaimydk** [comment]
Okay that is fine, thanks :)
