### ISSUE TITLE
Thumbnail generation for images.

### ISSUE THREAD

**Issue by jonathanjuursema** [saproto/saproto#64]
All images are now uploaded (and displayed) at full resolution. Need a way to request thumbnails that also caches requested thumbnails.

**Comment by WeeJeWel** [comment]
Take a look at timthumb

**Comment by jonathanjuursema** [comment]
[This](http://stackoverflow.com/q/33384442) stackexchange post recommends [Glide](http://glide.thephpleague.com/) over timthumb.

**Comment by WeeJeWel** [comment]
Cool!
