### ISSUE TITLE
Newsletter mailinglist for news items

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#642]
Dear committee,

I would love for an option to get news items (on the home page and /news) by mail, just like I subscribed to the Proto.ink posts.

xoxo thank you!

**Comment by jonathanjuursema** [comment]
I think this is something the @saproto/board can fix themselves if they see the need to mail members about newsletters. They can either make a new subscribable newsletter where they can send these news items to, or they can just send them over the already existing "General Proto News" list. I'll close this as an issue, and ask you to contact the board about this. :)
