### ISSUE TITLE
Protocard

### ISSUE THREAD

**Issue by Sarah1312** [saproto/saproto#646]
When one prints a protocard, the endproduct is not what it should be. The scaling seems off. This can not be seen when one looks at the preview of the card. 

An example of what I mean is on the desk in the little metal basket. The card of xxx for instance. 

Could someone look at this?

Thank you!

**Comment by jonathanjuursema** [comment]
Please don't post personal information on GitHub, everyone can see this. 🙈 

We'll take a look at this probably on Thursday.
