### ISSUE TITLE
Gmm 25 nit available on the wiki

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#647]
I want to see proto.utwente.nl/page/gmm25 but I get a 404. Can they be online again (soon)?

**Comment by xadya** [comment]
Not*

**Comment by jonathanjuursema** [comment]
The page should be online [here](https://www.proto.utwente.nl/page/gmm25-). Regarding the content, this is something the @saproto/board can fix themselves, please inquire with them regarding the content of the page. :)
