### ISSUE TITLE
Switch entity selection fields to proper elastic search fields

### ISSUE THREAD

**Issue by Habenga** [saproto/saproto#655]
Would it possible to change the name and product field from a drop-down to a search field with drop-down results. This search should search the entire name (so also return vlamtosti when searching tosti) just like the OmNomCom product search and 'Nicename' (and product and student number respectively)

This would make mobile (and pc) use a lot easier.

**Comment by jonathanjuursema** [comment]
I've renamed the issue to something more general, because we should do this with more fields on the site. We'll have to switch to elastic search for more input fields.

**Comment by jonathanjuursema** [comment]
@OmNomCom (@Habenga among others) the "add multiple orderlines" dialog pop-up thing now only shows products in the product dropdown that are set as "visible" to make the list smaller. The new "search field" functionality can be found in the right column.
