### ISSUE TITLE
Helper mails contains wrong link to event

### ISSUE THREAD

**Issue by DennisVinke** [saproto/saproto#658]
The mail with a helper's request is forwarding to the wrong activity

**Comment by jonathanjuursema** [comment]
The bug is confirmed in production but cannot be reproduced outside the production environment. We will investigate further.

**Comment by thijsdortmann** [comment]
The mail queue worker was using the wrong `HASHIDS_SECRET` from the .env file, due to an oepsje on my part. A restart fixed the problem. :)
