### ISSUE TITLE
Event registration through Omnomcom

### ISSUE THREAD

**Issue by Frankieknarf** [saproto/saproto#668]
Would it be possible to add a section with activities for which you can subscribe for events in the OmNomCom? 
I understand that this feature would not support unsubscribing for an event since the identity is only checked during checkout, but I think it would improve promotion of activities. 

Another issue that would arise is that people should not be able to "buy" more than one activity.

**Comment by thijsdortmann** [comment]
This has already been discussed in #593, and it was decided not to implement this.
