### ISSUE TITLE
Achievement for donations

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#671]
Hey hey!

It would be awesome if there would be an automatic achievement for when you've donated X euros to committee Y,
Starting with your first donation, updating for the cumulative amount of donations, specifically to fishcie, or omnomcom, for example.

**Comment by jonathanjuursema** [comment]
This should be opt-in, since I can imagine reasons you don't want to make public how much money you spend on specific Proto stuff. And if it is opt-in, I think it will not be widely used. Let's see if people vote for this idea! Would you opt-in?

**Comment by renskruining** [comment]
Ah, yes, I see the issue. And I agree not a lot of people will opt in, especially with the (growing) amount of opt-in stuff.

Maybe changing it to just "you've donated to the FishCie" instead of specific amount after the first donation would help this concept.

**Comment by daniepyromanie** [comment]
Is this going to be implemented? :3 i think its a very nice achievement to stimulate donating

**Comment by jonathanjuursema** [comment]
This feature is still a proposal and didn't receive a whole lot of votes, so I'm afraid that unless someone is personally interested in implementing it it's not going to be implemented soon. See also [here](https://wiki.proto.utwente.nl/ict/issues#special_notes_for_feature_proposals).
