### ISSUE TITLE
Boardroom calendar on protopolis screen

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#672]
It seems that the boardroom calendar on the screens isempty because it still refers to the old calendar. Could this be updated to the new (Alfred's) calendar

**Comment by jonathanjuursema** [comment]
We're already working on this, but good that you mention! 👍

**Comment by renskruining** [comment]
👌🏻😎

**Comment by jonathanjuursema** [comment]
By the way, we're awaiting feedback from the LISA department, since we cannot access the calendar yet. :)

**Comment by jonathanjuursema** [comment]
Still waiting on LISA feedback by the way. There are some procedural issues which make it that LISA cannot immedeately fulfill our request.

**Comment by jonathanjuursema** [comment]
Will close for now. If we get feedback from LISA we'll look into this again!
