### ISSUE TITLE
Year in title of photo albums

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#678]
It would be nice for all albums to have the year of the event/photos taken as a last parameter in the title. i.e. Short Circuit should become Short Circuit 2016. This mainly for archive puposes and because you can see this on proTube when the images are playing.

**Comment by jonathanjuursema** [comment]
@xadya this was already present for the Photo albums on the photos page on the website. But it is now also in ProTube! Please not that we do not change or automatically update the album name as we get it from Flickr, but we construct an 'album date' based on the date_taken or date_uploaded of the photos in that album and use that album date to display the additional info as well. For the best results, album names on Flickr should thus NOT contain a date. :)
