### ISSUE TITLE
Handyman Committee Team Building activity!

### ISSUE THREAD

**Issue by HarladusCoenradusKlene** [saproto/saproto#680]
Dear Proto,

Because of the fact that I did not know where to submit this proposal, I am doing it via this medium. Wouldn't it be amazing to have an Ikea team building activity for the Handyman Committee? The people participating in this wonderful committee can acquire inspiration for their next big ass project, and play hide and seek while doing so.

Thank you for taking my proposal in consideration.

**Comment by thijsdortmann** [comment]
Hi there! This issue tracker is used by the Have You Tried Turning It Off And On Again committee to keep track of things we have to do and things people want us to do. For this you should contact your board responsible or @saproto/board in general :)
