### ISSUE TITLE
Noun Project API for icons achievement

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#682]
Hey hey!

I just saw a board member making a new achievement, and noticed the choice of icons was quite limited. Now I know [The Noun Project](https://thenounproject.com/) has a vast amount of icons of great quality and I was wondering, since it has an [API](https://thenounproject.com/), if it was possible to use this (and its search engine) for the achievement icons

😙

**Comment by jonathanjuursema** [comment]
I think it's better to switch to the [new fontawesome](https://fontawesome.com/), since there are less licensing issues with those icons.

**Comment by renskruining** [comment]
Ah, yes, I did not know of this, but yes, do whatever suits best d:

**Comment by jonathanjuursema** [comment]
Due to limited time available and other higher priority issues, we won't implement this right now. Sorry. :(
