### ISSUE TITLE
Delete confirmation for orderline history

### ISSUE THREAD

**Issue by daniepyromanie** [saproto/saproto#683]
If you want to delete an orderline via the OmNomCom tools in the proto site you don't get a confirmation question (HELP!). Might happen that you missclick and accidentally delete the wrong orderline.

**Comment by daniepyromanie** [comment]
Heyo I saw that this was closed, but I don't see that it's fixed :'(

**Comment by jonathanjuursema** [comment]
Issue was fixed, but I forgot to put it on live. :(
