### ISSUE TITLE
Specific spam(?) For all committee mails

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#686]
Hey, I hope you've noticed as well, that all committees have received a mail their account is approved.

I hope you know the source of this, 
![screenshot_20180317-084525](https://user-images.githubusercontent.com/9930890/37553043-576179fe-29c0-11e8-9d9f-89bc15e4640b.png)
![screenshot_20180317-084534](https://user-images.githubusercontent.com/9930890/37553041-56fa8f78-29c0-11e8-9081-9b6aacbde7ac.png)
![screenshot_20180317-084556](https://user-images.githubusercontent.com/9930890/37553042-5734b2c0-29c0-11e8-885f-64a42ac23cda.png)
![screenshot_20180317-084610](https://user-images.githubusercontent.com/9930890/37553044-5787814e-29c0-11e8-8a58-f9802e9bd062.png)

**Comment by jonathanjuursema** [comment]
I have personally not yet seen that spam campaign. You can always send the [e-mail headers](https://support.google.com/mail/answer/29436?hl=en) to us for analysis, but I'm afraid there's nothing that we can do. Just keep flagging the e-mails as spam.

Please note that committee e-mail addresses are public, and will eventually receive spam. :(

**Comment by renskruining** [comment]
Sarah also got the same spam mails.

Herewith the entire "original" of one of the mails:
`Delivered-To: rens.kruining@gmail.com
Received: by 10.202.166.219 with SMTP id t88csp72712oij;
        Fri, 16 Mar 2018 14:16:06 -0700 (PDT)
X-Google-Smtp-Source: AG47ELu6uImALBqSvFC+qIWrmYhaYwWs0+dc9P8VZtJtHeQ3ePyB+tAxVt6YvgfQnNaqWNfSOFJI
X-Received: by 10.80.144.54 with SMTP id b51mr268694eda.194.1521234966199;
        Fri, 16 Mar 2018 14:16:06 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1521234966; cv=none;
        d=google.com; s=arc-20160816;
        b=jhKwrQ9/EYfqLdVlj6aLjGSRlMBJzGstjvAzd4D9tlxF0gkvl9EtzK2ku8swU4y8TI
         TPlUiUvTeA9KIOZcRtgwDOHHo15cSGHnGJiLIlIjAqhsVozeOXdznC98Tdwrs4plEBm7
         cIdNBqiVbGhL8JU6sMVgtxU/mHmkPm/DQeFLs3R2/A0y/+iA0JUnSeQ7JOjzTwE8tLeN
         nosbKBfWYHrExu/qFlIOUxeeXKyzPWDf4uSh0n8Wydqte0x6TeAchCgvCSSC6Qfnik5Q
         8KTYFR4HD5aN1KxLJ31ffkfAiw9NoHmhosC2/H1ZE3Te/1To1OE51scAsla5Czvp8AhE
         vOKg==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=spamtally:blacklistcheck:content-transfer-encoding:mime-version
         :message-id:user-agent:reply-to:subject:to:from:list-unsubscribe
         :date:arc-authentication-results;
        bh=y155jyiK4lcyuqYiMJhi/WruNLaz7+Hkh4hNMM5CI2c=;
        b=mgb1SmnToga4AG4hvwbhn/WuqeqtbqaZhjr9ABx13DAz7guzJTYnE3/CslTKi2Shk2
         cIIfhyfoJX83uVJVFwpZi1SGQ4MtYj3drOf6yq3vKENyB4hHClvOoGyfaoGUF108qNod
         EM6xtYEvtLmAXED3NDemT9D4aEgONcFSYJ7hBqRArnuWF30HAWIRQCy7a2pELicdGBck
         9izWj7X3H1p80CRusgOeHIvMm5HHmA2ezcM1w8aPJFTljRtpBQKdBbCoJR/6rhYlumxO
         guj8KA8aQciG2PczBg+dUYH3eE6uHes3nRU+mrvq3XHI2ZKhkdorjox+HeS1xgyZCpXF
         2PbQ==
ARC-Authentication-Results: i=1; mx.google.com;
       spf=pass (google.com: domain of srs0=qtghcv=gg=nl.accapproved.gq=robschulze310@proto.utwente.nl designates 2a01:7c8:aabc:5c8::1 as permitted sender) smtp.mailfrom=SRS0=qTGHcv=GG=nl.accapproved.gq=robschulze310@proto.utwente.nl
Return-Path: <SRS0=qTGHcv=GG=nl.accapproved.gq=robschulze310@proto.utwente.nl>
Received: from atalanta.saproto.nl (atalanta.saproto.nl. [2a01:7c8:aabc:5c8::1])
        by mx.google.com with ESMTPS id q5si665576edh.143.2018.03.16.14.16.05
        (version=TLS1_2 cipher=ECDHE-RSA-CHACHA20-POLY1305 bits=256/256);
        Fri, 16 Mar 2018 14:16:06 -0700 (PDT)
Received-SPF: pass (google.com: domain of srs0=qtghcv=gg=nl.accapproved.gq=robschulze310@proto.utwente.nl designates 2a01:7c8:aabc:5c8::1 as permitted sender) client-ip=2a01:7c8:aabc:5c8::1;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of srs0=qtghcv=gg=nl.accapproved.gq=robschulze310@proto.utwente.nl designates 2a01:7c8:aabc:5c8::1 as permitted sender) smtp.mailfrom=SRS0=qTGHcv=GG=nl.accapproved.gq=robschulze310@proto.utwente.nl
Received: from [2001:4b98:dc2:41:216:3eff:fe44:518] (helo=mx.nl.accapproved.gq) by atalanta.saproto.nl with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128) (Exim 4.90) (envelope-from <robschulze310@nl.accapproved.gq>) id 1ewwhY-0006Kc-FP for omnomcom@proto.utwente.nl; Fri, 16 Mar 2018 22:16:05 +0100
Received: from [127.0.0.1] (mx.nl.accapproved.gq [127.0.0.1]) by mx.nl.accapproved.gq (Postfix) with ESMTP id C68597515C for <omnomcom@proto.utwente.nl>; Fri, 16 Mar 2018 22:15:43 +0100 (CET)
Date: Fri, 16 Mar 2018 21:15:43 +0000
List-Unsubscribe: <http://nl.accapproved.gq/unsubscribe.php?u=VGU5bUMrUWw5WjJiRTFlU0tkblUyWXZjRlBLTlhobk9GcmpZcWxETUNhbkNwQWFlYzRiWFozMlpPRnMwNlAxeUtmeFdpdWdFbGFCZVBYSmhhSXVNOFE9PQ==>, <mailto:postmaster@nl.accapproved.gq?subject=9NxIgZw2oz5Qt4MRVDbmrqH8JWCUdsT3>
From: Customer Service <robschulze310@nl.accapproved.gq>
To: omnomcom@proto.utwente.nl
Subject: 👍 Account Approved - omnomcom@proto.utwente.nl
Reply-To: <robschulze310@nl.accapproved.gq>
User-Agent: CodeIgniter
X-Sender: robschulze310@nl.accapproved.gq
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: <5aac33ffc0ce5@nl.accapproved.gq>
Mime-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
BlacklistCheck: Blacklisted address, +50 Spam score
X-Spam-Score: -1.1 (-)
X-Spam-Report: Spam detection software, running on the system "atalanta.saproto.nl", has NOT identified this incoming email as spam.
  The original message has been attached to this so you can view it or label similar future email.
  If you have any questions, see the administrator of that system for details.
  Content preview:
  Hello. Good news! Your account has been approved! Your Email:
    omnomcom@proto.utwente.nl Date: 03/12/2018 Account ID: UZEBCJAE Password:
    d5EiAQ [...]
   Content analysis details:
   (-1.1 points, 5.0 required)
   pts rule name
              description ---- ---------------------- -------------------------------------------------- -1.9 BAYES_00
               BODY: Bayes spam probability is 0 to 1%
                             [score: 0.0000]
  0.8 RDNS_NONE
              Delivered to internal network by a host with no rDNS
SpamTally: Final spam score: 40


Hello.
Good news! Your account has been approved!

Your Email: omnomcom@proto.utwente.nl
Date: 03/12/2018

Account ID: UZEBCJAE
Password: d5EiAQ

You can log in now and start using your account!
http://nl.accapproved.gq/account/KU2dFIlApqHWkt

Have a good day!
--
Rob Schulze
Customer Service
`

**Comment by jonathanjuursema** [comment]
From the headers I gather that (unfortunately) our mailing systems have not tagged the mail as spam, partly because the sending of the e-mail was well authenticated (for example SPF was in order). We could contact the sender network in France, but I'm not sure that it'll be of much help because similar of our previous attempts did not resolve anything. Also, from the screencaps I gather that Google did tag the mail as spam, so you should also not have received it in the inbox. It is very difficult for us to filter this kind of spam accurately because it takes sophisticated content-based filters we simply do not have. :(

Is there, at this point, anything specific you would like from us?

**Comment by renskruining** [comment]
No, I think it is okay. I just wanted to make sure you were aware mails for "accounts" for all committees came in.
