### ISSUE TITLE
Page for video's 

### ISSUE THREAD

**Issue by marloes21** [saproto/saproto#690]
Have a video album page so we can see all the after movies

**Comment by jonathanjuursema** [comment]
@saproto/board if you're interested, in preparation for this issue, could you make a YouTube playlist using the S.A. Proto board (Google) account with videos we should include on this page?

**Comment by xadya** [comment]
@saproto/board I think I did collect all videos some time ago, if you like this idea I can take a look together with videography :)

**Comment by jonathanjuursema** [comment]
Input from the committee meeting:

- We'll make a seperate "video database" where people can add individual video's by, for example, a YouTube ID.
- Video's can be linked to an activity, which will make that video listed next to that activity's photos.
- There will also be a central video gallery, with all videos.
- Perhaps also a 'latest video' on the homepage.
