### ISSUE TITLE
Handyman Proto-Wiki page

### ISSUE THREAD

**Issue by emielsteegh** [saproto/saproto#693]
The Handyman committee needs a good way to keep people posted on the projects we accept and are currently working on.

A way we thought would be good to do this in is via a handyman project page on the Proto wiki, this page would need to be editable by Quinten and Emiel at least, but if others in the committee can edit as well this is best (dunno how those privileges work). Ideally if there is a comment feature it would be nice if people could submit digital requests under the page?

If you have a better/more fitting solution that is fine aswell!

Emiel

**Comment by jonathanjuursema** [comment]
Hey! Cool that you want to use the wiki for this! I'll give some info below, but don't forget to also familiarize yourself with how DokuWiki works. You can also drop by Tuesday evenings if you have questions.

[If created a namespace for your committee](https://wiki.proto.utwente.nl/handyman/start). Within that namespace, all members of Proto can edit everything (there's not really a comment functionality and most plug-ins seem to be too complicated for what you want to do) so you can give updates and other uses can give comments on those projects. I propose that you make one page per project, and keep the start page as an overview page.

If you want, I can lock down the start page so only the handymen can edit them (giving access to the entire committee is easier than adding users one by one 😄). If you want, I can also give you a private internal wiki namespace (something like /handyman/private) that is only accessible for you that you can use for notes. If you want either of these, or something else, you can reopen the issue. :)
