### ISSUE TITLE
wiki breadcrumbs to hierarchical

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#701]
Dear committee,

I would be forever grateful to have the dokuwiki breadcrumbs be set to hierarchical. It is explained here:
[DokuWiki Breadcrumbs](https://www.dokuwiki.org/breadcrumbs)
(disclaimer, don't visit on april 1st unless you want to make it harder on yourself😘)

**Comment by jonathanjuursema** [comment]
There you go!
