### ISSUE TITLE
Optional extra description textbox for orders

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#705]
Hi! 

It would make things much more explained if orders (for products such as "dinner costs €8,-") could have an extra description (such as "studynight 11-april-2017").

I think this would be advantageous for both members, omnomcom and board.

Thank you <3

**Comment by renskruining** [comment]
Hey committee, 

since you've had a meeting last night (or so I heard), I was hoping you could give me an update for this issue.

**Comment by jonathanjuursema** [comment]
This is already a `to-be-implemented` issue, so we'll implement it as soon as we have time! :)

**Comment by renskruining** [comment]
ah cool, I'm looking forward to it!
Thabk you!

**Comment by jonathanjuursema** [comment]
Please note that descriptions cannot be changed via the website after they have been submitted. Descriptions can only be added via the advanced orderline add.
