### ISSUE TITLE
Activity participation survey for activities like HABHAK

### ISSUE THREAD

**Issue by TomOnderwater** [saproto/saproto#712]
Hi HYTTIOAOAc,

When doing my duties as fish deliverer, I notice that sometimes it is difficult to decide what sauces or sizes of kibbeling I need. Would it be possible to make an addition on the HABHAK page where people could choose their sauce of choice and can say whether they would like a large or a small portion of Kibbeling.

It is just an idea, but it should remain easy to order kibbeling!

-Tom

**Comment by jonathanjuursema** [comment]
We could tie some sort of survey to an activity participation to make it more generally applicable to other activities. However, this does require quite some work. If there are other committees interested in this feature, please [convince them to upvote this issue](https://wiki.proto.utwente.nl/ict/issues#special_notes_for_feature_proposals) so we know where to put it on our priority list. :)
