### ISSUE TITLE
Contact SNT regarding contract and data processing agreement.

### ISSUE THREAD

**Issue by jonathanjuursema** [saproto/saproto#725]

**Comment by xadya** [comment]
Hallo Xadya,

Met de verwerkersovereenkomst zijn wij bijna klaar, ik verwacht deze
morgen te kunnen publiceren/opsturen. Het contract is er helaas de
afgelopen tijd bij ingeschoten, dus ik weet niet zeker of mij dat deze
week nog gaat lukken.

-- 
Met vriendelijke groet, kind regards,

Willem Mulder
Secretaris

**Comment by xadya** [comment]
Is there!
