### ISSUE TITLE
Bigger/Full screen menu on mobile

### ISSUE THREAD

**Issue by margotr** [saproto/saproto#730]
On mobile, the menu is hard to use because the items are quite small. Is it an idea to make the menu bigger/full screen?

<img width="380" alt="screen shot 2018-05-20 at 15 17 47" src="https://user-images.githubusercontent.com/9929190/40279337-065606f2-5c41-11e8-80d0-a99453a33847.png">

**Comment by xadya** [comment]
We unfortunately do not have time for this :(
