### ISSUE TITLE
Is it possible to get a participating indicator?

### ISSUE THREAD

**Issue by monjainox** [saproto/saproto#731]
Hello!

When I am on the calendar page of the Proto website I can overview all upcoming activities but if I want to check for which ones I am enrolled I have to click all of them separately. I am wondering if it might be possible to indicate if you are participating just by looking at the calendar page so you don't have to like all individual events. I was thinking a green check next to the title, the event block could be green etc.

Thanks in advance.
Puck

**Comment by xadya** [comment]
To add on this, Emiel and I were thinking that it might be nice to also indicate here whether a helper has been found or is still being searched for with such an indicator.

**Comment by monjainox** [comment]
Maybe the helper could be something like: Protographer 0/1 or with an icon

**Comment by xadya** [comment]
Yeah, we thought about a green or red icon of the committee and no icon when not needed. Same can go for participating, icon if going only. But maybe @saproto/board (or candidate board) would also like this for ERO ?

**Comment by sbkoomen** [comment]
Maybe a tick for participating, a camera for Protography help needed, and a plus sign for EmergenCie help needed? The camera and plus sign could only be for members of the specific committees and the board.

**Comment by jonathanjuursema** [comment]
What would you do for other assisting committees? Such as the organizing committee, GoD, video? I think perhaps it gets a bit too busy. You get the activities you help with in your personal agenda. Perhaps one icon for participating, and one for helping in general?

**Comment by xadya** [comment]
There are only three via the Proto site: photo, video and ERO and one for joining in general I think :)

**Comment by jonathanjuursema** [comment]
We made it explicitly so that you can make any committee an assisting committee, which is something used by for example the [FishCie to indicate which person is going to get the HABHAK](https://www.proto.utwente.nl/events/4z62BYmnBGmKvE08). I would prefer to implement one solution that covers all helping committees immedeately, to prevent additions later on as use cases change.

**Comment by sbkoomen** [comment]
In that case, wouldn't it be easier to create a separate page with a list of events, where every event has a sub-list of required committees in list form?

So for instance:

HABHAK                              <date, time>
   - FishCie: 5
   - Protography: 1
   - EmergenCie: 2

Dies Pie Baking Contest    <date+time>
   - Protography: 1
   - EmergenCie: 3

**Comment by jonathanjuursema** [comment]
You will now get:

- A checkmark if you participate.
- A 'help' icon if you are helping.
- A ticket icon if you have bought tickets.
- An exclamation mark if the activity needs help AND you can actually provide that help.
