### ISSUE TITLE
Protube pixel of video under queue bar

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#737]
Hi!

We just discovered a protube video can be seen beneath the (empty) queue bar, just a single pixel or so.
Once you've seen it, it can't be unseen.
Maybe the bar should go one pixel mor down d:

It has only been noticed with the screen near the omnomcom (protopolis 1).

A weird bleed effect has also been noticed on the same screen with photos scrolling downwards

**Comment by jonathanjuursema** [comment]
The issue seems to be gone. I cannot see it in any case, and neither could several other people in the Protopolis. Perhaps I accidentally fixed it earlier. 😛
