### ISSUE TITLE
Explanation in footer for mails to all active members

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#744]
Dear,

Since there are many different newsletters and mail subscription options, It would be awesome if mails indicated which subscription or what group is addressed.

"You're receiving this mail because you're subscribed to X"
or
"You're receiving this mail because it's addressed to all active members"
for example.

**Comment by thijsdortmann** [comment]
Maybe I'm not understanding your issue correctly, but isn't this already happening? Below the newsletter sent today, for example, the following is shown:

<img width="696" alt="screen shot 2018-06-05 at 13 56 36" src="https://user-images.githubusercontent.com/7880407/40974609-5bbe80c2-68c8-11e8-8aa6-8fe675a3b492.png">

**Comment by renskruining** [comment]
Ah, that may be so. I just noticed it with the mail Sander sent regarding the active member activity. I assume this is sent using the mailing tool, and sent to all active members or something.

**Comment by thijsdortmann** [comment]
I just checked, and it looks like the active members list is the only thing not included in the list of possible explanations for why a mail was sent. For generic mails sent to a list, this is already happening, as well as for mails sent to all members, all users and event participants (see https://github.com/saproto/saproto/blob/master/resources/views/emails/manualemail.blade.php). An explanation for active members should be added.

**Comment by renskruining** [comment]
ah, okay, I just managed to notice the exception, I guess.

Thanks!
