### ISSUE TITLE
Omnomcom csv, enter pl0x

### ISSUE THREAD

**Issue by PetervanderBurgt** [saproto/saproto#754]
Hello,

As i have disturbed you quite some times for the omnomcom already, I thought that once more would probably settle it :p.
It would be amazing if the export CSV could have new lines for every product line.
Thanks in advance.

Kind regards,

Patoer

**Comment by MartijnVerkleij** [comment]
I would like to reopen this issue, as the newlines still do not seem to be present. In the raw content they are present, but the presence of HTML codes makes it harder to work with.

The easiest solution I can see is wrapping the content in a bare html file, in a `<pre>` environment. 

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>OmnomCom Bulk Order %DATE%</title>
  </head>
  <body>
    <pre>
      %CSVDATA%
    </pre>
  </body>
</html>
```

**Comment by jonathanjuursema** [comment]
Is this still relevant?

**Comment by MartijnVerkleij** [comment]
Current implementation has been working great! Thanks!
