### ISSUE TITLE
Failed Direct Withdrawal mail typo/error

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#765]
Dear,

I just received a mail about a failed direct withdrawal and I noticed a parentheses ")" in a spot I didn't expect it. Is it part of the mail, a script or my bank details?

![screen shot 2018-08-07 at 13 23 08](https://user-images.githubusercontent.com/9930890/43773408-eb383cf8-9a45-11e8-8bb5-7215628dee18.png)

Thank you!

**Comment by jonathanjuursema** [comment]
It was a mistake in the e-mail template, probably the result of seeing what the best phrasing of the message was.
