### ISSUE TITLE
Dilemmarama poll-voting toolie under ''For Members'' section

### ISSUE THREAD

**Issue by PhilippeTu** [saproto/saproto#766]
Hey HYTTIOAOA-committee,

As some of you have heard I would like to implement something called Dilemmaramas (Dillemma-Op-Dinsdag) next year in the weekly newsletter. Jonathan suggest building this into the Proto-website as a voting system, like a poll.
This sounds great! 
My vision for this is as follows: I introduce the new Dilemmarama every week in the Newsletter, including a link to the poll on the Proto-website. People are then able to vote throughout the week on their favourite. Also I could write a small piece of text discussing the results of last's week Dilemmarama. 
For now I think the shareable link on the Proto-website to the poll would suffice, however it would be great is more additions could be made so it'd be easier for me to implement it in the newsletter of each week. Even a button for people to suggest Dilemmarama topics would be great!

**Comment by PhilippeTu** [comment]
Any updates? :D

**Comment by jonathanjuursema** [comment]
It's still scheduled for implementation, but we unfortunately haven't gotten around to it because of limited time and other higher priority issues.

**Comment by PhilippeTu** [comment]
Check, thanks for the update! :)

**Comment by thijsdortmann** [comment]
We will look at this later on when we have more time.
