### ISSUE TITLE
Linkt to social media accounts on the site.

### ISSUE THREAD

**Issue by PhilippeTu** [saproto/saproto#768]
More a suggestion: Would be nice to have Proto's socials linked somewhere, I believe we have Facebook, Youtube, LinkedIn and now also Instagram.
I think it'd be fine if we were to put them somewhere along the bottom, doesn't need to be obnoxiously at the top of the website ;P

**Comment by jonathanjuursema** [comment]
If you give use the links we might find time to  take on this daunting task. :)

**Comment by PhilippeTu** [comment]
Free vector icons if needed:
https://www.flaticon.com/search?word=social%20media

https://www.facebook.com/groups/SAProto/
https://www.youtube.com/channel/UCdH2x3ObOrmLdm2OOGDBslw
https://www.linkedin.com/company/s-a-proto/
https://www.instagram.com/s.a.proto/

**Comment by jonathanjuursema** [comment]
We have [fontawesome](https://fontawesome.com/v4.7.0/icons/)!

**Comment by jonathanjuursema** [comment]
(Renamed title to English)
