### ISSUE TITLE
Activity overview

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#77]
Hey!

It'd seem that the treasurer might be the only one using the existing activity overview.
If it'd developed again, I'd change it according to the following to have a certain use for the treasurer:

At the moment, I use the overview to see what activities should still be closed, making it easier to know what committees to ask for activity accounts. 
The following would have a super addition to the page:better info on activities: the date of the actual activity, when it has been closed, the dates of registration opening and closing (:

**Comment by jonathanjuursema** [comment]
We currently don't record the date on which an activity was closed (we don't have that data for old activities either). Would you really be interested in closed activities as well or is an overview of still to be closed activities be enough?

**Comment by renskruining** [comment]
Overview of closed activities would be fun (having a vast amount of awesome activities on screen), but main focus should be on open activities c:
