### ISSUE TITLE
Online dinnerforms

### ISSUE THREAD

**Issue by maximdeleeuw** [saproto/saproto#776]
Ghello,

Dennis and I were talking about dinner forms during the drinks. Is there a possibility for an online dinner form on the Proto site. The idea is to create an order line page with admin option to create an order line which would be a combination of the amount to be paid plus the date. 

Kind regards, 
Maxim and Dennis

**Comment by jonathanjuursema** [comment]
Sounds like a perfect idea. I'm not sure when we will implement this (given our futureproofing plans) but definately worth considering.

**Comment by maximdeleeuw** [comment]
if possible, please consider high priority, because it will definitely help
us.

*Kind regards, *


Maxim de Leeuw| Candidate Treasurer of S.A. Proto 8.0

M +31 650 56 06 42

P +31 53 489 4423

E cb@proto.utwente.nl (Candidate Board)

E m.deleeuw@proto.utwente.nl (Personal)

W https://www.proto.utwente.nl/

<https://www.proto.utwente.nl/>

Study Association Proto

Drienerlolaan 5
<https://maps.google.com/?q=Drienerlolaan+5+7522+NB+Enschede+The+Netherlands&entry=gmail&source=g>

7522 NB Enschede
<https://maps.google.com/?q=Drienerlolaan+5+7522+NB+Enschede+The+Netherlands&entry=gmail&source=g>

The Netherlands
<https://maps.google.com/?q=Drienerlolaan+5+7522+NB+Enschede+The+Netherlands&entry=gmail&source=g>


S.A. Proto is the study association of the Creative Technology bachelor
program and Interaction Technology master program at the University of
Twente

**Comment by jonathanjuursema** [comment]
We gave this another thought and couldn't find significant value above the already existing dinner form. We figure the only time this will save is the time spent entering the people and the price they need to pay into the "add multiple/complex orderlines" form. Because of this we reject this issue for now. If you don't agree with this, please let us know what we've missed.
