### ISSUE TITLE
Email Archive for Board functions?

### ISSUE THREAD

**Issue by emielsteegh** [saproto/saproto#779]
I would like to be able to access emails sent or received by previous owners of my alias. This way I can easily look into what other secretaries before me have done like knowing when which members have requested to no longer be member. And there are probably other useful features here.

I understand that I would not benefit from this feature as the mails before me have most likely gone into some owner-less digital void. But the poor saps after me (and the other functions) might benefit from this the way I would like to benefit from it.

maybe forward all mail to another adress like archive[function] or archive[board]?

**Comment by jonathanjuursema** [comment]
This should be possible. Although we don't really want to offer mailboxes for general use, this is most certainly doable. We can create an archive account that you can access via webmail and just forward all your stuff to there. Question is, would it suffice to have one account that we forward everything to?

**Comment by emielsteegh** [comment]
As long as the email is tagged in some way, being able to search for the original sender/receiver of the email would be great.

**Comment by jonathanjuursema** [comment]
We discussed this again during the meeting and figured we still miss some feedback and/or think some things are not entirely thought out. Flip was at the discussion and will take this to the next board meeting. We'll await what comes out of that! @emielsteegh you'll also find the discussion in the minutes.

**Comment by emielsteegh** [comment]
After some discussion we came to the conclusion that mainly I just want wan archive and the rest of the board does not see it as necessary function.

The solution we see fit is a webmail that gets all incoming and outgoing email from the board _and_ secretary into one inbox that only the secretary and vice secretary get access to.

cheers

**Comment by jonathanjuursema** [comment]
This is finally fixed! You can approach `boardarchive@proto.utwente.nl` via the [webmail](https://webmail.saproto.nl) (be sure to select `E-mail for Metis`!)

 I'll give you the password later today. :)
