### ISSUE TITLE
Protube Remote Scroll Playlist

### ISSUE THREAD

**Issue by Frankieknarf** [saproto/saproto#781]
Could the playlist in the Protube remote be made scrollable? Members can then see how long it will approximately take for their song to be played. now you can only see 8 songs in advance. 

![opera snapshot_2018-09-11_100913_www protube nl](https://user-images.githubusercontent.com/22320883/45347293-fe94cd80-b5ab-11e8-8922-a2b7db943fb6.png)

**Comment by thijsdortmann** [comment]
This used to be possible, but was removed because it made scrollbars look weird on some devices (see #628). I'll look into re implementing this.

**Comment by thijsdortmann** [comment]
Due to the amount of effort to fix this in such a a way that #628 won't come back is quite difficult. This will therefore not be fixed.
