### ISSUE TITLE
Photo policy

### ISSUE THREAD

**Issue by emielsteegh** [saproto/saproto#782]
Other association have a checkbox for stating that you are fine with having pictures taken or used, is this relevant for proto or is it fine just stating something like that in the PP

**Comment by emielsteegh** [comment]
In the process of becoming a member*

**Comment by jonathanjuursema** [comment]
This is already in our [Privacy Policy details](https://wiki.proto.utwente.nl/ict/privacy/details#photos_and_portrait_right). Upon consideration (maybe @xadya has an opinion on this) we may consider moving that paragraph and/or adding a small statement to the [main Privacy Policy](https://wiki.proto.utwente.nl/ict/privacy/start).

I think @xadya knows more about whether or not this is enough, but based on what I hear around me it should be enough for now.

**Comment by xadya** [comment]
Has been made more clear in the privacy policy.

**Comment by emielsteegh** [comment]
Opidopi
