### ISSUE TITLE
access to hidden events

### ISSUE THREAD

**Issue by emielsteegh** [saproto/saproto#784]
When a member that does not have access obtains the link to a hidden event, they can view it like normal.
Is it enough of a concern to patch them to only people with access can view type of deal?

It does not bother me a lot personally as people should not normally be able to obtain these links, but just getting it out there

**Comment by jonathanjuursema** [comment]
This is the intended use! It's meant for something like the active member activity.

The toggle is called "secret", and if you tell someone about a secret, they know that secret. :O
