### ISSUE TITLE
Tutorial-like welcome for people that log into their Proto account for the first time

### ISSUE THREAD

**Issue by daniepyromanie** [saproto/saproto#788]
Abacus has a system like that. When you log into your account for the first time, you get a popup saying something like "Welcome to the [association name] site, you can do a lot of new things now!" and then the popup message will go past important menu options. 
For example, "The Association: here you can see important documents, photos, committees and all activities that are being organised." or "DokuWiki: useful documents will be put here, including summaries, design request pages, and all GMM documents".

I don't know if it's hard to implement (i guess it is) but it might be nice so new members know what to do with the website!

**Comment by jonathanjuursema** [comment]
This should be possible with the new announcements functionality. If you can give us the text that you would like to have shown to new users, we'll make it happen!

**Comment by jonathanjuursema** [comment]
We're still waiting on an answer to the question posted above. In addition, outside of this issue we've also heard that the idea is to make it close to what Abacus currently has. After discussing we think that this is a large hassle for relatively little gain. Can you please let us know exactly what functions should be highlighted and explained, and how often there are questions about these pages.

**Comment by daniepyromanie** [comment]
I'm sorry for the late reply. It was indeed meant to be like the Abacus website, but I understand that that is too much. 
I think it's just a lot of cool pages that are unnoticed unless someone wanders the website for long enough (like the quote corner, achievement page). But I think the most important pages are the user's dashboard, as you can basically do everything there related to your profile, and the committee page, because if you want to be active or if you have questions for committees that's where you should look.
I will type a text for both of them, and if you have other suggestions feel free to let me know!

**Comment by daniepyromanie** [comment]
Dashboard: "If you want to change your profile, (un)subscribe for mailing lists, or add an allergy/diet wish to your account, you should go to your dashboard!"
Committees: "Here you can see every committee that currently exists. Click on a committee to get more information as well as an email address so you can contact the committee if you have questions."

Something like this?

**Comment by jonathanjuursema** [comment]
Is this everything the board wants there?

**Comment by thijsdortmann** [comment]
The board has decided not to have this implemented.
