### ISSUE TITLE
drive/bitsync/network folder: "cloud" storage

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#79]
I'd love it if the board could add folders for persons, committees or other groups and provide them with credentials.

choice of means for storage is up to you. I do like the network folder-system, works like a charm

**Comment by jonathanjuursema** [comment]
We have this now! We recently set-up an Active Directory environment that synchronizes users and committees with the association database. With that AD, we can very easily create network shares for users and committees. If you want a network share for your committee, please let us know. :)
