### ISSUE TITLE
Newsletter standard text

### ISSUE THREAD

**Issue by PhilippeTu** [saproto/saproto#790]
When I send the newsletter there are pieces of standard text included.
First it says what the newsletter is for, and then the "special announcement by the board", afterwards it shows the text that I type.
The standard text doesn't add much, can it be removed?

**Comment by thijsdortmann** [comment]
Yes it can!

Just a bit of context on why it's there: the previous board requested this feature for very occasional use, so it was added to make the content stand out.

**Comment by PhilippeTu** [comment]
Could you maybe also add ''Officer of Internal Affairs'' below my name, so people can also immediately know who I am in relation to the association.
