### ISSUE TITLE
Pirate OmNomComMonster

### ISSUE THREAD

**Issue by Harladus** [saproto/saproto#791]
Dear HYT,

Hereby I send in yet another OmNomComMonster. Not only for "Talk like a pirate" - day, which is today, but also as a promotional element for this year's Proto camp having the pirate-y theme "Tales of the Singing Sails". The OmNomComMonster can, as always, be found on Google Drive: https://drive.google.com/drive/folders/1IH190t17D9sJbBH_q1V9sKyoKWPhGfpE?usp=sharing

Shiver me Timbers!
Harrrrladus "Youri" Eversmann

**Comment by jonathanjuursema** [comment]
Closed via https://github.com/saproto/saproto/commit/44c71d23d7abbb54d06b5fe03c48817938158a70
