### ISSUE TITLE
Checkbox in userprofiles for having signed an NDA

### ISSUE THREAD

**Issue by emielsteegh** [saproto/saproto#797]
thanks

**Comment by jonathanjuursema** [comment]
I'm not sure what you mean with this. This functionality is already available but restricted to the site admins, to make sure the system is used like it's supposed to.

**Comment by emielsteegh** [comment]
The Idea was that if a member signs an NDA and that signed NDA has been added to a physical archive, people with access to useradmin like board members can click something like has studied create (except then it might be has signed an NDA) so that there exists a digital database next to a physical folder with all the NDAs.
This way I can check if for every user that has signed an NDA we still own the form (and maybe scan them?) and for new NDA signees I can just add them to keep everything updated.

But I can understand if this is something the site admins want to do themselves to keep a proper overview. Also I don't know how often a board member will have to make someone sign an NDA or if this is more exclusive to admins.

**Comment by jonathanjuursema** [comment]
The functionality already exists, and I'll send more info your way via Slack!
