### ISSUE TITLE
Drink request page 

### ISSUE THREAD

**Issue by PetervanderBurgt** [saproto/saproto#812]
Hello Have You Tried,

I would like for the TIPCie to have a drink request page, just like the poster request page. 

People would need to fill in the following things. 
Name of the drink
Date of the drink
Date of the request
Preference what drink room (AbScInt Mbasement, SmartXP) 
Begin time 
End time
Committee 
Contact person 

Thank you for the effort. 

Peter

**Comment by jonathanjuursema** [comment]
The form is on-line [here](https://wiki.proto.utwente.nl/members/active/request-drink).

The wiki page is locked to make sure people don't accidentally mess up the form. If you would like to have additional text added, please let us know!
