### ISSUE TITLE
Deleted accounts link to your own profile

### ISSUE THREAD

**Issue by emielsteegh** [saproto/saproto#813]
This is a suggestion as a member

When you try to visit an account that has been closed via their link (from a committee page for example) it refers to /user making you visit your own profile.
Is this intentional? It feels weird to me, maybe link to a profile no longer exists page?

(also their profile picture is still be visible on the committee pages member list even if they no longer hold an account)

**Comment by jonathanjuursema** [comment]
This is not intentional.
