### ISSUE TITLE
Show notification when receiving new achievement and offer to show on profile

### ISSUE THREAD

**Issue by thijsdortmann** [saproto/saproto#817]
Some people might not want to show their achievements to other people. For this reason, having achievements publicly available on ones profile should be opt-out.

**Comment by DennisVinke** [comment]
Is it possible to toggle per achievement if you want to show this on the site? 

I think some achievements are too specific to show on the site, so I can imagine some people would not like to show that they spend a lot of money on beer or a lot of money in general on the site, while they would be fine with some of the other achievements to be public.

**Comment by xadya** [comment]
We will discuss this next Tuesday.

@saproto/board can you think about this too?

**Comment by thijsdortmann** [comment]
This would replace the current behaviour where all achievements are displayed on a user's profile.
