### ISSUE TITLE
Activity Icon for Studynights

### ISSUE THREAD

**Issue by daniepyromanie** [saproto/saproto#819]
Hello dear HYTTIOAOA committee. The site is currently looking pretty fine with all these icons indicating whether you have signed up, have bought a ticket, an ERO is needed, you are currently helping, it is not organised by Proto etc. Would it be possible to include an icon when an activity is a studynight so people can easily see that the activity is 'good for your education'?

Maybe something like this :
![open-book](https://user-images.githubusercontent.com/33750931/47347836-5f85ea00-d6b0-11e8-8282-eada9a964467.png)

**Comment by jonathanjuursema** [comment]
I think a "this activity is educational" toggle should not be a problem. Any other ideas on how this toggle can be shown throughout the site?

Regarding the icon, you can choose any icon from [here](https://fontawesome.com/icons?d=gallery&q=study&m=free), [here](https://fontawesome.com/icons?d=gallery&q=book&m=free) or [here](https://fontawesome.com/icons?d=gallery&m=free). Or perhaps [this one](https://fontawesome.com/icons/university?style=solid)?

**Comment by daniepyromanie** [comment]
What do you mean "how it can be shown throughout the site"? It can be next to the activity name as an icon.
https://fontawesome.com/icons/book-open?style=solid I think this one works best.
