### ISSUE TITLE
Import doesn't like accented characters (e.g. AprèsCie)

### ISSUE THREAD

**Issue by thijsdortmann** [saproto/saproto#82]
See the [committee page](https://next.saproto.nl/committee/list) and the [committee detail page](https://next.saproto.nl/committee/2068), where AprèsCie appears as Apr.

This is also incorrect in the database, meaning that this happens during import from the old database.

**Comment by jonathanjuursema** [comment]
There seems to be problems converting from the source to the destination database. Adding new entries with special characters works fine. We're going to manually fix the few entries that need fixing after importing.

*wontfix*
