### ISSUE TITLE
Preview button when editing/making a new News-article

### ISSUE THREAD

**Issue by PhilippeTu** [saproto/saproto#826]
Title says it all ;)
Should be easy enough to implement just like you did for the Weekly Newsletter preview button

**Comment by jonathanjuursema** [comment]
You can already set the publish date to the future, and visit the news page using the "eye" button in the news admin. Would you require anything more than this?

**Comment by jonathanjuursema** [comment]
@PhilippeTu indicated that this was sufficient and he was just lazy. 😁
