### ISSUE TITLE
Show an animation when "OmNomCom is awesome" is bought through the OmNomCom computer

### ISSUE THREAD

**Issue by MartijnVerkleij** [saproto/saproto#827]
Today in the Proto room people talked about that it would be awesome to show an animation when the the product "OmNomCom is Awesome!" is bought through the OmNomCom computer.

**Comment by thijsdortmann** [comment]
Due to the amount of work required for this and the hacky solution that would have to be added to the Omnomcom, as well as other committees that would most likely also want this afterwards we're not going to implement this.
