### ISSUE TITLE
S.A. Proto redesign – feedback

### ISSUE THREAD

**Issue by jonathanjuursema** [saproto/saproto#829]
**Hej!** *(that's Swedish for hello)*

We just launched a new design for the website of S.A. Proto, something the [Have You Tried Turning It Off And On Again committee](https://www.proto.utwente.nl/committee/haveyoutriedturningitoffandonagain) worked hard on over the past few weeks. You will find most of the stuff where you used to find it – it just looks different.

The website got a new paint job because the look that it had for the past two years was not well thought out and was always secretly never meant to be the *final* design. With its new appearance we put more thought in what goes where and how it should look. In addition, we also updated a lot of stuff behind the scenes so that the site runs on a modern design scaffolding.

We would like the new design to be an ongoing project. If you have any suggestions, tips, criticism or feedback, let us know below. You can upvote or downvote suggestions at your convenience, and perhaps your suggestion will be baked in to the new Proto site!

**Please only put one suggestion/tip/bug per comment. You can make multiple comments after each other.**

_If your coment is marked as resolved please be patient. The code changes are not immediately deployed to the website._

**Comment by renskruining** [comment]
Feedback:
Price of activity cannot be seen when signed up

Mobile landing page for "non-logged-in": the text on top of the picture "welcome to study.." can only be seen partially

Mobile: the hamburger icon (menu) outline turns (and stays) orange upon opening the menu

**Comment by daniepyromanie** [comment]
![image](https://user-images.githubusercontent.com/33750931/47716920-65e20c00-dc44-11e8-838f-067e86cbdd9a.png)

Greate -> typo :3 should be 'Great'

**Comment by thijsdortmann** [comment]
The sidebar with 'upcoming events' can be confusing on some pages. For example, the committee page.

**Comment by jonathanjuursema** [comment]
@thijsdortmann @robi-wan69 

Looking for input. Most user-facing pages (such as committee information, static pages and activity pages) now have a 'sidebar' with upcoming activities and recent albums. Some people perceive this as confusing and/or unnecessary. Please 👍 this comment if you want to keep the sidebar, and 👎 if you want it removed! 😀

**Comment by jonathanjuursema** [comment]
> * [ ]  The menus are a mess
> * [x]  The Proto.Ink articles should have a similar styling as the regular 'News' styling
> * [x]  Do the upcoming events and recent photo albums have to show up on every page?

@robi-wan69 what exactly do you mean with "the menus are a mess"?

**Comment by renskruining** [comment]
in what way is Frankiknarf [comment](https://github.com/saproto/saproto/issues/829#issuecomment-434263597) resolved? I still encounter the issue

**Comment by jonathanjuursema** [comment]
> in what way is Frankiknarf [comment](https://github.com/saproto/saproto/issues/829#issuecomment-434263597) resolved? I still encounter the issue

I've resolved the issue in the code, but the code is not yet published. I've added a clarification in my original post.

**Comment by jonathanjuursema** [comment]
@renskruining below are my responses to the yet unresolved points you mentioned. Could you post a new comment per thing that you still think is relevant? That make resolving the comments a little easier. I'll also update my original post.

- [ ] Activity: [mobile]why does signup always come before the info?

The order comes from a design choice for the desktop version. If you would like to see the order reversed you could start a vote below!

- [ ] Menu: the menus "association" and "for members" could use some cleanup/reorganisation as wel as spaces/dividers/horizontal lines

This should be fixed by the @saproto/board (except for the dividers, this is not possible yet).

- [ ] Achievements: some have missing icons

This should be fixed by the @saproto/board.

- [ ] Achievements: when opening another category, the page doesn't adjust scrolling, placing the view halfway down a list

I'm not sure what you mean, can you elaborate?

- [ ] Dashboard: birthdate and phone have a checkbox "show to members", but address has a button for the same purpose

This has something to do with the back-end and was already the case in the previous design. We might fix this some day but we don't think it has a high priority.

- [ ] Dashboard: "General Proto News"-mailing list and news page can be confused, due to information now hidden.

Can you elaborate?

- [ ] Card styling: two different styles are used: white text with black dropshadow on full color image (photo albums, committees and news items(their respective pages), and black text without shadow on faded color image (calendar, videos)

This is on purpose. For the full-color image cards, white text is more legible. We only use full-color cards when they are the main focus of the page (such as photo albums). All other pages should have the faded cards, and these should not be mixed on one page. If I did this somewhere, do let me know.

- [ ] Card styling: all use the latter styling in the short version below almost every page.

What do you mean exactly?

**Comment by renskruining** [comment]
*Vote* On Activity pages on _mobile_, the signup now comes before the event name and info. I think it would be better for it to be the other way around. That way, you instantly know you have entered the intended page, read the info immediately and don't have to scroll through a (stupendously long) signup list first.
It also puts the signup list above (or at least that's my suggestion) the helpers list
👍 for activity name and info first
👎 for signup first

**Comment by renskruining** [comment]
>  - [ ] Achievements: when opening another category, the page doesn't adjust scrolling, placing the view halfway down a list
>  I'm not sure what you mean, can you elaborate?

This is both on mobile as it is on desktop. The achievements and committee members are now divided into groups which are collapsed by default, except for the top one. Clicking a group collapses the open group and opens the clicked. 
As the first group requires some scrolling (most of the time on mobile), and the second or other group does not reset scrolling to its top when clicked, the user ends up halfway down a group.
I suggest a script or function to scroll the top of the screen to the top of the clicked group.

>  - [ ]  Dashboard: "General Proto News"-mailing list and news page can be confused, due to information now hidden.
>  Can you elaborate?

Maybe this is with the idea of a mailinglist for news items (on proto.utwente.nl/news) in the back of my mind, but as the information of the mailing lists is now hidden by default (revealed only after clicking), it could be unclear/misunderstood at the first glance.
I think the fix for the  other checkbox on _Dashboard Mailinglists_, discussing the markup of the information above it, would fix this problem as well.


>   - [ ] Card styling: two different styles are used: white text with black dropshadow on full color image (photo albums, committees and news items(their respective pages), and black text without shadow on faded color image (calendar, videos)
>  This is on purpose. For the full-color image cards, white text is more legible. We only use full-color cards when they are the main focus of the page (such as photo albums). All other pages should have the faded cards, and these should not be mixed on one page. If I did this somewhere, do let me know.

Then why are the videos with faded images? and the reason behind full color committee images?
News has some without picture, which standout a lot now, but would less do so with faded images, I reckon.

>  - [ ]  Card styling: all use the latter styling in the short version below almost every page.
>  What do you mean exactly?

What I meant here is that the sidebar (especially on mobile) really stands out a lot when the rest of the page uses the other styling (full color image cards)

Thanks for your hard work!

**Comment by renskruining** [comment]
hyperlink markup: 
- [ ] links are the same colour and style(black, regular font) as the rest of the page, and are indistinguishable until hovered over with the cursor, underlining them.
I think a colour would make them more easily recognisable as links.
(as seen in this [example](https://www.proto.utwente.nl/page/Posterrequest))


Activities without signup:
- [ ] the page doesn't indicate there is no signup.

**Comment by PetervanderBurgt** [comment]
![image](https://user-images.githubusercontent.com/32461043/47733794-4e694a00-dc69-11e8-8e6e-e1d456e95b46.png)

The times are a bit weird : 3

**Comment by daniepyromanie** [comment]
![image](https://user-images.githubusercontent.com/33750931/47734980-c89ace00-dc6b-11e8-8e8e-e7e4459324f2.png)

The committee box is overlapping the description lay out bar waaah

**Comment by thijsdortmann** [comment]
Adding a committee member without an end date is not allowed anymore, since the until field would be empty.

**Comment by maximdeleeuw** [comment]
If the welcome message on your profile is longer than 5 words, the message is cut while seeing it on your telephone

**Comment by renskruining** [comment]
I would love it if hyperlinks (in texts) open in new tabs instead of the current tab.

**Comment by jonathanjuursema** [comment]
> > * [x]  Achievements: when opening another category, the page doesn't adjust scrolling, placing the view halfway down a list
> >   I'm not sure what you mean, can you elaborate?
> 
> This is both on mobile as it is on desktop. The achievements and committee members are now divided into groups which are collapsed by default, except for the top one. Clicking a group collapses the open group and opens the clicked.
> As the first group requires some scrolling (most of the time on mobile), and the second or other group does not reset scrolling to its top when clicked, the user ends up halfway down a group.
> I suggest a script or function to scroll the top of the screen to the top of the clicked group.
>
Fixed
> > * [x]   Dashboard: "General Proto News"-mailing list and news page can be confused, due to information now hidden.
> >   Can you elaborate?
> 
> Maybe this is with the idea of a mailinglist for news items (on proto.utwente.nl/news) in the back of my mind, but as the information of the mailing lists is now hidden by default (revealed only after clicking), it could be unclear/misunderstood at the first glance.
> I think the fix for the other checkbox on _Dashboard Mailinglists_, discussing the markup of the information above it, would fix this problem as well.
Fixed with the markup suggestion.
> 
> > * [x]  Card styling: two different styles are used: white text with black dropshadow on full color image (photo albums, committees and news items(their respective pages), and black text without shadow on faded color image (calendar, videos)
> >   This is on purpose. For the full-color image cards, white text is more legible. We only use full-color cards when they are the main focus of the page (such as photo albums). All other pages should have the faded cards, and these should not be mixed on one page. If I did this somewhere, do let me know.
> 
> Then why are the videos with faded images? and the reason behind full color committee images?
> News has some without picture, which standout a lot now, but would less do so with faded images, I reckon.
> 
The idea is that if something is the page's main feature (such as the committees on the committee page) the images will pop (full color). If it's not (like the calendar events on the homepage, or the sidebar on most user pages) the images will not pop (washed out). I'll push an update which makes this a little more consistent regarding the videos.
> > * [x]   Card styling: all use the latter styling in the short version below almost every page.
> >   What do you mean exactly?
> 
> What I meant here is that the sidebar (especially on mobile) really stands out a lot when the rest of the page uses the other styling (full color image cards)
> 
> Thanks for your hard work!

**Comment by jonathanjuursema** [comment]
> hyperlink markup:
> 
> * [x]  links are the same colour and style(black, regular font) as the rest of the page, and are indistinguishable until hovered over with the cursor, underlining them.
>   I think a colour would make them more easily recognisable as links.
>   (as seen in this [example](https://www.proto.utwente.nl/page/Posterrequest))
> 
Is going to be fixed.
> Activities without signup:
> 
> * [ ]  the page doesn't indicate there is no signup.

This was also not the case on the old site. We could include a notice, but this notice should be thought about well. There could be any number of reasons for not having a sign-up (no sign-up required, or sign-up via another site, fill in your own). If a specific notice is wanted, please discuss with the board and make proposal here. :)

**Comment by jonathanjuursema** [comment]
> ![image](https://user-images.githubusercontent.com/33750931/47734980-c89ace00-dc6b-11e8-8e8e-e7e4459324f2.png)
> 
> The committee box is overlapping the description lay out bar waaah

@daniepyromanie on what page, device and resolution are you having this? I can't find it.

**Comment by jonathanjuursema** [comment]
> If the welcome message on your profile is longer than 5 words, the message is cut while seeing it on your telephone

@maximdeleeuw this is unfortunately not really fixable in a reliable manner. :(

**Comment by jonathanjuursema** [comment]
> I would love it if hyperlinks (in texts) open in new tabs instead of the current tab.

@renskruining This is something the @saproto/board should fix. The @saproto/board can use HTML in their Markdown edit fields (such as with pages) and can manually set the target tag there.

See [here](https://stackoverflow.com/a/4425223/7316014) for reference.

**Comment by Habenga** [comment]
Is it possible to add a 2 collum site layout? 
Now it goes from 1 collum to 4 instantly, having a 2 collum view at the 'iPad'/half monitor size would be nice.

**Comment by jonathanjuursema** [comment]
> Is it possible to add a 2 collum site layout?
> Now it goes from 1 collum to 4 instantly, having a 2 collum view at the 'iPad'/half monitor size would be nice.

@abelgerritse can you specify suggestions for specific pages? There is no 'one site layout'. Every page has their own layout according to the needs of the page. :)

**Comment by Habenga** [comment]
> > Is it possible to add a 2 collum site layout?
> > Now it goes from 1 collum to 4 instantly, having a 2 collum view at the 'iPad'/half monitor size would be nice.
> 
> @Habenga can you specify suggestions for specific pages? There is no 'one site layout'. Every page has their own layout according to the needs of the page. :)

So far I just meant the home page. I have not found any other pages that actively use the 4 columns individually.

**Comment by MartijnVerkleij** [comment]
I believe this specific bug has not been reported yet. The proto.ink cards on the front page have an explicit height set. Specifically, the <a> tag. Due to this, long titles overflow.

Screenie: 
![proto front page overflow bug](https://user-images.githubusercontent.com/4638931/47910253-928b6300-de92-11e8-8408-0c39531f024a.png)

Also, it feels a bit weird that no Proto logo is present in the navigation bar, next to the logo. I must also admit that despite the little playing around with the page that I did, I do not know how to add it without looking bad....

**Comment by xadya** [comment]
Can you make the UT address book search toolie a with wider?

![image](https://user-images.githubusercontent.com/8876164/47929565-b4540c80-dec9-11e8-80f9-d40b7073d0a8.png)

**Comment by maximdeleeuw** [comment]
Orderline wizard is missing some products, for instance a4 prints aren't visible. Therefor, I need to manually add 6 prints to someone

**Comment by jonathanjuursema** [comment]
> Orderline wizard is missing some products, for instance a4 prints aren't visible. Therefor, I need to manually add 6 prints to someone

@maximdeleeuw the orderline wizard only shows products marked as "visible" in the OmNomCom (to reduce the number of products since we cannot use the search fields there). I've marked the A4 product as visible and removed it from the "Specials" category to prevent it from popping up on the OmNomCom.

**Comment by maximdeleeuw** [comment]
Hey Jonathan,

That explains a lot! Thanks!

**Comment by jonathanjuursema** [comment]
> Also, it feels a bit weird that no Proto logo is present in the navigation bar, next to the logo. I must also admit that despite the little playing around with the page that I did, I do not know how to add it without looking bad....

@MartijnVerkleij I tried but the logo is just too complex to show in the little space of the navbar. If anyone has a good suggestion on where to put le logo, please do let me know!
