### ISSUE TITLE
[Site Frontpage] Newsletter Story

### ISSUE THREAD

**Issue by PetervanderBurgt** [saproto/saproto#832]
Hey Have You Tried,

In the newsletter Philippe always types a nice little piece about the board, what we are doing and such.
It would be great to see this on the frontpage as well, as a small piece to show on the website what we are doing. Besides this, having the newsletter on the website as well would be good ;)
Thanks in advance.

Peter

**Comment by jonathanjuursema** [comment]
@PetervanderBurgt @PhilippeTu This will be visible later today. Please be reminded that this means we no longer clear the newsletter text after sending the newsletter, and so you should **always** check the newsletter text before sending.
