### ISSUE TITLE
2FA field on log-in saves previous authentication keys

### ISSUE THREAD

**Issue by emielsteegh** [saproto/saproto#838]
[suggestion]
If there is an easy way to disable the auto-fill option in the 2FA field that would be nice.
obviously there is a pretty slim chance that one of the previous keys is going to be the one ;)

**Comment by emielsteegh** [comment]
when I said saves I mean suggests. google is the one saving the keys, but if there is a way of letting browsers know that there is no need for saving here that would be neat

**Comment by jonathanjuursema** [comment]
This [should be doable](https://gist.github.com/niksumeiko/360164708c3b326bd1c8), sounds logical and I don't see any security reasons to not do this. @thijsdortmann?
