### ISSUE TITLE
Weekly Newsletter automatically on a Newspage

### ISSUE THREAD

**Issue by PhilippeTu** [saproto/saproto#842]
I heard that a few people miss seeing the Weekly Newsletter. They eihter don't read it in their email and delete it immideiatelywhich I find a shame since I try my best to write an interesting story each week.
Woul it be possible to assign a Newsletter slot to the weekly Newsletter there? So the weekly newsletter uploads automatically to that assigned slot each time I send it.
Maybe even add an achive so all the Newsletters get saved for future reference, but thats not all that necessary and possibly redundant.

**Comment by jonathanjuursema** [comment]
Isn't this a duplicate of #832?

**Comment by PhilippeTu** [comment]
Ah shait, yeah indeed :x

**Comment by jonathanjuursema** [comment]
Closed as duplicate of https://github.com/saproto/saproto/issues/832.
