### ISSUE TITLE
Rename isPrize to excludeFromAllAchievements or something

### ISSUE THREAD

**Issue by thijsdortmann** [saproto/saproto#845]
This option does not seem to do anything and can be removed.

**Comment by jonathanjuursema** [comment]
I've checked the code and the isPrize attribute seems to be used to ignore that achievement for the "collected all achievements" achievement. So it actually seems to fix the bug we saw with that achievement. Should we just keep it (or perhaps rename it)?

**Comment by jonathanjuursema** [comment]
Because that is the actual function of the toggle
