### ISSUE TITLE
iPhone app endpoint requests

### ISSUE THREAD

**Issue by hesje** [saproto/saproto#850]
Gather Issue for all endpoint requests etc. for the iPhone App (eg. isaak)

**Comment by hesje** [comment]
An endpoint for retrieving the personal welcome message of a user.

**Comment by hesje** [comment]
an endpoint for retrieving the omnomcom purchase history of a certain user

**Comment by hesje** [comment]
an endpoint that retrieves the events that a certain user is signed up for and an endpoint for signing a user up for an event

**Comment by hesje** [comment]
I think the endpoint for retrieving the last 100 purchases actually returns the _first_ 100 purchases. I namely get purchases between 2014 and 2016

**Comment by hesje** [comment]
Add information about whether a user should have access to protube admin in the /api/user/info endpoint

**Comment by hesje** [comment]
@jonathanjuursema The events endpoint doesn't return whether someone can still sign out.

**Comment by jonathanjuursema** [comment]
For the overview I'll close this issue. Feel free to re-open if there's more work to be done. :)
