### ISSUE TITLE
Empty Calendar Year

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#866]
Dear,

When perusing the calendar, I found 2019, which was empty (for me).

Now I assume this is because of a hidden event, but it looks a bit weird d:
![screenshot 2018-11-21 at 16 44 23](https://user-images.githubusercontent.com/9930890/48852203-258e2d80-edad-11e8-85ba-f538ad647132.png)
[Screenshot of 2019 calendar](https://www.proto.utwente.nl/events/archive/2019)

**Comment by jonathanjuursema** [comment]
You, sir, hit the nail on the head.
