### ISSUE TITLE
OmNomCom product ID not visible for OmNomCom

### ISSUE THREAD

**Issue by sainety** [saproto/saproto#868]
Hello beheer :)

We hebben een probleem gevonden voor de OmNomCom. Op de proto website is op dit moment niet meer het product ID van de producten in de OmNomCom te zien.  Dit is onhandig met het toevoegen van nieuwe producten. Kunnen we dit misschien weer ergens te zien krijgen? 

Groet, OmNomCom :)

**Comment by jonathanjuursema** [comment]
No problem. Could you post in Engelish next time? :)
