### ISSUE TITLE
Protography chair(s) to set cover photo

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#869]
It would be very nice to make Protography members feel more appreciated by placing nice photos of activities as new cover photos. Since Protography chairs probably know best which photos were made recently, it would be nice to give them access to this tool. In this way more people will also notice new photos which will probably make them curious for the entire photo album.

**Comment by jonathanjuursema** [comment]
Closed via 6498926550d830875c70e700374ce6a4b649384b
