### ISSUE TITLE
Notification on site for Privacy Changes

### ISSUE THREAD

**Issue by DennisVinke** [saproto/saproto#872]
As mails are not always sent after changes in the privacy policy as they could be included in a bigger privacy policy update mail. As the privacy policy right now is somewhere on the wiki and you will only look at it if you need it, the changes are not really noticed without a notification. 

Would it be possible to implement something in the site to notify users that something in the privacy policy has changed? This could be as simple as having a little text in the footer that says "Last change to privacy policy on: xx-xx-xxxx". That way people know something changed and will be able to find the changes themselves through the history page function on the wiki.

**Comment by DennisVinke** [comment]
I was failing and pressed the wrong button. Working on description right now :P

**Comment by xadya** [comment]
This has already been discussed, and the board has chosen not to implement this.
