### ISSUE TITLE
Unable to request helping committees

### ISSUE THREAD

**Issue by PhilippeTu** [saproto/saproto#884]
I'm unable to add helping committees (like the organizing committee or Protography) when there is not a sign-up included.
Could this be fixed?

**Comment by thijsdortmann** [comment]
What you want is already possible: add a sign-up but choose 0 as the participant limit. The event will then not show a sign-up option on the website, but you can still add helping committees and people can sign up as helpers. This is also explained when hovering the (?)-symbol next to the participant limit.
