### ISSUE TITLE
Relay helping helper to committee

### ISSUE THREAD

**Issue by emielsteegh** [saproto/saproto#886]
The board would like a feature added. If a member from a supporting committee signs up to help with an activity it would be useful to send an email (very much like the "Helper for the Protography subscribed for the activity BBQ Hunt."-type mail) to the organising committe stating who signed up to help. Same thing for when someone signs out of helping.

**Comment by jonathanjuursema** [comment]
I want to double check if this is what you really want. This means that a lot of people will get a lot more e-mails, and this might affect the effectiveness of these e-mails. Are you sure you want this?

**Comment by thijsdortmann** [comment]
Maybe this could be only sent to the people that subscribed to the helper reminder mails?

**Comment by thijsdortmann** [comment]
Oh, nevermind. It read over that part in the issue. I agree with Jonathan that this would probably send too much email to members of a committee. Maybe we could implement this so that the committee get's an email if a helper unsubscribes shortly before the event?

**Comment by jonathanjuursema** [comment]
I don't know if that would add much. What are they going to do? Ask the committee what's up. It's not likely they'll try to arrange something by themselves circumventing the helping committee. It should be the task of the helping committee to make sure somebody can help, and they can already subscribe for helper e-mails.

**Comment by jonathanjuursema** [comment]
Conclusion from the meeting. Making sure there are enough helpers is the responsibility of the board responsbile of that committee. They already have the tools needed for this job (the helper needed icon in the calendar and the helper reminder e-mails). Going forward the helping committee functionality should be properly used, and board responsibles should be aware that they are ultimately responsibly for making sure there are enough helpers for the committees they are responsible for,.
