### ISSUE TITLE
exam database and bookpage

### ISSUE THREAD

**Issue by Curmit** [saproto/saproto#89]
a database for exams  and a bookpage where all the books are shown with a picture and the posibility with ratings.

**Comment by jonathanjuursema** [comment]
@thijsdortmann how about a system were we can create Courses (maybe even in a year/module category) and assign books and/or files to them? That we we can add more stuff for courses later.

**Comment by thijsdortmann** [comment]
Implemented exam database for main study (Creative Technology) in 15c923439cc5b7ef90b5eb58279850438f4f1eae. Still to be done: make pretty, show courses added for different studies.

**Comment by jonathanjuursema** [comment]
Also linked to #25.
