### ISSUE TITLE
Automatic EmergenCie notification trigger

### ISSUE THREAD

**Issue by JRitmeester** [saproto/saproto#894]
Because of a mistake that is commonly made by committees and sometimes the board, EmergenCie is often notified on very short notice about the need for an ERO. That is why we (the whole board) agreed on requesting a feature where events with a sign-up list have a trigger as soon as 17 or more members sign up (20 - 3). This trigger should then cause an email to be sent to the EmergenCie that event X is in need of an ERO, along with the EmergenCie being added to helping committees. (or the other way around, I'm not familiar with the structure and chain of events of the website).

**Comment by jonathanjuursema** [comment]
This could be done fairly easily, but I see a number of problems.

1. We will also have occasions where we will have external ERO, or a board ERO member. This is sometimes discussed but not put on the site properly. This means the EmergenCie gets e-mails while in fact there is no need.
2. Do you want this feature to also create the "helping" entry automatically for the ERO?
3. What happens if number 17 signs up, signs out, and someone else signs up?
4. Do you want another e-mail if the sign-up stays between 17 and 20 (so in fact an ERO is not required, although one did sign-up)?

Functionality like this means that the website needs to guess what the truth is (i.e. when an how many ERO's are needed). To be perfectly honest, I think it's better that instead of the site trying to guess the truth, we just need to make sure the site knows the truth.

**Comment by jonathanjuursema** [comment]
Because of these technical reservations I'll mark this as a feature proposal for now, perhaps the rest of the committee disagrees with me. Regardless, we can discuss this tonigh.

**Comment by xadya** [comment]
I foresee the same issues. I think a solution to this is to send such a mail to the board, not directly to the committee.

**Comment by JRitmeester** [comment]
The point is that the board also often forgets to check. In an attempt to answer Jonathans questions:
1. If a board members acts as ERO it is usually done through the usual channels of EmergenCie anyway, so I don't think that is a valid reason. For an external ERO, the request should maybe be manually-overwritable?
2. Yes.
3. If an email was already sent to the ERO, then don't trigger again. Simple boolean helpWasRequest can fix this.
4. Perhaps this is a good idea. If for example 24 hours before the starting time of the event the participant count is still between below 20, a notification would be nice. However,  signing out as ERO should still be done after being discussed by whoever organises it.

**Comment by jonathanjuursema** [comment]
I'm not sure that will make everything easier... To be perfectly honest this seems like a lot of work for something that can be summarised as `we often forget to check`. If anything, I agree with @xadya to just send an e-mail to the board with something along the lines of "hey this activity has a lot of participants, make sure you arrange an ERO". But if this is something the board really wants, it's possible.

**Comment by JRitmeester** [comment]
Is it possible (literally, is it possible), as an alternative of sending the entire board an automated email, to link the recpients address to the committee email filled in "organisation" in the event page? I feel like most events that require an ERO are organised by a committee that can be filled in there. For example, if I were to put in pLAN and 17 people would sign up for a LAN party, the pLAN would receive such an email, rather than 1 board responsible and 5 others who don't have much to do with it.

Please note that this is a personal question. When answered I will discuss this with the board first.

**Comment by JRitmeester** [comment]
The idea by @jonathanjuursema seems like the right way to go. At least this way the committees are notified that an ERO is likely going to be required in the near future.

**Comment by jonathanjuursema** [comment]
Conclusion from the meeting: participant limit and helper functionality should be used properly (so no unlimited participants without enough BHV'ers, be consequent with participant limit and helping BHV'ers when you set the limits). And additionally it should be made more clear that if you're on the back-up list you will only pay when you're actually moved to the participants list.

This will be checked by the board in their next meeting.
