### ISSUE TITLE
Extra step with link to dashboard in membership wizard

### ISSUE THREAD

**Issue by daniepyromanie** [saproto/saproto#895]
Hey beheer!

Would it be possible to add another option when you are signing up to be a Proto member? It would be a checkbox list of all email list that one can sign up to, so you can easily select which ones you need (with a small description so people know what those lists are). 

It is now only possible on your proto dashboard, but a lot of members don't know it exists and easily miss out on signing up for mailing lists.

**Comment by xadya** [comment]
Wouldn't it then be nice(r) to guide this member to their dashboard so they know where to find this and more useful stuff later on in their Proto career?

**Comment by jonathanjuursema** [comment]
Perhaps we can point out the dashboard more clearly in the "hey you are now a member" e-mail?

**Comment by daniepyromanie** [comment]
Yes that might be nice! Would it also be possible to let the new members go to their dashboard automatically after they've become a member/user and then give a pop-up info to show they can sign up for email lists? Or is that what you meant? In that case, YES! :P 

Because my fear is that people see their page and just click through because there are so many different elements on the dashboard (mail lists, allergies, photo, personal info.). But this approach might work :D Because then members are even more aware of their dashboard!

**Comment by thijsdortmann** [comment]
It's currently unclear to us what exactly is expected by the board of this feature. Emiel will talk about this during the BV.

**Comment by emielsteegh** [comment]
"Een update over hoe we leden hun dashboard in laten vullen
wij zouden graag een extra stap zien bij /becomeamember die je naar het dashboard leid en je suggereert je profiel foto toe te voegen (als je daar comfortabel mee bent) / allergieën toe te voegen (als je die hebt) / voornamelijk je aanspoort je in te schrijven voor toepasselijke mail lijsten. 

Dus eigenlijk gewoon een extra stap met wat tekst, die al "klaar" is als je op de knop/link naar dashboard klikt. Zo zagen wij het voor ons"

groetjes

**Comment by thijsdortmann** [comment]
Cool, thanks :) We'll add an extra step to the membership wizard.
