### ISSUE TITLE
Fix bug in migrations OmNomCom calories

### ISSUE THREAD

**Issue by jonathanjuursema** [saproto/saproto#897]
https://github.com/saproto/saproto/blob/master/database/migrations/2018_11_14_172300_add_omnomcom_show_calories_to_users.php#L28
https://github.com/saproto/saproto/blob/master/database/migrations/2018_11_14_165117_add_calories_to_products.php#L28

@JonaMata there's something missing in your migrations. :D

**Comment by thijsdortmann** [comment]
Fixed in d44ffdf3e67521855a835c720dc98881e6dedb62.
