### ISSUE TITLE
Alfred's custom OmNomCom broken

### ISSUE THREAD

**Issue by MartijnVerkleij** [saproto/saproto#900]
Hi there!

Alfred just came by to ask about the omnomcom. He claims to not be able to see the items he's sold anymore, while he could before. 

Dennis suspects that it might have been forgotten during the redesign. 

Good luck!
~Martijn

**Comment by jonathanjuursema** [comment]
If I impersonate Alfred I can see one orderline for today. Is there any specific orderlines he's missing? Maybe someone of the committee can drop by to see what the problem exactly is.

**Comment by thijsdortmann** [comment]
We'll have to look into this together with Alfred, as we can't seem to be able to reproduce it. I'll ask him about it in the coming days.
