### ISSUE TITLE
Last step unclarity on proto.utwente.nl/becomeamember

### ISSUE THREAD

**Issue by PhilippeTu** [saproto/saproto#902]
I've hear a few times that it is not clear that a new member needs to come to the board to finalize the membership.
Now it only says that the board need to push a few buttons, so they think that they have done all that they need to do.
Could you add that in to make it more clear? :)

**Comment by xadya** [comment]
Could you specifically mention what you want it to say?:)

**Comment by PhilippeTu** [comment]
"You're almost a full-fledged Proto member! You'll need to find one of the board-members to finalize your registration. They can usually be found in the Protopolis - Zilverling A230"
