### ISSUE TITLE
Beerbutton omnomcom

### ISSUE THREAD

**Issue by Vlieking** [saproto/saproto#904]
Okay, what about a beerbell, but not a physical one, but a button on the omnomcom. When you press it, alarmbells sound effects go off and "wat zullen we drinken" automatically plays in the protube, to let everyone know the button has been pressed. In the next, like, 10 minutes everyone can stripe (one) beer on that persons account with their own card. Sounds amazing and fun, right? Right.

**Comment by xadya** [comment]
I think that we were just drifting away from the drinking culture, but this decision is really up to @saproto/board :)

**Comment by thijsdortmann** [comment]
Due to the technical aspects of this proposal (we would basically have to rebuild a large part of the Omnomcom), we're not going to do this.
