### ISSUE TITLE
Removing a wiki page

### ISSUE THREAD

**Issue by emielsteegh** [saproto/saproto#905]
https://wiki.proto.utwente.nl/proto/corporate

this wiki page has lost its purpose after corporate identity was moved to general info. I have pasted an ascii monkey in the page for the time being which does not translate very well into doku wiki flavoured markdown.
Anyway the page is obsolete, so please remove it :)

kisses

**Comment by jonathanjuursema** [comment]
Done! You can also remove it yourself by just emptying the page and saving. :)
