### ISSUE TITLE
Batch helper mails

### ISSUE THREAD

**Issue by emielsteegh** [saproto/saproto#911]
I think it would be more efficient and less spammy to group the "hey this event needs your help" emails into a daily (if any are sent that day) in to a "hey these events need your help" that is sent at midnight also spotlighting other events that still need help,

Thanks

**Comment by maximdeleeuw** [comment]
Hey dear HYTTIOAOA, 

Currently, the batch helper mail works really nice. It really helps with the spam. What I did notice, is that once a helper has been requested, and a helper has filled up the spot before the mail has been sent, it doesn't check if the spot is filled and still sends the mail. Is it possible to check if the helper has been found and thus no mail is required? 

xxxx your penny

**Comment by thijsdortmann** [comment]
I'll add the check :)
