### ISSUE TITLE
Mailing list

### ISSUE THREAD

**Issue by FemkeXJ** [saproto/saproto#915]
The Acquisition would like to do some more promotion for their acitivities. For this reason we would like to have a mailing list for the people that have previously visited a workshop to invite them when a new one is introduced. Is this allowed with the GDPR rules and possible to implement? If not are there any similar solutions that are possible? 

Kind regards,
Femke

**Comment by xadya** [comment]
Hey, It is certainly not allowed to let people automatically be put on some mailinglist, they should explicitly opt-in for such a list. However, there is already such a list specifically for external promotion which I think would be sufficient for your issue. If you really want you could explicitly (on paper) ask participants if it is okay that you sign them up for the mailinglist regarding external promotion during such an event. Other than that the function already exists.

Plase let me know if that is sufficient, then I can close the issue.

**Comment by FemkeXJ** [comment]
Thankss, we are going to look into using the external promotion
