### ISSUE TITLE
ProTube link front page

### ISSUE THREAD

**Issue by sbkoomen** [saproto/saproto#923]
Since the big clean-up of the subsections on the front page a direct link to ProTube seems to be missing. Is this intentional (or was it never there? I'm not really sure)? If not, could it be (re-)added?

**Comment by thijsdortmann** [comment]
As far as I know it was never there. As it's just a menu click away and can be easily reached, I don't think a more direct link is necessary.

**Comment by sbkoomen** [comment]
There is also no link to Protube in the menus though, only to the Protube dashboard and to the Protube Hits, both don't have a link to the actual Protube input screen.

**Comment by jonathanjuursema** [comment]
Has been added to the "For members" menu. :)
