### ISSUE TITLE
Stuk.

### ISSUE THREAD

**Issue by Harladus** [saproto/saproto#930]
![image](https://user-images.githubusercontent.com/29762568/55109577-6e951c00-50d6-11e9-9e4a-2dd73bc080a6.png)

https://www.proto.utwente.nl/companies/6

This page stuk.

**Comment by thijsdortmann** [comment]
These pages are managed by the Officer of External Affairs, and he used HTML instead of Markdown on this page. This results in what you see. @JRitmeester can you fix this? :)

**Comment by JRitmeester** [comment]
This was not by me but I will fix this :)
