### ISSUE TITLE
helper emails not entirely bcc?

### ISSUE THREAD

**Issue by emielsteegh** [saproto/saproto#932]
<Personal info on slack, so removed here.>

just a heads up, I do not know if this is intentional but three email addresses are visible in the "to: " section of the email

**Comment by jonathanjuursema** [comment]
This is right now intentional. The e-mail adresses you see are all the people from the committee the mail is sent to that have helper notifications enabled. The idea is that this helps you to assess if the right people know that there is still people missing.

**Comment by jonathanjuursema** [comment]
We discussed this during the meeting, my comment above is the right summary. :)
