### ISSUE TITLE
Can we have the following sounds in the soundboard? :)

### ISSUE THREAD

**Issue by Vlieking** [saproto/saproto#936]
A fart sound, as suggested by Alfred, and the sound of Sebastiaan saying "Helemaal naar de getver". MP4's are included in the zip file.
[SoundBoardStuff.zip](https://github.com/saproto/saproto/files/3029715/SoundBoardStuff.zip)

**Comment by thijsdortmann** [comment]
We'll discuss these during our meeting and possibly add them after :)

**Comment by JRitmeester** [comment]
[DING DING DING SHAME SHAME.zip](https://github.com/saproto/saproto/files/3053985/DING.DING.DING.SHAME.SHAME.zip)
Let the dawn of an era... commence!

**Comment by thijsdortmann** [comment]
The sounds have been added last week :)
