### ISSUE TITLE
Alphabetise OmNomCom

### ISSUE THREAD

**Issue by JRitmeester** [saproto/saproto#951]
Yesterday I received several complaints from members that it was too difficult to navigate the subcategories on the OmNomCom screen. Perhaps it would be nicer to alphabetise the products within each category.

**Comment by jonathanjuursema** [comment]
It is already possible to re-arrange products within categories per request of the OmNomCom. Before we will consider changing this behaviour, please get someone of the OmNomCom involved in this discussion. :)

**Comment by jonathanjuursema** [comment]
Has this already been discussed with the OmNomCom? If so, what is the outcome? If not, is this still relevant?

**Comment by JRitmeester** [comment]
I have asked Peter about this. The rearranging of products takes an enormous amount of time because you have to shift each product one index at a time, after which the page repeats every single time. This takes stupid amounts of waiting and time. Is there an easier way to reorder them programatically (i.e. by HYT)?

**Comment by jonathanjuursema** [comment]
It's trivial to order products by name, price, calories or other properties of the product. It would be preferable if we can arrange the entire OmNomCom on one such property.

**Comment by jonathanjuursema** [comment]
So what is the desired outcome?

**Comment by JRitmeester** [comment]
Alphabetised, as stated in the initial post.

**Comment by jonathanjuursema** [comment]
Did the OmNomCom also confirm this?

**Comment by emielsteegh** [comment]
Yes
