### ISSUE TITLE
Protube: change code after each submission

### ISSUE THREAD

**Issue by Frankieknarf** [saproto/saproto#955]
After people entered the wrong code to log into Protube, the code doesn't change . This makes it vulnerable to a simple script trying out all 1000 possible codes. I have the feeling that some members implemented this already, as they put in songs in Protube without being anywhere near the Protopolis. 

Proposal: change the Protube screen login code after each wrong submission so that scripting is harder.

**Comment by jonathanjuursema** [comment]
I have the feeling that it would be way more interesting to blacklist bruteforcing IP's for a day or so. :)

**Comment by thijsdortmann** [comment]
I agree with Jonathan. Resetting the code after a wrong submission has a relatively high abuse-potential, where a user can mess with another user trying to enter the code. Implementing a blacklist should be relatively easy and should make it fairly difficult to brute force your way into Protube.

**Comment by jonathanjuursema** [comment]
Due to time constraints we'll put this on the backlog since it doesn't have a high priority, sorry. :(
