### ISSUE TITLE
GMMdocs visibility

### ISSUE THREAD

**Issue by emielsteegh** [saproto/saproto#968]
Hoi beheer 💻 

In GMM 31 🤓  is doorgestemd 📩 dat de GMMdocs 📜 folder 📁  achter een log in 🔏  mag,  het zou ook wel chill ❄️  zijn als dat dan ook daadwerkelijk 🔮  achter een log in 🔐  gezet wordt, anders had die stemming 👍  weinig zin 😨 

Niet de official 🏢 documents 📝 pagina maar wel t gmmdocs 📜 mappie 📂. dus kan dat gefixt 🛠  worden ⌨️ ?

Kusjes 💋

**Comment by jonathanjuursema** [comment]
Done!
