### ISSUE TITLE
Profile page improvements

### ISSUE THREAD

**Issue by jonathanjuursema** [saproto/saproto#97]
The lay-out of the profile page needs to be finalized, and additionally a possibility to upload a profile picture should be baked in.

**Comment by jonathanjuursema** [comment]
Including a way for people to change their profile picture. :)

**Comment by jonathanjuursema** [comment]
@regnerus could you provide a status update?

**Comment by regnerus** [comment]
Going to work on this tonight.

**Comment by jonathanjuursema** [comment]
@regnerus could you please indicate if you can fix this within the next two weeks? Otherwise I'll be unassigning you to make clear there is no-one working on this issue.
