### ISSUE TITLE
ProTube problems

### ISSUE THREAD

**Issue by JRitmeester** [saproto/saproto#973]
ProTube has been very wacky today. I think the oak processionary catterpillars are what is causing all the bugs in Proto.

Symptoms (all persistent after reboot):

- When a song is playing, ProTube does not switch to displaying YouTube but keeps playing photo albums, radio and the audio of the YouTube song, all at once.
- The "time elapsed" counter doesn't move up, i.e. the song never "starts". This causes another problem; when the song is finished, you have to skip it to proceed to the next one.

**Comment by JRitmeester** [comment]
No steps in particular. Search a song and add it. Nothing else really.

**Comment by jonathanjuursema** [comment]
Haven't found a way to reproduce and asking others yielded that they don't seem to encounter this problem. If you find a way to consistently reproduce it, or if it happens often, please re-open this ticket. :)
