### ISSUE TITLE
Restrictions on membership form

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#982]
Hela,

We have Multiple people really testing our become a member form. Therefore we need some restrictions. I propose having no spaces in the zipcode, having a land code seperate from the rest of the phone number and not having capital letters in e-mail. If we encounter more, I will update this.

**Comment by xadya** [comment]
Also add additional info on dashboard link is broken in become a member form

**Comment by jonathanjuursema** [comment]
After discussing with @xadya, we will do this:

- For addresses: address in Dutch will be autocompleted based on zipcode + street number, non-Dutch addresses should be filled manually. No more Google autocomplete form.
- For phone: use two input boxes, one with country prefix, one with local value. Also try to convert existing numbers into new format.
- For e-mail, make make sure you can change capitals in your mail address.
- Become a member form buggy if account is created but not yet member.

**Comment by jonathanjuursema** [comment]
Regarding the "become a member form bug", this is actually intended. Since you're not a member, you hadn't unlocked that step yet. However, the text looked like a link.

I've changed the become a member form so that "locked" steps don't look like a link in anymore.

**Comment by jonathanjuursema** [comment]
Adress lookup with zip and number works!

**Comment by jonathanjuursema** [comment]
I have only been able to provide a clearer error message if the phone validation failed. I've tried to get [this](https://intl-tel-input.com/) to work but wasn't able to after a few tries. Hope this already helps.

Regarding the e-mail, I'm not sure what I should do. I know we've dicussed a number of options, but I've tried reproducing the error and I wasn't able to. :(

**Comment by jonathanjuursema** [comment]
Closed after consultation with @xadya
