### ISSUE TITLE
Contact & For Companies Page on website

### ISSUE THREAD

**Issue by Vlieking** [saproto/saproto#988]
Hai Beheer, 

It caught my attention that as of now our beautiful website does not have a "contact" and "for companies" page. Could these be added? I know there is contact information at the bottom of the site, but most people will sooner look for a contact tab as they have on most websites, or at least we think so. I know pages can be created by the board, and I'd be more than willing to make the pages, but I could not find an option to actually add them to the top menu.

Greetz ja boi Mickelino

**Comment by jonathanjuursema** [comment]
Hey! If you've made an extra page, you can add it to the menu under "Site > Menu". Just don't give it a parent item and it will be put in the main menu bar on the tip. Hope that helps! :)
