### ISSUE TITLE
Shorter link for anonymous email to association board

### ISSUE THREAD

**Issue by sainety** [saproto/saproto#989]
Heyo, 

Right now the link for the page you can use to send an anonymous email to the association board is https://www.proto.utwente.nl/committee/board/send_anonymous_email. We want to promote this possibility more to our member (for example using the narrowcasting), so it would be nice if there could be a shorter link people can navigate to. Is it possible for you guys to create a 'shortcut link' for this webpage?

xx Ninetje

**Comment by jonathanjuursema** [comment]
Are you requesting an S.A. Proto short link service (such as bit.ly or tinyurk, but Proto branded), or just an alternative link? 

If you would like an alternative link, can you please give us a proposal to indicate what would we short enough? :)

**Comment by sainety** [comment]
I think an alternative link works best (similar to proto.utwente.nl/becomeamember and such), because it is easily recognisable (which tinyurl/bit.ly links aren't that much). 
Is proto.utwente.nl/anonmail a good one?

**Comment by sainety** [comment]
Conclusion right now: A general short url service (using a new domain name) will be created so we can use this going forward.

**Comment by jonathanjuursema** [comment]
Don't forget to create the short URL [here](https://www.proto.utwente.nl/short_url/edit/new). @sainety
