### ISSUE TITLE
Timetable op schermen in Proto

### ISSUE THREAD

**Issue by hanotonah** [saproto/saproto#990]
Op aanvraag vanuit de slack, hier een issue!

Frank zou het heel erg fijn vinden als de timetables van CreaTe en ITech weer gedisplayed kunnen worden op de schermen. Kan dat? :D

Succes!!

**Comment by jonathanjuursema** [comment]
Should be fixed in about an hour.

**Comment by jonathanjuursema** [comment]
Are imported to Google Calendar, should display correctly tomorrow. If not, let me know. :)
