### ISSUE TITLE
Adjustment to text Poster Request form 

### ISSUE THREAD

**Issue by sainety** [saproto/saproto#993]
![image](https://user-images.githubusercontent.com/35506182/64715980-c62b1680-d4c1-11e9-86be-a36fbf991865.png)

Heyo,

Any chance this line on the poster request form could be changed to, "If you have any questions please contact the Graphicie at graphicie@proto.utwente.nl"? We can't edit this page ourselves sadly enough. 

Thanks, <3 Ninetje

**Comment by jonathanjuursema** [comment]
Done!
