### ISSUE TITLE
Allow for removing of the automatically generated page header for pages (or change styling)

### ISSUE THREAD

**Issue by Vlieking** [saproto/saproto#995]
Hai Beheer, 

When creating a page on the website, the top header cannot be edited and will always retain the same (quite small) header size. Would it be possible to also make this editable / bigger? :) (@JonaMata agrees :) ) (im using him hihi )

Greets, Mick

**Comment by jonathanjuursema** [comment]
I'm not really sure I understand what it is you would like to see. Could you perhaps include a screenshot/photoshop of what you mean, and what you would like to see?

**Comment by Vlieking** [comment]
![image](https://user-images.githubusercontent.com/32953319/65224082-c1b6bd00-dac2-11e9-8ca6-07b5a129f0b3.png)
"Contact" was automatically added by the toolie, and cannot be removed nor made bigger as far as I could figure out. So a bigger top header is kind of impossible, or it would have to be below the smaller top header which looks odd.
