### ISSUE TITLE
Wiki: add more information to login page

### ISSUE THREAD

**Issue by FrankvanMourik** [saproto/saproto#996]
Logging in on the Proto wiki can only be done with one's Proto username and password, however this is stated nowhere. Especially for less-active members, this might be confusing. I propose to add a line in the sense of "Logging in can be done with you **Proto username and password**. Your Proto username can be found on your dashboard, where you can reset your password as well."

**Comment by jonathanjuursema** [comment]
Should be fixed. I know for sure there was a good reason why we didn't have this, but the fix seems super easy. If the log-in help stops working, please re-open this issue.

For now I've just changed `/var/www/wiki/public/inc/lang/en/login.txt`...
